// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ConflictReport 冲突报告
 */
export interface ConflictReport {
    /**
     * Conflicts 冲突文件列表
     */
    "conflicts": FileConflict[] | null;

    /**
     * TotalConflicts 总冲突数
     */
    "totalConflicts": number;
}

/**
 * ConflictType 冲突类型
 */
export enum ConflictType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ConflictContentModified 内容冲突：本地和远端文件内容都被修改（hash 不同）
     */
    ConflictContentModified = "content_modified",

    /**
     * ConflictSizeMismatch 大小不匹配：路径存在但文件大小不同（快速检测，可能后续 hash 验证为同一内容）
     */
    ConflictSizeMismatch = "size_mismatch",
};

/**
 * FileConflict 文件冲突详情
 */
export interface FileConflict {
    /**
     * Path 冲突文件的相对路径
     */
    "path": string;

    /**
     * Type 冲突类型
     */
    "type": ConflictType;

    /**
     * LocalModTime 本地文件修改时间
     */
    "localModTime": time$0.Time;

    /**
     * RemoteModTime 远端文件修改时间
     */
    "remoteModTime": time$0.Time;

    /**
     * LocalSize 本地文件大小
     */
    "localSize": number;

    /**
     * RemoteSize 远端文件大小
     */
    "remoteSize": number;

    /**
     * LocalHash 本地文件哈希
     */
    "localHash"?: string;

    /**
     * RemoteHash 远端文件哈希
     */
    "remoteHash"?: string;

    /**
     * SuggestedStrategy 建议的解决策略
     */
    "suggestedStrategy": ResolutionStrategy;

    /**
     * HashFailed 标记哈希计算失败的条目（R27 code_review P2-1 修复）。
     * 此类条目本应人工审查，ResolveConflictsLocked 检测到 HashFailed 时
     * 不覆盖 SuggestedStrategy，直接计入 manual 计数。
     */
    "hashFailed"?: boolean;
}

/**
 * ResolutionStrategy 冲突解决策略
 */
export enum ResolutionStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ResolveForceRemote 强制使用远端版本
     */
    ResolveForceRemote = "force_remote",

    /**
     * ResolveForceLocal 强制保留本地版本
     */
    ResolveForceLocal = "force_local",

    /**
     * ResolveManual 手动解决（由调用方决定）
     */
    ResolveManual = "manual",
};
