// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    LitematicBlockStat,
    LitematicMeta,
    LitematicVoxelData,
    ModRequirement,
    NestedPattern,
    ResourceType,
    ResourceTypeRegistry,
    Variant,
    VoxelGroup,
    ZipEntryMatch
} from "./models.js";
