// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LitematicBlockStat 方块类型统计
 */
export interface LitematicBlockStat {
    /**
     * "minecraft:stone"
     */
    "name": string;
    "count": number;
}

/**
 * LitematicMeta 投影文件元数据（对应 .litematic 中 Metadata compound）
 */
export interface LitematicMeta {
    "name": string;
    "author": string;
    "description": string;

    /**
     * unix 毫秒
     */
    "timeCreated": number;

    /**
     * unix 毫秒
     */
    "timeModified": number;

    /**
     * MC 数据版本号
     */
    "minecraftDataVersion": number;

    /**
     * Litematica 格式版本
     */
    "version": number;

    /**
     * 非空气方块总数
     */
    "totalBlocks": number;

    /**
     * 包围盒总体积（含空气）
     */
    "totalVolume": number;

    /**
     * [x, y, z]
     */
    "enclosingSize": number[];
    "regionCount": number;

    /**
     * 按数量降序排列
     */
    "blockStats": LitematicBlockStat[] | null;

    /**
     * "data:image/png;base64,..." 或 ""
     */
    "previewImage": string;
}

/**
 * LitematicVoxelData 体素渲染数据
 */
export interface LitematicVoxelData {
    /**
     * 包围盒尺寸 [x, y, z]
     */
    "size": number[];

    /**
     * 按颜色分组的方块
     */
    "groups": VoxelGroup[] | null;

    /**
     * 超过上限被截断
     */
    "truncated": boolean;

    /**
     * 生效的渲染上限
     */
    "maxBlocks": number;
}

/**
 * VoxelGroup 同一颜色的方块组
 */
export interface VoxelGroup {
    /**
     * 十六进制颜色 "#7F7F7F"
     */
    "color": string;

    /**
     * [[x,y,z], ...]
     */
    "positions": number[][] | null;
}
