// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig 应用持久化配置
 * 独立路径下沉为 CustomRoots map（ADR-095）：以资源类型 id 为 key（如 "ysm"→"D:/.../ysm"），
 * 取代过去 YsmRoot/ResourcepackRoot/... 7 个独立字段，避免资源类型膨胀时结构体硬编码。
 * configField 语义：存储的是资源类型 id（非结构体字段名），具体路由逻辑在 internal/app/resource_bindings.go
 * 统一查 CustomRoots map，检索 "customRoots" 即可抓到全貌。
 */
export interface AppConfig {
    /**
     * 统一文件存储根目录，各类型默认存 {filesRoot}/{subDir}/
     */
    "filesRoot": string;

    /**
     * 资源类型 id → 自定义根路径（留空则回退 FilesRoot）
     */
    "customRoots": { [_ in string]?: string } | null;

    /**
     * Deprecated: 以下字段为历史兼容保留，新代码请使用 FilesRoot/CustomRoots
     */
    "ysmRoot"?: string;
    "resourcepackRoot"?: string;
    "shaderpackRoot"?: string;
    "schematicRoot"?: string;
    "litematicRoot"?: string;
    "mmdRoot"?: string;
    "vrcRoot"?: string;
    "mcRoot": string;
    "linkMode": string;
    "theme": string;
    "mirror": string;

    /**
     * 3D 体素渲染上限，0=使用默认 200000
     */
    "voxelMaxBlocks": number;

    /**
     * 运行阈值（ADR-062 可配置化下沉：0=使用各包默认常量，行为零漂移）
     * 扫描缓存 TTL 毫秒，0=默认 30s（scanner.scanCacheTTL）
     */
    "scanCacheTtlMs": number;

    /**
     * 下载超时秒，0=默认 300s（download.defaultTimeout）
     */
    "downloadTimeoutSec": number;

    /**
     * 日志条数上限，0=默认 500（logs.maxLogEntries）
     */
    "logMaxEntries": number;

    /**
     * 日志单字段长度上限，0=默认 1024（logs.maxFieldLen）
     */
    "logMaxFieldLen": number;

    /**
     * .corrupt 备份保留天数，0=默认 7（logs.corruptRetentionDays）
     */
    "logCorruptRetentionDays": number;

    /**
     * 预览/元数据整读上限 MB，0=默认 50（fileops.maxPreviewRead）
     */
    "previewReadLimitMb": number;

    /**
     * 版本检查间隔毫秒，0=默认 6h（前端 version-updater CHECK_INTERVAL）
     */
    "updateCheckIntervalMs": number;

    /**
     * 版本检查超时毫秒，0=默认 30s（前端 version-updater CHECK_TIMEOUT）
     */
    "updateCheckTimeoutMs": number;

    /**
     * 窗口状态（合并到主配置，避免 window_state.json 散落）
     */
    "winX": number;
    "winY": number;
    "winW": number;
    "winH": number;
    "winRelX": number;
    "winRelY": number;
    "winScrW": number;
    "winScrH": number;
}

/**
 * AuthorInfo 作者信息（含模型计数）
 */
export interface AuthorInfo {
    "Name": string;
    "Count": number;

    /**
     * 该作者第一个模型文件路径（用于提取头像）
     */
    "SampleFile"?: string;
}

/**
 * BedrockModel 基岩版模型几何体摘要（用于 2D 预览）
 */
export interface BedrockModel {
    "boneCount": number;
    "cubeCount": number;

    /**
     * 纹理图 base64 data URI（单纹理兼容）
     */
    "texture"?: string;

    /**
     * 多纹理 base64 data URI 数组（全量，2D 预览用）
     */
    "textures"?: string[] | null;

    /**
     * 纹理文件名（去扩展名），与 Textures 同序
     */
    "textureNames"?: string[] | null;

    /**
     * TextureCategories 纹理分类标记，与 TextureNames 同序同长度。
     * "player" = player.texture[] 声明，可切换皮肤；
     * "projectile" / "vehicle" / "arrow" = 组件专属纹理（不可切换）；
     * "" = 未分类（无 ysm.json 时，前端兜底显示）。
     */
    "textureCategories"?: string[] | null;

    /**
     * ComponentTextures 每组件独立纹理（ADR-114 perComponent）。
     * key = 组件源模型名（main/arm/arrow/minecart/boat/foxcar/trident）
     * value = 该组件声明的纹理 base64 data URI 数组（通常 1 张）
     * 3D 渲染用此字段；为空时 fallback 到 Textures[0]。
     */
    "componentTextures"?: { [_ in string]?: string[] | null } | null;

    /**
     * 组件源模型文件名（去扩展名，如 main/arm/arrow），UI 组件名用
     */
    "sourceName"?: string;

    /**
     * "1.12.0" 等
     */
    "format"?: string;
    "texWidth"?: number;
    "texHeight"?: number;
    "bones"?: Bone2D[] | null;

    /**
     * 动画 JSON 字符串数组
     */
    "animations"?: string[] | null;

    /**
     * L0/L1 派生的子模型清单（多角色包内切换用）
     */
    "subModels"?: SubModel[] | null;

    /**
     * ysm.json metadata 段（名称/许可/作者/链接，详情页用）
     */
    "metadata"?: YsmMetadata | null;

    /**
     * zip 内文件归属清单（parseGlobalResources 轻量版，只识别不解析）
     */
    "fileInventory"?: FileInventory | null;
}

/**
 * Bone2D 骨骼简化信息（只用于 2D 线条图）
 */
export interface Bone2D {
    "name": string;
    "parent"?: string;
    "pivot"?: number[];
    "rotation"?: number[];
    "cubes": Cube2D[] | null;

    /**
     * "player" / "projectile" / "vehicle"
     */
    "groupId"?: string;
}

/**
 * Cube2D 立方体信息
 */
export interface Cube2D {
    "origin": number[];
    "size": number[];
    "pivot"?: number[];
    "uv"?: number[];

    /**
     * 每面独立 UV（JSON 字符串）
     */
    "faceUV"?: string;
    "rotation"?: number[];

    /**
     * 纹理槽（从 cube.texture 解析）
     */
    "texSlot": number;

    /**
     * Blockbench 膨胀（正=外扩，负=收缩），渲染时 origin-=i、size+=2i
     */
    "inflate"?: number;

    /**
     * Blockbench 镜像（沿 X 翻转几何）
     */
    "mirror"?: boolean;
}

/**
 * CustomFileInfo custom 目录下的文件信息
 */
export interface CustomFileInfo {
    "Name": string;
    "LinkType": LinkType;
}

/**
 * DownloadTask 下载队列任务。
 * 归属（ADR-145）：同上，跨包契约 DTO 下沉至 types（JSON tag 原样保留 → bindings 零漂移）。
 */
export interface DownloadTask {
    "url": string;
    "saveDir": string;
    "name": string;
    "size": number;
}

/**
 * FileInventory zip 内文件归属清单（对齐 Modern YSM parseGlobalResources 的分流思想，
 * 但只识别归属、不解析内容——不造双路径，前端直接消费准确清单，不再事后按文件名猜）。
 */
export interface FileInventory {
    /**
     * *.animation.json（真动画文件路径）
     */
    "animations"?: string[] | null;

    /**
     * *.animation_controller.json（动画控制器）
     */
    "controllers"?: string[] | null;

    /**
     * *.lang（本地化资源）
     */
    "langFiles"?: string[] | null;

    /**
     * *.inc（include 资源）
     */
    "incFiles"?: string[] | null;

    /**
     * 旧格式几何（main.json/arm.json/arrow.json/info.json，无 ysm.json 场景）
     */
    "legacyModels"?: string[] | null;

    /**
     * avatar/ 下的图片（作者头像，非主纹理）
     */
    "avatars"?: string[] | null;

    /**
     * Truncated 标记 classifyFileInventory 达到 maxClassifyEntries 封顶，
     * 返回的 inventory 不完整。调用方应据此向用户披露「清单可能不全」。
     * R29 code_review P3-1：旧实现静默截断，调用方无法区分完整 vs 截断。
     */
    "truncated"?: boolean;
}

/**
 * ImportFileItem 文件夹型模型整组导入的文件项（ADR-038 关联：解压目录整组导入）
 */
export interface ImportFileItem {
    /**
     * 相对文件夹根的路径（正斜杠，保留子目录层级）
     */
    "RelPath": string;

    /**
     * 文件内容
     */
    "Base64": string;
}

/**
 * ImportLog 应用操作日志（导入、扫描、下载、同步等）
 */
export interface ImportLog {
    "ModelName": string;
    "SourcePath": string;
    "TargetDir": string;
    "FileSize": number;
    "Status": string;
    "ErrorMsg"?: string;
    "Timestamp": number;

    /**
     * import / scan / download / sync / rename / delete
     */
    "Operation"?: string;

    /**
     * debug/info/warn/error/fatal
     */
    "Level"?: LogLevel;
}

/**
 * InstanceStatus 整合包状态
 */
export interface InstanceStatus {
    "Name": string;
    "CustomDir": string;

    /**
     * "complete" | "missing" | "extra"
     */
    "Status": string;

    /**
     * 已同步文件数（Files 长度，前端排序用）
     */
    "Synced": number;

    /**
     * 完整路径
     */
    "Missing": string[] | null;

    /**
     * 文件名（供展示）
     */
    "Extra": string[] | null;
    "Disabled": string[] | null;
    "HasYSM": boolean;

    /**
     * 当前资源类型对应的 mod 是否存在
     */
    "HasMod": boolean;

    /**
     * custom 目录下每个文件的链接类型
     */
    "Files": CustomFileInfo[] | null;
}

/**
 * LauncherInstance is a Minecraft instance discovered from a launcher directory.
 * GameRoot is the shared .minecraft directory; GameDir is the actual run directory
 * after applying the launcher's per-instance isolation setting.
 */
export interface LauncherInstance {
    "launcher": string;
    "name": string;
    "gameVersion": string;
    "gameRoot": string;
    "gameDir": string;
    "customDir": string;
    "exists": boolean;
}

/**
 * LinkType 链接类型
 */
export enum LinkType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LinkCopy = "copy",
    LinkHard = "hardlink",
    LinkSym = "symlink",
    LinkUnknown = "unknown",
};

/**
 * LitematicBlockStat 方块类型统计
 */
export interface LitematicBlockStat {
    /**
     * "minecraft:stone"
     */
    "name": string;
    "count": number;
}

/**
 * LitematicMeta 投影文件元数据（对应 .litematic 中 Metadata compound）
 */
export interface LitematicMeta {
    "name": string;
    "author": string;
    "description": string;

    /**
     * unix 毫秒
     */
    "timeCreated": number;

    /**
     * unix 毫秒
     */
    "timeModified": number;

    /**
     * MC 数据版本号
     */
    "minecraftDataVersion": number;

    /**
     * Litematica 格式版本
     */
    "version": number;

    /**
     * 非空气方块总数
     */
    "totalBlocks": number;

    /**
     * 包围盒总体积（含空气）
     */
    "totalVolume": number;

    /**
     * [x, y, z]
     */
    "enclosingSize": number[];
    "regionCount": number;

    /**
     * 按数量降序排列
     */
    "blockStats": LitematicBlockStat[] | null;

    /**
     * "data:image/png;base64,..." 或 ""
     */
    "previewImage": string;
}

/**
 * LitematicVoxelData 体素渲染数据
 */
export interface LitematicVoxelData {
    /**
     * 包围盒尺寸 [x, y, z]
     */
    "size": number[];

    /**
     * 按颜色分组的方块
     */
    "groups": VoxelGroup[] | null;

    /**
     * 超过上限被截断
     */
    "truncated": boolean;

    /**
     * 生效的渲染上限
     */
    "maxBlocks": number;
}

/**
 * LogLevel 日志级别（诊断页按 Level 过滤；向后兼容——旧日志无此字段时前端按 Status 兜底）
 */
export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LevelDebug = "debug",
    LevelInfo = "info",
    LevelWarn = "warn",
    LevelError = "error",
    LevelFatal = "fatal",
};

/**
 * ModRequirement mod 依赖声明（ADR-110）：
 *   - JarKeywords：文件名关键词匹配（如 "mmdskin" 匹配 mmdskin-1.0.jar）
 *   - ModID/DisplayName：内容检测型（读 mods.toml，如 touhou_little_maid）
 * 
 * 两者互斥：有 ModID 时优先内容检测，否则用 JarKeywords 文件名匹配。
 */
export interface ModRequirement {
    /**
     * 文件名关键词（小写匹配）
     */
    "jarKeywords"?: string[] | null;

    /**
     * mods.toml 中的 modId
     */
    "modId"?: string;

    /**
     * mods.toml 中的 displayName
     */
    "displayName"?: string;
}

/**
 * ModelEntry 模型文件条目
 */
export interface ModelEntry {
    "Name": string;
    "Size": number;
    "Path": string;
    "Ext": string;

    /**
     * SHA256
     */
    "Hash": string;

    /**
     * Unix 时间戳（毫秒）
     */
    "ModTime": number;

    /**
     * 是否有标签
     */
    "HasTags": boolean;

    /**
     * Type 资源类型 ID（如 "ysm"/"EntityPlayer"/"resourcepack"）。
     * ScanModelEntriesFiltered 按 rtype 过滤时自动填充；未指定 rtype 时为 ""。
     * 前端据此展示类型图标/标签，无需从 Path 反推类型。
     */
    "type"?: string;

    /**
     * SubDir MMD 用途子目录分组（ADR-096）：文件位于 mmdSubdirNames 命中的
     * 用途子目录内时填子目录名（如 SceneModel/CustomAnim）；根下或其他类型恒为 ""。
     * 前端据此按子目录分组展示，无需从 Path 推导。
     */
    "subdir"?: string;
}

/**
 * NestedPattern 嵌套模型模式配置（ADR-XXX）：
 * 支持任意深度的嵌套路径检测，用于识别多层嵌套的模型结构。
 * 例如 maid-model 的 assets/<namespace>/maid_model.json 结构，
 * 或其他更深层的嵌套目录结构。
 * 
 * 配置示例：
 * 
 * 	{
 * 	  "entryDir": "assets",           // 入口目录（相对于模型根目录）
 * 	  "entryFiles": ["maid_model.json", "chair_model.json"]  // 入口文件名
 * 	}
 * 
 * 运行时行为：
 *  1. 从模型根目录开始，递归查找 entryDir 指定的目录
 *  2. 在 entryDir 下查找 entryFiles 中任一文件
 *  3. 找到后将该目录识别为模型目录（含层级信息）
 */
export interface NestedPattern {
    /**
     * 入口目录名（如 "assets"），为空则直接在根目录查找
     */
    "entryDir": string;

    /**
     * 入口文件名列表（如 ["maid_model.json"]）
     */
    "entryFiles": string[] | null;

    /**
     * 最大递归深度（默认 10），防止无限递归
     */
    "maxDepth"?: number;
}

/**
 * PackInfo 模型整合包信息（ysm-pack.json）
 */
export interface PackInfo {
    "name": string;
    "description": string;

    /**
     * ysm-pack.png 的 base64 data URI
     */
    "imageBase64"?: string;
}

/**
 * PackMetaView ReadPackMeta 的返回视图（pack.mcmeta 摘要，ADR-143 P1 struct 化）
 */
export interface PackMetaView {
    "pack_format": number;
    "description": string;
    "thumbnail": string;
    "supported_formats"?: number[] | null;
    "min_format"?: number[] | null;
    "max_format"?: number[] | null;
}

/**
 * PackModelDetail ListPackModelsDetail 单条模型（路径 + 立方体数）
 */
export interface PackModelDetail {
    "path": string;
    "cubes": number;
}

/**
 * PackModelDetailList ListPackModelsDetail 的返回（封顶 + total 全量）
 */
export interface PackModelDetailList {
    "models": PackModelDetail[] | null;
    "total": number;
}

/**
 * QueueStatusInfo 下载队列状态（替代多返回值，Wails 自动映射为 JS object）。
 * 归属（ADR-145）：跨包契约 DTO 下沉至 types——go/cli 定义 AppService 接口时
 * 需引用本类型，若不随 DTO 下沉则 cli 得反向 import internal/app（死结）。
 */
export interface QueueStatusInfo {
    "remaining": number;
    "running": boolean;
}

/**
 * ResourceSyncItem 单个资源文件的同步状态
 */
export interface ResourceSyncItem {
    "path": string;
    "name": string;
    "status": SyncStatus;
    "type": string;
    "icon": string;
    "size": number;

    /**
     * IsDir 标记该条目是文件夹（true）还是文件（false）
     * 前端据此分流渲染：文件夹 → sm-dir（可展开），文件 → sm-item（扁平）
     */
    "isDir": boolean;

    /**
     * SubDir MMD 子目录分组（ADR-096：dirLevel 同步单元若位于
     * mmdSubdirNames 命中的用途子目录内，填子目录名；根下为 ""=EntityPlayer）
     */
    "subdir"?: string;

    /**
     * Children 子条目列表（文件夹级同步单元的内部文件状态）
     * 当同步单元是文件夹且存在内容级差异时，填充此字段
     * 用于展示文件夹内部每个文件的真实同步状态
     */
    "children"?: ResourceSyncItem[] | null;
}

/**
 * ResourceSyncResult 资源同步结果
 */
export interface ResourceSyncResult {
    "synced": string[] | null;

    /**
     * 全局有但整合包没有（可推送）
     */
    "missing": string[] | null;

    /**
     * 整合包有但全局没有（可拉取）
     */
    "extra": string[] | null;
}

/**
 * ResourceType 一种受支持的资源类型定义
 */
export interface ResourceType {
    "id": string;
    "name": string;
    "icon": string;

    /**
     * 所属分组（ADR-092）：minecraft / minecraft-mod / mmd / vrm / other
     */
    "group": string;

    /**
     * 分组显示名，仅该组首个类型携带（消除双写）
     */
    "groupLabel"?: string;

    /**
     * 分组图标，同上
     */
    "groupIcon"?: string;
    "extensions": string[] | null;
    "storageSubDir": string;

    /**
     * 整合包内实际存放目录（安装+扫描统一路径）
     */
    "instanceDir": string;
    "instanceLevel": boolean;

    /**
     * "3d" / "thumbnail" / "none"
     */
    "preview": string;

    /**
     * "ysm" / "mcmeta" / "shader" / "zipentry" / "extension"
     */
    "detector": string;

    /**
     * AppConfig 字段名（如 YsmRoot）
     */
    "configField": string;

    /**
     * AppConfig 回退字段名（如 VrcRoot→MmdRoot）
     */
    "configFallback": string;

    /**
     * 目录型资源（删除/同步整目录）
     */
    "isDir": boolean;

    /**
     * 扩展名参与 SHA256 哈希（ShouldHashExt 注册表驱动）
     */
    "hashable": boolean;

    /**
     * 文件夹级资源同步（sync.SyncResourcesDirLevel）
     */
    "dirLevelSync": boolean;

    /**
     * instance 视图额外扫描整合包目录（非模型类型兜底）
     */
    "scanInstance": boolean;

    /**
     * 兜底扫描只认此目录名（空=不限定，ScanInstance=true 时生效）
     */
    "fallbackDir"?: string;

    /**
     * 安装白名单扩展名（空=全部放行，仅可执行文件黑名单除外）
     */
    "installExts": string[] | null;

    /**
     * ZIP 内容特征条目（importer.DetectZipType 注册表驱动）
     */
    "zipEntries": ZipEntryMatch[] | null;

    /**
     * 嵌套模型目录（ADR-095）：模型入口在 assets/<namespace>/ 下（如 maid-model 的 maid_model.json）
     */
    "nestedModelDir": boolean;

    /**
     * 嵌套模式配置（ADR-XXX）：支持任意深度的嵌套路径检测
     */
    "nestedPatterns"?: NestedPattern[] | null;

    /**
     * 检测优先级（同指纹计数打平时高者胜：专用指纹类型 > 通用指纹类型，如 maid-model > resourcepack）
     */
    "priority"?: number;

    /**
     * mod 依赖声明（ADR-110：mod 下沉注册表）
     */
    "mod"?: ModRequirement | null;

    /**
     * 格式变体（ADR-111：variants 解耦，按扩展名分发预览器）
     */
    "variants"?: Variant[] | null;
}

/**
 * ResourceTypeRegistry 资源类型注册表
 */
export interface ResourceTypeRegistry {
    "resourceTypes": ResourceType[] | null;
}

/**
 * RuntimeLog 运行时日志（watcher/sync 等标准库 log 输出，诊断页可见）
 */
export interface RuntimeLog {
    "Message": string;
    "Timestamp": number;

    /**
     * 默认 info（标准库 log 无级别）
     */
    "Level"?: LogLevel;
}

/**
 * SearchResult 模型搜索结果
 */
export interface SearchResult {
    "name": string;
    "path": string;
    "boneCount": number;
    "cubeCount": number;
    "texWidth": number;
    "texHeight": number;
    "hasError": boolean;

    /**
     * 资源类型 ID（跨类型搜索时携带）
     */
    "type"?: string;
}

/**
 * ShaderpackLang ReadShaderpackLang 的返回（光影包 lang/en_US.lang 摘要）
 */
export interface ShaderpackLang {
    "name": string;
    "entries": { [_ in string]?: string } | null;
}

/**
 * SubModel 子模型条目（多角色加载）。
 * 来源优先级：L0（maid_model.json model[] 权威清单）→ L1（geoFiles 枚举兜底）。
 */
export interface SubModel {
    /**
     * 角色名（L0 直接取自 model[].name；L1 取自 geometry 文件名去后缀）
     */
    "name": string;

    /**
     * 条目的 zip 内相对路径（用于精确比对去重）
     */
    "sourcePath"?: string;

    /**
     * 默认绑定的纹理槽索引（对应 Textures 数组下标）
     */
    "texSlot"?: number;
}

/**
 * SyncResolveResult ResolveConflicts 的返回结果
 */
export interface SyncResolveResult {
    /**
     * Resolved 成功解决数
     */
    "resolved": number;

    /**
     * Failed 解决失败数
     */
    "failed": number;

    /**
     * Manual 需人工介入数
     */
    "manual": number;
}

/**
 * SyncScanDirs GetSyncScanDirs 的返回（同步页展示实际扫描目录对）
 */
export interface SyncScanDirs {
    "global": string;
    "instance": string;
    "warningCode": string;
    "warningParams": { [_ in string]?: string } | null;
}

/**
 * SyncStatus 资源文件同步状态
 */
export enum SyncStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SyncStatusSynced = "synced",
    SyncStatusMissing = "missing",
    SyncStatusOptional = "optional",
    SyncStatusDisabled = "disabled",
    SyncStatusLegacy = "legacy",

    /**
     * SyncStatusDiverged 文件夹级聚合状态：两侧同名文件夹存在内容级差异
     * 子文件有 missing/optional/disabled 时，父文件夹标记为 diverged
     * 前端渲染：继承 missing 的可操作属性（⬇️图标 + 推送按钮）
     */
    SyncStatusDiverged = "diverged",
};

/**
 * Variant 格式变体声明（ADR-111：variants 解耦）：
 * 同一资源类型内不同格式变体的预览器路由。
 * 例如角色模型（EntityPlayer）内 .pmx 用 mmd 预览器，.vrm 用 vrm 预览器。
 */
export interface Variant {
    /**
     * 扩展名（如 ".pmx"、".vrm"）
     */
    "ext": string;

    /**
     * 预览器 id（如 "mmd"、"vrm"）
     */
    "preview": string;
}

/**
 * VersionInstance 整合包信息
 */
export interface VersionInstance {
    "Name": string;
    "VersionDir": string;
    "CustomDir": string;
    "Exists": boolean;
}

/**
 * VoxelGroup 同一颜色的方块组
 */
export interface VoxelGroup {
    /**
     * 十六进制颜色 "#7F7F7F"
     */
    "color": string;

    /**
     * [[x,y,z], ...]
     */
    "positions": number[][] | null;
}

/**
 * WindowState 窗口位置
 */
export interface WindowState {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

/**
 * WorkshopCreator 创作者条目
 * Type 是平台标签，分号分隔，如 "bilibili;afdian"
 */
export interface WorkshopCreator {
    "name": string;
    "desc": string;
    "type"?: string;
    "role"?: string;
}

/**
 * WorkshopPresetSearch 预设搜索词
 */
export interface WorkshopPresetSearch {
    "label": string;
    "q": string;
}

/**
 * WorkshopSite 创意工坊站点配置
 */
export interface WorkshopSite {
    "id": string;
    "icon": string;
    "label": string;
    "url": string;
    "desc": string;
    "group": string;
    "searchUrl"?: string;
    "presetSearches"?: WorkshopPresetSearch[] | null;
}

/**
 * YsmAuthor 作者条目
 */
export interface YsmAuthor {
    /**
     * 作者名
     */
    "name"?: string;

    /**
     * 角色（模型原作/动画原作/材质等）
     */
    "role"?: string;

    /**
     * 作者留言
     */
    "comment"?: string;

    /**
     * 头像路径（zip 内相对路径，如 avatar/wmdj.jpg）
     */
    "avatar"?: string;

    /**
     * 联系方式（平台→URL，如 Bilibili/Afdian）
     */
    "contact"?: { [_ in string]?: string } | null;
}

/**
 * YsmLicense 许可信息（wine_fox：{"type": "CC BY-NC-SA 4.0"}）
 */
export interface YsmLicense {
    "type"?: string;
    "description"?: string;
}

/**
 * YsmMetadata ysm.json 的 metadata 段（模型详情：名称/许可/作者/链接）。
 * 字段对齐 Modern YSM RawMetadata（RawYsmModel.java L191-208）+ 真实 ysm.json 格式
 * （wine_fox：license 为 {type} 对象、authors[].contact 为平台→URL map、authors[].avatar 为路径字符串）。
 */
export interface YsmMetadata {
    /**
     * 模型名（如 "Wine Fox（酒狐）"）
     */
    "name"?: string;

    /**
     * 提示/简介（可含 \n 多行）
     */
    "tips"?: string;

    /**
     * 许可信息
     */
    "license"?: YsmLicense | null;

    /**
     * 作者列表（模型/动画/材质等角色）
     */
    "authors"?: YsmAuthor[] | null;

    /**
     * 附加链接（平台→URL）
     */
    "links"?: { [_ in string]?: string } | null;
}

/**
 * ZipEntryMatch ZIP 内容特征条目：检测 ZIP 内是否存在命中条目名
 */
export interface ZipEntryMatch {
    /**
     * 条目名（小写比较）
     */
    "name": string;

    /**
     * "exact" / "prefix" / "suffix"
     */
    "match": string;
}
