// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig 应用持久化配置
 * 独立路径下沉为 CustomRoots map（ADR-095）：以资源类型 id 为 key（如 "ysm"→"D:/.../ysm"），
 * 取代过去 YsmRoot/ResourcepackRoot/... 7 个独立字段，避免资源类型膨胀时结构体硬编码。
 * configField 语义：存储的是资源类型 id（非结构体字段名），具体路由逻辑在 internal/app/resource_bindings.go
 * 统一查 CustomRoots map，检索 "customRoots" 即可抓到全貌。
 */
export interface AppConfig {
    /**
     * 统一文件存储根目录，各类型默认存 {filesRoot}/{subDir}/
     */
    "filesRoot": string;

    /**
     * 资源类型 id → 自定义根路径（留空则回退 FilesRoot）
     */
    "customRoots": { [_ in string]?: string } | null;

    /**
     * Deprecated: 以下字段为历史兼容保留，新代码请使用 FilesRoot/CustomRoots
     */
    "ysmRoot"?: string;
    "resourcepackRoot"?: string;
    "shaderpackRoot"?: string;
    "schematicRoot"?: string;
    "litematicRoot"?: string;
    "mmdRoot"?: string;
    "vrcRoot"?: string;
    "mcRoot": string;
    "linkMode": string;
    "theme": string;
    "mirror": string;

    /**
     * 3D 体素渲染上限，0=使用默认 200000
     */
    "voxelMaxBlocks": number;

    /**
     * 运行阈值（ADR-062 可配置化下沉：0=使用各包默认常量，行为零漂移）
     * 扫描缓存 TTL 毫秒，0=默认 30s（scanner.scanCacheTTL）
     */
    "scanCacheTtlMs": number;

    /**
     * 下载超时秒，0=默认 300s（download.defaultTimeout）
     */
    "downloadTimeoutSec": number;

    /**
     * 日志条数上限，0=默认 500（logs.maxLogEntries）
     */
    "logMaxEntries": number;

    /**
     * 日志单字段长度上限，0=默认 1024（logs.maxFieldLen）
     */
    "logMaxFieldLen": number;

    /**
     * .corrupt 备份保留天数，0=默认 7（logs.corruptRetentionDays）
     */
    "logCorruptRetentionDays": number;

    /**
     * 预览/元数据整读上限 MB，0=默认 50（fileops.maxPreviewRead）
     */
    "previewReadLimitMb": number;

    /**
     * 版本检查间隔毫秒，0=默认 6h（前端 version-updater CHECK_INTERVAL）
     */
    "updateCheckIntervalMs": number;

    /**
     * 版本检查超时毫秒，0=默认 30s（前端 version-updater CHECK_TIMEOUT）
     */
    "updateCheckTimeoutMs": number;

    /**
     * 窗口状态（合并到主配置，避免 window_state.json 散落）
     */
    "winX": number;
    "winY": number;
    "winW": number;
    "winH": number;
    "winRelX": number;
    "winRelY": number;
    "winScrW": number;
    "winScrH": number;
}

/**
 * AuthorInfo 作者信息（含模型计数）
 */
export interface AuthorInfo {
    "Name": string;
    "Count": number;

    /**
     * 该作者第一个模型文件路径（用于提取头像）
     */
    "SampleFile"?: string;
}

/**
 * BedrockModel 基岩版模型几何体摘要（用于 2D 预览）
 */
export interface BedrockModel {
    "boneCount": number;
    "cubeCount": number;

    /**
     * 纹理图 base64 data URI（单纹理兼容）
     */
    "texture"?: string;

    /**
     * 多纹理 base64 data URI 数组（全量，2D 预览用）
     */
    "textures"?: string[] | null;

    /**
     * 纹理文件名（去扩展名），与 Textures 同序
     */
    "textureNames"?: string[] | null;

    /**
     * TextureCategories 纹理分类标记，与 TextureNames 同序同长度。
     * "player" = player.texture[] 声明，可切换皮肤；
     * "projectile" / "vehicle" / "arrow" = 组件专属纹理（不可切换）；
     * "" = 未分类（无 ysm.json 时，前端兜底显示）。
     */
    "textureCategories"?: string[] | null;

    /**
     * ComponentTextures 每组件独立纹理（ADR-114 perComponent）。
     * key = 组件源模型名（main/arm/arrow/minecart/boat/foxcar/trident）
     * value = 该组件声明的纹理 base64 data URI 数组（通常 1 张）
     * 3D 渲染用此字段；为空时 fallback 到 Textures[0]。
     */
    "componentTextures"?: { [_ in string]?: string[] | null } | null;

    /**
     * 组件源模型文件名（去扩展名，如 main/arm/arrow），UI 组件名用
     */
    "sourceName"?: string;

    /**
     * "1.12.0" 等
     */
    "format"?: string;
    "texWidth"?: number;
    "texHeight"?: number;
    "bones"?: Bone2D[] | null;

    /**
     * 动画 JSON 字符串数组
     */
    "animations"?: string[] | null;

    /**
     * L0/L1 派生的子模型清单（多角色包内切换用）
     */
    "subModels"?: SubModel[] | null;

    /**
     * ysm.json metadata 段（名称/许可/作者/链接，详情页用）
     */
    "metadata"?: YsmMetadata | null;

    /**
     * zip 内文件归属清单（parseGlobalResources 轻量版，只识别不解析）
     */
    "fileInventory"?: FileInventory | null;
}

/**
 * Bone2D 骨骼简化信息（只用于 2D 线条图）
 */
export interface Bone2D {
    "name": string;
    "parent"?: string;
    "pivot"?: number[];
    "rotation"?: number[];
    "cubes": Cube2D[] | null;

    /**
     * "player" / "projectile" / "vehicle"
     */
    "groupId"?: string;
}

/**
 * Cube2D 立方体信息
 */
export interface Cube2D {
    "origin": number[];
    "size": number[];
    "pivot"?: number[];
    "uv"?: number[];

    /**
     * 每面独立 UV（JSON 字符串）
     */
    "faceUV"?: string;
    "rotation"?: number[];

    /**
     * 纹理槽（从 cube.texture 解析）
     */
    "texSlot": number;

    /**
     * Blockbench 膨胀（正=外扩，负=收缩），渲染时 origin-=i、size+=2i
     */
    "inflate"?: number;

    /**
     * Blockbench 镜像（沿 X 翻转几何）
     */
    "mirror"?: boolean;
}

/**
 * CustomFileInfo custom 目录下的文件信息
 */
export interface CustomFileInfo {
    "Name": string;
    "LinkType": LinkType;
}

/**
 * FileInventory zip 内文件归属清单（对齐 Modern YSM parseGlobalResources 的分流思想，
 * 但只识别归属、不解析内容——不造双路径，前端直接消费准确清单，不再事后按文件名猜）。
 */
export interface FileInventory {
    /**
     * *.animation.json（真动画文件路径）
     */
    "animations"?: string[] | null;

    /**
     * *.animation_controller.json（动画控制器）
     */
    "controllers"?: string[] | null;

    /**
     * *.lang（本地化资源）
     */
    "langFiles"?: string[] | null;

    /**
     * *.inc（include 资源）
     */
    "incFiles"?: string[] | null;

    /**
     * 旧格式几何（main.json/arm.json/arrow.json/info.json，无 ysm.json 场景）
     */
    "legacyModels"?: string[] | null;

    /**
     * avatar/ 下的图片（作者头像，非主纹理）
     */
    "avatars"?: string[] | null;
}

/**
 * ImportFileItem 文件夹型模型整组导入的文件项（ADR-038 关联：解压目录整组导入）
 */
export interface ImportFileItem {
    /**
     * 相对文件夹根的路径（正斜杠，保留子目录层级）
     */
    "RelPath": string;

    /**
     * 文件内容
     */
    "Base64": string;
}

/**
 * ImportLog 应用操作日志（导入、扫描、下载、同步等）
 */
export interface ImportLog {
    "ModelName": string;
    "SourcePath": string;
    "TargetDir": string;
    "FileSize": number;
    "Status": string;
    "ErrorMsg"?: string;
    "Timestamp": number;

    /**
     * import / scan / download / sync / rename / delete
     */
    "Operation"?: string;

    /**
     * debug/info/warn/error/fatal
     */
    "Level"?: LogLevel;
}

/**
 * InstanceStatus 整合包状态
 */
export interface InstanceStatus {
    "Name": string;
    "CustomDir": string;

    /**
     * "complete" | "missing" | "extra"
     */
    "Status": string;

    /**
     * 已同步文件数（Files 长度，前端排序用）
     */
    "Synced": number;

    /**
     * 完整路径
     */
    "Missing": string[] | null;

    /**
     * 文件名（供展示）
     */
    "Extra": string[] | null;
    "Disabled": string[] | null;
    "HasYSM": boolean;

    /**
     * 当前资源类型对应的 mod 是否存在
     */
    "HasMod": boolean;

    /**
     * custom 目录下每个文件的链接类型
     */
    "Files": CustomFileInfo[] | null;
}

/**
 * LauncherInstance is a Minecraft instance discovered from a launcher directory.
 * GameRoot is the shared .minecraft directory; GameDir is the actual run directory
 * after applying the launcher's per-instance isolation setting.
 */
export interface LauncherInstance {
    "launcher": string;
    "name": string;
    "gameVersion": string;
    "gameRoot": string;
    "gameDir": string;
    "customDir": string;
    "exists": boolean;
}

/**
 * LinkType 链接类型
 */
export enum LinkType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LinkCopy = "copy",
    LinkHard = "hardlink",
    LinkSym = "symlink",
    LinkUnknown = "unknown",
};

/**
 * LogLevel 日志级别（诊断页按 Level 过滤；向后兼容——旧日志无此字段时前端按 Status 兜底）
 */
export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LevelDebug = "debug",
    LevelInfo = "info",
    LevelWarn = "warn",
    LevelError = "error",
    LevelFatal = "fatal",
};

/**
 * ModelEntry 模型文件条目
 */
export interface ModelEntry {
    "Name": string;
    "Size": number;
    "Path": string;
    "Ext": string;

    /**
     * SHA256
     */
    "Hash": string;

    /**
     * Unix 时间戳（毫秒）
     */
    "ModTime": number;

    /**
     * 是否有标签
     */
    "HasTags": boolean;

    /**
     * Type 资源类型 ID（如 "ysm"/"EntityPlayer"/"resourcepack"）。
     * ScanModelEntriesFiltered 按 rtype 过滤时自动填充；未指定 rtype 时为 ""。
     * 前端据此展示类型图标/标签，无需从 Path 反推类型。
     */
    "type"?: string;

    /**
     * SubDir MMD 用途子目录分组（ADR-096）：文件位于 mmdSubdirNames 命中的
     * 用途子目录内时填子目录名（如 SceneModel/CustomAnim）；根下或其他类型恒为 ""。
     * 前端据此按子目录分组展示，无需从 Path 推导。
     */
    "subdir"?: string;
}

/**
 * PackInfo 模型整合包信息（ysm-pack.json）
 */
export interface PackInfo {
    "name": string;
    "description": string;

    /**
     * ysm-pack.png 的 base64 data URI
     */
    "imageBase64"?: string;
}

/**
 * RuntimeLog 运行时日志（watcher/sync 等标准库 log 输出，诊断页可见）
 */
export interface RuntimeLog {
    "Message": string;
    "Timestamp": number;

    /**
     * 默认 info（标准库 log 无级别）
     */
    "Level"?: LogLevel;
}

/**
 * SearchResult 模型搜索结果
 */
export interface SearchResult {
    "name": string;
    "path": string;
    "boneCount": number;
    "cubeCount": number;
    "texWidth": number;
    "texHeight": number;
    "hasError": boolean;

    /**
     * 资源类型 ID（跨类型搜索时携带）
     */
    "type"?: string;
}

/**
 * SubModel 子模型条目（多角色加载）。
 * 来源优先级：L0（maid_model.json model[] 权威清单）→ L1（geoFiles 枚举兜底）。
 */
export interface SubModel {
    /**
     * 角色名（L0 直接取自 model[].name；L1 取自 geometry 文件名去后缀）
     */
    "name": string;

    /**
     * 条目的 zip 内相对路径（用于精确比对去重）
     */
    "sourcePath"?: string;

    /**
     * 默认绑定的纹理槽索引（对应 Textures 数组下标）
     */
    "texSlot"?: number;
}

/**
 * VersionInstance 整合包信息
 */
export interface VersionInstance {
    "Name": string;
    "VersionDir": string;
    "CustomDir": string;
    "Exists": boolean;
}

/**
 * WindowState 窗口位置
 */
export interface WindowState {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

/**
 * WorkshopCreator 创作者条目
 * Type 是平台标签，分号分隔，如 "bilibili;afdian"
 */
export interface WorkshopCreator {
    "name": string;
    "desc": string;
    "type"?: string;
    "role"?: string;
}

/**
 * WorkshopPresetSearch 预设搜索词
 */
export interface WorkshopPresetSearch {
    "label": string;
    "q": string;
}

/**
 * WorkshopSite 创意工坊站点配置
 */
export interface WorkshopSite {
    "id": string;
    "icon": string;
    "label": string;
    "url": string;
    "desc": string;
    "group": string;
    "searchUrl"?: string;
    "presetSearches"?: WorkshopPresetSearch[] | null;
}

/**
 * YsmAuthor 作者条目
 */
export interface YsmAuthor {
    /**
     * 作者名
     */
    "name"?: string;

    /**
     * 角色（模型原作/动画原作/材质等）
     */
    "role"?: string;

    /**
     * 作者留言
     */
    "comment"?: string;

    /**
     * 头像路径（zip 内相对路径，如 avatar/wmdj.jpg）
     */
    "avatar"?: string;

    /**
     * 联系方式（平台→URL，如 Bilibili/Afdian）
     */
    "contact"?: { [_ in string]?: string } | null;
}

/**
 * YsmLicense 许可信息（wine_fox：{"type": "CC BY-NC-SA 4.0"}）
 */
export interface YsmLicense {
    "type"?: string;
    "description"?: string;
}

/**
 * YsmMetadata ysm.json 的 metadata 段（模型详情：名称/许可/作者/链接）。
 * 字段对齐 Modern YSM RawMetadata（RawYsmModel.java L191-208）+ 真实 ysm.json 格式
 * （wine_fox：license 为 {type} 对象、authors[].contact 为平台→URL map、authors[].avatar 为路径字符串）。
 */
export interface YsmMetadata {
    /**
     * 模型名（如 "Wine Fox（酒狐）"）
     */
    "name"?: string;

    /**
     * 提示/简介（可含 \n 多行）
     */
    "tips"?: string;

    /**
     * 许可信息
     */
    "license"?: YsmLicense | null;

    /**
     * 作者列表（模型/动画/材质等角色）
     */
    "authors"?: YsmAuthor[] | null;

    /**
     * 附加链接（平台→URL）
     */
    "links"?: { [_ in string]?: string } | null;
}
