// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppConfig 应用持久化配置
 */
export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("filesRoot" in $$source)) {
            /**
             * 统一文件存储根目录，各类型默认存 {filesRoot}/{subDir}/
             * @member
             * @type {string}
             */
            this["filesRoot"] = "";
        }
        if (!("ysmRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ysmRoot"] = "";
        }
        if (!("repoRoot" in $$source)) {
            /**
             * 旧版字段，v1.6.4+ 不再使用，仅用于 config 迁移
             * @member
             * @type {string}
             */
            this["repoRoot"] = "";
        }
        if (!("resourcepackRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resourcepackRoot"] = "";
        }
        if (!("shaderpackRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shaderpackRoot"] = "";
        }
        if (!("schematicRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schematicRoot"] = "";
        }
        if (!("litematicRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["litematicRoot"] = "";
        }
        if (!("mmdRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mmdRoot"] = "";
        }
        if (!("vrcRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vrcRoot"] = "";
        }
        if (!("mcRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mcRoot"] = "";
        }
        if (!("linkMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["linkMode"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("mirror" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mirror"] = "";
        }
        if (!("voxelMaxBlocks" in $$source)) {
            /**
             * 3D 体素渲染上限，0=使用默认 200000
             * @member
             * @type {number}
             */
            this["voxelMaxBlocks"] = 0;
        }
        if (!("winX" in $$source)) {
            /**
             * 窗口状态（合并到主配置，避免 window_state.json 散落）
             * @member
             * @type {number}
             */
            this["winX"] = 0;
        }
        if (!("winY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winY"] = 0;
        }
        if (!("winW" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winW"] = 0;
        }
        if (!("winH" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winH"] = 0;
        }
        if (!("winRelX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winRelX"] = 0;
        }
        if (!("winRelY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winRelY"] = 0;
        }
        if (!("winScrW" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winScrW"] = 0;
        }
        if (!("winScrH" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winScrH"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

/**
 * AuthorInfo 作者信息（含模型计数）
 */
export class AuthorInfo {
    /**
     * Creates a new AuthorInfo instance.
     * @param {Partial<AuthorInfo>} [$$source = {}] - The source object to create the AuthorInfo.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 该作者第一个模型文件路径（用于提取头像）
             * @member
             * @type {string | undefined}
             */
            this["SampleFile"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthorInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthorInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthorInfo(/** @type {Partial<AuthorInfo>} */($$parsedSource));
    }
}

/**
 * BedrockModel 基岩版模型几何体摘要（用于 2D 预览）
 */
export class BedrockModel {
    /**
     * Creates a new BedrockModel instance.
     * @param {Partial<BedrockModel>} [$$source = {}] - The source object to create the BedrockModel.
     */
    constructor($$source = {}) {
        if (!("boneCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["boneCount"] = 0;
        }
        if (!("cubeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cubeCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 纹理图 base64 data URI（单纹理兼容）
             * @member
             * @type {string | undefined}
             */
            this["texture"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 多纹理 base64 data URI 数组
             * @member
             * @type {string[] | undefined}
             */
            this["textures"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "1.12.0" 等
             * @member
             * @type {string | undefined}
             */
            this["format"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["texWidth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["texHeight"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Bone2D[] | undefined}
             */
            this["bones"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 动画 JSON 字符串数组
             * @member
             * @type {string[] | undefined}
             */
            this["animations"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BedrockModel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BedrockModel}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("textures" in $$parsedSource) {
            $$parsedSource["textures"] = $$createField3_0($$parsedSource["textures"]);
        }
        if ("bones" in $$parsedSource) {
            $$parsedSource["bones"] = $$createField7_0($$parsedSource["bones"]);
        }
        if ("animations" in $$parsedSource) {
            $$parsedSource["animations"] = $$createField8_0($$parsedSource["animations"]);
        }
        return new BedrockModel(/** @type {Partial<BedrockModel>} */($$parsedSource));
    }
}

/**
 * Bone2D 骨骼简化信息（只用于 2D 线条图）
 */
export class Bone2D {
    /**
     * Creates a new Bone2D instance.
     * @param {Partial<Bone2D>} [$$source = {}] - The source object to create the Bone2D.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parent"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["pivot"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["rotation"] = undefined;
        }
        if (!("cubes" in $$source)) {
            /**
             * @member
             * @type {Cube2D[]}
             */
            this["cubes"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * "player" / "projectile" / "vehicle"
             * @member
             * @type {string | undefined}
             */
            this["groupId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bone2D instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Bone2D}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cubes" in $$parsedSource) {
            $$parsedSource["cubes"] = $$createField4_0($$parsedSource["cubes"]);
        }
        return new Bone2D(/** @type {Partial<Bone2D>} */($$parsedSource));
    }
}

/**
 * Cube2D 立方体信息
 */
export class Cube2D {
    /**
     * Creates a new Cube2D instance.
     * @param {Partial<Cube2D>} [$$source = {}] - The source object to create the Cube2D.
     */
    constructor($$source = {}) {
        if (!("origin" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["origin"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["size"] = Array.from({ length: 3 }, () => 0);
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["pivot"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["uv"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 每面独立 UV（JSON 字符串）
             * @member
             * @type {string | undefined}
             */
            this["faceUV"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["rotation"] = undefined;
        }
        if (!("texSlot" in $$source)) {
            /**
             * 纹理槽（从 cube.texture 解析）
             * @member
             * @type {number}
             */
            this["texSlot"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cube2D instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Cube2D}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cube2D(/** @type {Partial<Cube2D>} */($$parsedSource));
    }
}

/**
 * CustomFileInfo custom 目录下的文件信息
 */
export class CustomFileInfo {
    /**
     * Creates a new CustomFileInfo instance.
     * @param {Partial<CustomFileInfo>} [$$source = {}] - The source object to create the CustomFileInfo.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("LinkType" in $$source)) {
            /**
             * @member
             * @type {LinkType}
             */
            this["LinkType"] = LinkType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CustomFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CustomFileInfo(/** @type {Partial<CustomFileInfo>} */($$parsedSource));
    }
}

/**
 * ImportLog 导入日志
 */
export class ImportLog {
    /**
     * Creates a new ImportLog instance.
     * @param {Partial<ImportLog>} [$$source = {}] - The source object to create the ImportLog.
     */
    constructor($$source = {}) {
        if (!("ModelName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ModelName"] = "";
        }
        if (!("SourcePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SourcePath"] = "";
        }
        if (!("TargetDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TargetDir"] = "";
        }
        if (!("FileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FileSize"] = 0;
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ErrorMsg"] = undefined;
        }
        if (!("Timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportLog(/** @type {Partial<ImportLog>} */($$parsedSource));
    }
}

/**
 * InstanceStatus 整合包状态
 */
export class InstanceStatus {
    /**
     * Creates a new InstanceStatus instance.
     * @param {Partial<InstanceStatus>} [$$source = {}] - The source object to create the InstanceStatus.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("CustomDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CustomDir"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * "complete" | "missing" | "extra"
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("Synced" in $$source)) {
            /**
             * 已同步文件数（Files 长度，前端排序用）
             * @member
             * @type {number}
             */
            this["Synced"] = 0;
        }
        if (!("Missing" in $$source)) {
            /**
             * 完整路径
             * @member
             * @type {string[]}
             */
            this["Missing"] = [];
        }
        if (!("Extra" in $$source)) {
            /**
             * 文件名（供展示）
             * @member
             * @type {string[]}
             */
            this["Extra"] = [];
        }
        if (!("Disabled" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Disabled"] = [];
        }
        if (!("HasYSM" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["HasYSM"] = false;
        }
        if (!("HasMod" in $$source)) {
            /**
             * 当前资源类型对应的 mod 是否存在
             * @member
             * @type {boolean}
             */
            this["HasMod"] = false;
        }
        if (!("Files" in $$source)) {
            /**
             * custom 目录下每个文件的链接类型
             * @member
             * @type {CustomFileInfo[]}
             */
            this["Files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstanceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstanceStatus}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Missing" in $$parsedSource) {
            $$parsedSource["Missing"] = $$createField4_0($$parsedSource["Missing"]);
        }
        if ("Extra" in $$parsedSource) {
            $$parsedSource["Extra"] = $$createField5_0($$parsedSource["Extra"]);
        }
        if ("Disabled" in $$parsedSource) {
            $$parsedSource["Disabled"] = $$createField6_0($$parsedSource["Disabled"]);
        }
        if ("Files" in $$parsedSource) {
            $$parsedSource["Files"] = $$createField9_0($$parsedSource["Files"]);
        }
        return new InstanceStatus(/** @type {Partial<InstanceStatus>} */($$parsedSource));
    }
}

/**
 * LinkType 链接类型
 * @readonly
 * @enum {string}
 */
export const LinkType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LinkCopy: "copy",
    LinkHard: "hardlink",
    LinkSym: "symlink",
    LinkUnknown: "unknown",
};

/**
 * ModelEntry 模型文件条目
 */
export class ModelEntry {
    /**
     * Creates a new ModelEntry instance.
     * @param {Partial<ModelEntry>} [$$source = {}] - The source object to create the ModelEntry.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Size"] = 0;
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Ext"] = "";
        }
        if (!("Hash" in $$source)) {
            /**
             * SHA256
             * @member
             * @type {string}
             */
            this["Hash"] = "";
        }
        if (!("ModTime" in $$source)) {
            /**
             * Unix 时间戳（毫秒）
             * @member
             * @type {number}
             */
            this["ModTime"] = 0;
        }
        if (!("HasTags" in $$source)) {
            /**
             * 是否有标签
             * @member
             * @type {boolean}
             */
            this["HasTags"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelEntry(/** @type {Partial<ModelEntry>} */($$parsedSource));
    }
}

/**
 * PackInfo 模型整合包信息（ysm-pack.json）
 */
export class PackInfo {
    /**
     * Creates a new PackInfo instance.
     * @param {Partial<PackInfo>} [$$source = {}] - The source object to create the PackInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * ysm-pack.png 的 base64 data URI
             * @member
             * @type {string | undefined}
             */
            this["imageBase64"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackInfo(/** @type {Partial<PackInfo>} */($$parsedSource));
    }
}

/**
 * SearchResult 模型搜索结果
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("boneCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["boneCount"] = 0;
        }
        if (!("cubeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cubeCount"] = 0;
        }
        if (!("texWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["texWidth"] = 0;
        }
        if (!("texHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["texHeight"] = 0;
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * VersionInstance 整合包信息
 */
export class VersionInstance {
    /**
     * Creates a new VersionInstance instance.
     * @param {Partial<VersionInstance>} [$$source = {}] - The source object to create the VersionInstance.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("VersionDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["VersionDir"] = "";
        }
        if (!("CustomDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CustomDir"] = "";
        }
        if (!("Exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInstance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInstance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInstance(/** @type {Partial<VersionInstance>} */($$parsedSource));
    }
}

/**
 * WindowState 窗口位置
 */
export class WindowState {
    /**
     * Creates a new WindowState instance.
     * @param {Partial<WindowState>} [$$source = {}] - The source object to create the WindowState.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowState(/** @type {Partial<WindowState>} */($$parsedSource));
    }
}

/**
 * WorkshopCreator 创作者条目
 * Type 是平台标签，分号分隔，如 "bilibili;afdian"
 */
export class WorkshopCreator {
    /**
     * Creates a new WorkshopCreator instance.
     * @param {Partial<WorkshopCreator>} [$$source = {}] - The source object to create the WorkshopCreator.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desc"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["role"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkshopCreator instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkshopCreator}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkshopCreator(/** @type {Partial<WorkshopCreator>} */($$parsedSource));
    }
}

/**
 * WorkshopPresetSearch 预设搜索词
 */
export class WorkshopPresetSearch {
    /**
     * Creates a new WorkshopPresetSearch instance.
     * @param {Partial<WorkshopPresetSearch>} [$$source = {}] - The source object to create the WorkshopPresetSearch.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("q" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["q"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkshopPresetSearch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkshopPresetSearch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkshopPresetSearch(/** @type {Partial<WorkshopPresetSearch>} */($$parsedSource));
    }
}

/**
 * WorkshopSite 创意工坊站点配置
 */
export class WorkshopSite {
    /**
     * Creates a new WorkshopSite instance.
     * @param {Partial<WorkshopSite>} [$$source = {}] - The source object to create the WorkshopSite.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desc"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["searchUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {WorkshopPresetSearch[] | undefined}
             */
            this["presetSearches"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkshopSite instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkshopSite}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presetSearches" in $$parsedSource) {
            $$parsedSource["presetSearches"] = $$createField7_0($$parsedSource["presetSearches"]);
        }
        return new WorkshopSite(/** @type {Partial<WorkshopSite>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Bone2D.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Cube2D.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CustomFileInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = WorkshopPresetSearch.createFrom;
const $$createType8 = $Create.Array($$createType7);
