// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig 应用持久化配置
 */
export interface AppConfig {
    /**
     * 统一文件存储根目录，各类型默认存 {filesRoot}/{subDir}/
     */
    "filesRoot": string;
    "ysmRoot": string;

    /**
     * 旧版字段，v1.6.4+ 不再使用，仅用于 config 迁移
     */
    "repoRoot": string;
    "resourcepackRoot": string;
    "shaderpackRoot": string;
    "schematicRoot": string;
    "litematicRoot": string;
    "mmdRoot": string;
    "vrcRoot": string;
    "mcRoot": string;
    "linkMode": string;
    "theme": string;
    "mirror": string;

    /**
     * 3D 体素渲染上限，0=使用默认 200000
     */
    "voxelMaxBlocks": number;

    /**
     * 窗口状态（合并到主配置，避免 window_state.json 散落）
     */
    "winX": number;
    "winY": number;
    "winW": number;
    "winH": number;
    "winRelX": number;
    "winRelY": number;
    "winScrW": number;
    "winScrH": number;
}

/**
 * AuthorInfo 作者信息（含模型计数）
 */
export interface AuthorInfo {
    "Name": string;
    "Count": number;

    /**
     * 该作者第一个模型文件路径（用于提取头像）
     */
    "SampleFile"?: string;
}

/**
 * BedrockModel 基岩版模型几何体摘要（用于 2D 预览）
 */
export interface BedrockModel {
    "boneCount": number;
    "cubeCount": number;

    /**
     * 纹理图 base64 data URI（单纹理兼容）
     */
    "texture"?: string;

    /**
     * 多纹理 base64 data URI 数组
     */
    "textures"?: string[] | null;

    /**
     * 纹理文件名（去扩展名），与 Textures 同序
     */
    "textureNames"?: string[] | null;

    /**
     * 组件源模型文件名（去扩展名，如 main/arm/arrow），UI 组件名用
     */
    "sourceName"?: string;

    /**
     * "1.12.0" 等
     */
    "format"?: string;
    "texWidth"?: number;
    "texHeight"?: number;
    "bones"?: Bone2D[] | null;

    /**
     * 动画 JSON 字符串数组
     */
    "animations"?: string[] | null;
}

/**
 * Bone2D 骨骼简化信息（只用于 2D 线条图）
 */
export interface Bone2D {
    "name": string;
    "parent"?: string;
    "pivot"?: number[];
    "rotation"?: number[];
    "cubes": Cube2D[] | null;

    /**
     * "player" / "projectile" / "vehicle"
     */
    "groupId"?: string;
}

/**
 * Cube2D 立方体信息
 */
export interface Cube2D {
    "origin": number[];
    "size": number[];
    "pivot"?: number[];
    "uv"?: number[];

    /**
     * 每面独立 UV（JSON 字符串）
     */
    "faceUV"?: string;
    "rotation"?: number[];

    /**
     * 纹理槽（从 cube.texture 解析）
     */
    "texSlot": number;

    /**
     * Blockbench 膨胀（正=外扩，负=收缩），渲染时 origin-=i、size+=2i
     */
    "inflate"?: number;

    /**
     * Blockbench 镜像（沿 X 翻转几何）
     */
    "mirror"?: boolean;
}

/**
 * CustomFileInfo custom 目录下的文件信息
 */
export interface CustomFileInfo {
    "Name": string;
    "LinkType": LinkType;
}

/**
 * ImportFileItem 文件夹型模型整组导入的文件项（ADR-038 关联：解压目录整组导入）
 */
export interface ImportFileItem {
    /**
     * 相对文件夹根的路径（正斜杠，保留子目录层级）
     */
    "RelPath": string;

    /**
     * 文件内容
     */
    "Base64": string;
}

/**
 * ImportLog 应用操作日志（导入、扫描、下载、同步等）
 */
export interface ImportLog {
    "ModelName": string;
    "SourcePath": string;
    "TargetDir": string;
    "FileSize": number;
    "Status": string;
    "ErrorMsg"?: string;
    "Timestamp": number;

    /**
     * import / scan / download / sync / rename / delete
     */
    "Operation"?: string;
}

/**
 * InstanceStatus 整合包状态
 */
export interface InstanceStatus {
    "Name": string;
    "CustomDir": string;

    /**
     * "complete" | "missing" | "extra"
     */
    "Status": string;

    /**
     * 已同步文件数（Files 长度，前端排序用）
     */
    "Synced": number;

    /**
     * 完整路径
     */
    "Missing": string[] | null;

    /**
     * 文件名（供展示）
     */
    "Extra": string[] | null;
    "Disabled": string[] | null;
    "HasYSM": boolean;

    /**
     * 当前资源类型对应的 mod 是否存在
     */
    "HasMod": boolean;

    /**
     * custom 目录下每个文件的链接类型
     */
    "Files": CustomFileInfo[] | null;
}

/**
 * LinkType 链接类型
 */
export enum LinkType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LinkCopy = "copy",
    LinkHard = "hardlink",
    LinkSym = "symlink",
    LinkUnknown = "unknown",
};

/**
 * ModelEntry 模型文件条目
 */
export interface ModelEntry {
    "Name": string;
    "Size": number;
    "Path": string;
    "Ext": string;

    /**
     * SHA256
     */
    "Hash": string;

    /**
     * Unix 时间戳（毫秒）
     */
    "ModTime": number;

    /**
     * 是否有标签
     */
    "HasTags": boolean;
}

/**
 * PackInfo 模型整合包信息（ysm-pack.json）
 */
export interface PackInfo {
    "name": string;
    "description": string;

    /**
     * ysm-pack.png 的 base64 data URI
     */
    "imageBase64"?: string;
}

/**
 * RuntimeLog 运行时日志（watcher/sync 等标准库 log 输出，诊断页可见）
 */
export interface RuntimeLog {
    "Message": string;
    "Timestamp": number;
}

/**
 * SearchResult 模型搜索结果
 */
export interface SearchResult {
    "name": string;
    "path": string;
    "boneCount": number;
    "cubeCount": number;
    "texWidth": number;
    "texHeight": number;
    "hasError": boolean;
}

/**
 * VersionInstance 整合包信息
 */
export interface VersionInstance {
    "Name": string;
    "VersionDir": string;
    "CustomDir": string;
    "Exists": boolean;
}

/**
 * WindowState 窗口位置
 */
export interface WindowState {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

/**
 * WorkshopCreator 创作者条目
 * Type 是平台标签，分号分隔，如 "bilibili;afdian"
 */
export interface WorkshopCreator {
    "name": string;
    "desc": string;
    "type"?: string;
    "role"?: string;
}

/**
 * WorkshopPresetSearch 预设搜索词
 */
export interface WorkshopPresetSearch {
    "label": string;
    "q": string;
}

/**
 * WorkshopSite 创意工坊站点配置
 */
export interface WorkshopSite {
    "id": string;
    "icon": string;
    "label": string;
    "url": string;
    "desc": string;
    "group": string;
    "searchUrl"?: string;
    "presetSearches"?: WorkshopPresetSearch[] | null;
}
