// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AnimGroup {
    "id": string;
    "name": string;
    "items": string[] | null;
}

export interface Author {
    "name": string;
    "roles"?: string;
    "bilibili"?: string;
}

export interface ConfigMenu {
    "id": string;
    "name": string;
    "controls": string[] | null;
}

export interface Link {
    "home"?: string;
    "donate"?: string;
}

export interface PreviewInfo {
    "defaultTexture"?: string;
    "hasGui": boolean;
    "heightScale"?: number;
    "widthScale"?: number;
}

export interface Stats {
    "textures": number;
    "models": number;
    "animations": number;
    "texWidth": number;
    "texHeight": number;
}

/**
 * TexInfo 轻量级纹理尺寸（不解析完整模型）
 */
export interface TexInfo {
    "path": string;
    "texWidth": number;
    "texHeight": number;
}

/**
 * YSMHeader 从 YSM 文件文本头部提取的元数据（适用于加密和非加密模型）
 */
export interface YSMHeader {
    /**
     * 文件类型
     */
    "isYsm": boolean;

    /**
     * <free> true/false
     */
    "isFree": boolean;

    /**
     * <free> 标签是否存在
     */
    "hasFree": boolean;
    "hash"?: string;

    /**
     * 基本信息
     */
    "name": string;
    "license"?: string;

    /**
     * 作者信息
     */
    "authorName"?: string;
    "authorRole"?: string;
    "authorBilibili"?: string;
    "authorAfdian"?: string;

    /**
     * 链接
     */
    "linkHome"?: string;
    "linkUpdate"?: string;

    /**
     * 编码版本
     */
    "format"?: number;
    "crypto"?: number;

    /**
     * 导出信息
     */
    "tips"?: string;
}

/**
 * YSMModelMeta 模型元数据（从 model.json 提取）
 */
export interface YSMModelMeta {
    "name": string;
    "author": string;
    "version": string;
    "bones": number;
    "textures": number;
    "animations": number;
    "vertices": number;
    "faces": number;
    "hasError": boolean;
    "errorMsg"?: string;
}

/**
 * YsmSummary 是前端右侧面板和 AI 搜索消费的标准摘要
 */
export interface YsmSummary {
    /**
     * "ysm-summary/v1"
     */
    "schema": string;

    /**
     * 原始文件名
     */
    "source": string;
    "name": string;
    "tips"?: string;
    "license"?: string;
    "authors"?: Author[] | null;
    "links"?: Link;
    "spec": number;

    /**
     * "ysm" 或 "zip"
     */
    "format": string;

    /**
     * 文件大小 bytes
     */
    "size": number;
    "stats": Stats;
    "animGroups"?: AnimGroup[] | null;
    "configMenus"?: ConfigMenu[] | null;
    "preview": PreviewInfo;
}
