// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AnimGroup {
    /**
     * Creates a new AnimGroup instance.
     * @param {Partial<AnimGroup>} [$$source = {}] - The source object to create the AnimGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnimGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnimGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField2_0($$parsedSource["items"]);
        }
        return new AnimGroup(/** @type {Partial<AnimGroup>} */($$parsedSource));
    }
}

export class Author {
    /**
     * Creates a new Author instance.
     * @param {Partial<Author>} [$$source = {}] - The source object to create the Author.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["roles"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bilibili"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Author instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Author}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Author(/** @type {Partial<Author>} */($$parsedSource));
    }
}

export class ConfigMenu {
    /**
     * Creates a new ConfigMenu instance.
     * @param {Partial<ConfigMenu>} [$$source = {}] - The source object to create the ConfigMenu.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("controls" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["controls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigMenu instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigMenu}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("controls" in $$parsedSource) {
            $$parsedSource["controls"] = $$createField2_0($$parsedSource["controls"]);
        }
        return new ConfigMenu(/** @type {Partial<ConfigMenu>} */($$parsedSource));
    }
}

export class Link {
    /**
     * Creates a new Link instance.
     * @param {Partial<Link>} [$$source = {}] - The source object to create the Link.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["home"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["donate"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Link instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Link}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Link(/** @type {Partial<Link>} */($$parsedSource));
    }
}

export class PreviewInfo {
    /**
     * Creates a new PreviewInfo instance.
     * @param {Partial<PreviewInfo>} [$$source = {}] - The source object to create the PreviewInfo.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["defaultTexture"] = undefined;
        }
        if (!("hasGui" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasGui"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["heightScale"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["widthScale"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewInfo(/** @type {Partial<PreviewInfo>} */($$parsedSource));
    }
}

export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("textures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["textures"] = 0;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["models"] = 0;
        }
        if (!("animations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["animations"] = 0;
        }
        if (!("texWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["texWidth"] = 0;
        }
        if (!("texHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["texHeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

/**
 * TexInfo 轻量级纹理尺寸（不解析完整模型）
 */
export class TexInfo {
    /**
     * Creates a new TexInfo instance.
     * @param {Partial<TexInfo>} [$$source = {}] - The source object to create the TexInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("texWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["texWidth"] = 0;
        }
        if (!("texHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["texHeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TexInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TexInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TexInfo(/** @type {Partial<TexInfo>} */($$parsedSource));
    }
}

/**
 * YSMHeader 从 YSM 文件文本头部提取的元数据（适用于加密和非加密模型）
 */
export class YSMHeader {
    /**
     * Creates a new YSMHeader instance.
     * @param {Partial<YSMHeader>} [$$source = {}] - The source object to create the YSMHeader.
     */
    constructor($$source = {}) {
        if (!("isYsm" in $$source)) {
            /**
             * 文件类型
             * @member
             * @type {boolean}
             */
            this["isYsm"] = false;
        }
        if (!("isFree" in $$source)) {
            /**
             * <free> true/false
             * @member
             * @type {boolean}
             */
            this["isFree"] = false;
        }
        if (!("hasFree" in $$source)) {
            /**
             * <free> 标签是否存在
             * @member
             * @type {boolean}
             */
            this["hasFree"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hash"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * 基本信息
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["license"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 作者信息
             * @member
             * @type {string | undefined}
             */
            this["authorName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["authorRole"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["authorBilibili"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["authorAfdian"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 链接
             * @member
             * @type {string | undefined}
             */
            this["linkHome"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["linkUpdate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 编码版本
             * @member
             * @type {number | undefined}
             */
            this["format"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["crypto"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 导出信息
             * @member
             * @type {string | undefined}
             */
            this["tips"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new YSMHeader instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {YSMHeader}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new YSMHeader(/** @type {Partial<YSMHeader>} */($$parsedSource));
    }
}

/**
 * YSMModelMeta 模型元数据（从 model.json 提取）
 */
export class YSMModelMeta {
    /**
     * Creates a new YSMModelMeta instance.
     * @param {Partial<YSMModelMeta>} [$$source = {}] - The source object to create the YSMModelMeta.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("bones" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bones"] = 0;
        }
        if (!("textures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["textures"] = 0;
        }
        if (!("animations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["animations"] = 0;
        }
        if (!("vertices" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vertices"] = 0;
        }
        if (!("faces" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["faces"] = 0;
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMsg"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new YSMModelMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {YSMModelMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new YSMModelMeta(/** @type {Partial<YSMModelMeta>} */($$parsedSource));
    }
}

/**
 * YsmSummary 是前端右侧面板和 AI 搜索消费的标准摘要
 */
export class YsmSummary {
    /**
     * Creates a new YsmSummary instance.
     * @param {Partial<YsmSummary>} [$$source = {}] - The source object to create the YsmSummary.
     */
    constructor($$source = {}) {
        if (!("schema" in $$source)) {
            /**
             * "ysm-summary/v1"
             * @member
             * @type {string}
             */
            this["schema"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * 原始文件名
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tips"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["license"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Author[] | undefined}
             */
            this["authors"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Link | undefined}
             */
            this["links"] = undefined;
        }
        if (!("spec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["spec"] = 0;
        }
        if (!("format" in $$source)) {
            /**
             * "ysm" 或 "zip"
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * 文件大小 bytes
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {Stats}
             */
            this["stats"] = (new Stats());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AnimGroup[] | undefined}
             */
            this["animGroups"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ConfigMenu[] | undefined}
             */
            this["configMenus"] = undefined;
        }
        if (!("preview" in $$source)) {
            /**
             * @member
             * @type {PreviewInfo}
             */
            this["preview"] = (new PreviewInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new YsmSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {YsmSummary}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        const $$createField10_0 = $$createType4;
        const $$createField11_0 = $$createType6;
        const $$createField12_0 = $$createType8;
        const $$createField13_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("authors" in $$parsedSource) {
            $$parsedSource["authors"] = $$createField5_0($$parsedSource["authors"]);
        }
        if ("links" in $$parsedSource) {
            $$parsedSource["links"] = $$createField6_0($$parsedSource["links"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField10_0($$parsedSource["stats"]);
        }
        if ("animGroups" in $$parsedSource) {
            $$parsedSource["animGroups"] = $$createField11_0($$parsedSource["animGroups"]);
        }
        if ("configMenus" in $$parsedSource) {
            $$parsedSource["configMenus"] = $$createField12_0($$parsedSource["configMenus"]);
        }
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField13_0($$parsedSource["preview"]);
        }
        return new YsmSummary(/** @type {Partial<YsmSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Author.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Link.createFrom;
const $$createType4 = Stats.createFrom;
const $$createType5 = AnimGroup.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ConfigMenu.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = PreviewInfo.createFrom;
