// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BoneData {
    "id": string;
    "name": string;
    "parentId": string | null;
    "localPosition": number[];

    /**
     * quaternion [x,y,z,w]
     */
    "localRotation": number[];

    /**
     * 发光骨骼（名前缀 "ysmGlow"），前端设 emissive
     */
    "glow": boolean;

    /**
     * 该骨骼挂载的立方体数（前端统计用，underscore 字段）
     */
    "_cubeCount": number;
}

export interface MeshData {
    "id": string;
    "boneId": string;
    "localPosition": number[];

    /**
     * quaternion [x,y,z,w]
     */
    "localRotation": number[];
    "positions": number[] | null;
    "normals": number[] | null;
    "uvs": number[] | null;
    "indices": number[] | null;

    /**
     * 纹理槽索引
     */
    "texIdx": number;
}

export interface Model3DSpec {
    "models": ModelGroup[] | null;
}

export interface ModelGroup {
    "id": string;
    "name": string;
    "defaultVisible": boolean;
    "textureWidth": number;
    "textureHeight": number;
    "textureId": string | null;
    "bones": BoneData[] | null;
    "meshGroups": MeshData[] | null;
}
