// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BoneData {
    "id": string;
    "name": string;
    "parentId": string | null;
    "localPosition": number[];

    /**
     * quaternion [x,y,z,w]
     */
    "localRotation": number[];

    /**
     * 发光骨骼（名前缀 "ysmGlow"），前端设 emissive
     */
    "glow": boolean;

    /**
     * 该骨骼挂载的立方体数（前端统计用，underscore 字段）
     */
    "_cubeCount": number;
}

export interface MeshData {
    "id": string;
    "boneId": string;
    "localPosition": number[];

    /**
     * quaternion [x,y,z,w]
     */
    "localRotation": number[];
    "positions": number[] | null;
    "normals": number[] | null;
    "uvs": number[] | null;
    "indices": number[] | null;

    /**
     * 纹理槽索引
     */
    "texIdx": number;
}

export interface Model3DSpec {
    "models": ModelGroup[] | null;

    /**
     * TexArrOrder 组件序纹理名数组（R1 契约，GetModel3DSpec 注入）。
     * 必须在此声明：typed 返回链（json.Unmarshal → Wails 序列化）会丢弃
     * 结构体外字段——缺失曾致 perComponent 纹理/契约校验在前端静默失效（回归 936169b1）。
     */
    "texArrOrder"?: string[] | null;

    /**
     * ComponentTextures 组件名 → 声明纹理 base64 数组（ADR-114 perComponent，
     * zip/7z/解压目录三路同源注入）。同上，缺失即前端纹理绑定回落全局槽错贴。
     */
    "componentTextures"?: { [_ in string]?: string[] | null } | null;
}

export interface ModelGroup {
    "id": string;
    "name": string;
    "defaultVisible": boolean;
    "textureWidth": number;
    "textureHeight": number;
    "textureId": string | null;
    "bones": BoneData[] | null;
    "meshGroups": MeshData[] | null;
}
