// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileEntry 文件条目
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "size": number;
    "modTime": number;
}

/**
 * Group 重复文件分组
 */
export interface Group {
    /**
     * 算法生成的唯一标识
     */
    "hash": string;

    /**
     * 单文件大小
     */
    "size": number;

    /**
     * 文件列表
     */
    "files": FileEntry[] | null;
}
