[package]
name = "ysm-model-manager-wails-bridge"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ysm-model-manager-core = { path = "../rust-core" }
rust-test-utils = { path = "../rust-test-utils" }
