// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../go/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../go/updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ysm$0 from "../../go/ysm/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ========== 日志 ==========
 * @param {string} modelName
 * @param {string} sourcePath
 * @param {string} targetDir
 * @param {number} fileSize
 * @param {string} status
 * @param {string} errMsg
 * @returns {$CancellablePromise<void>}
 */
export function AddImportLog(modelName, sourcePath, targetDir, fileSize, status, errMsg) {
    return $Call.ByID(3744622591, modelName, sourcePath, targetDir, fileSize, status, errMsg);
}

/**
 * AllTags 返回所有被使用的标签（按使用次数降序）
 * @returns {$CancellablePromise<string[]>}
 */
export function AllTags() {
    return $Call.ByID(1246240395).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} modelPath
 * @returns {$CancellablePromise<types$0.BedrockModel>}
 */
export function AnalyzeBedrockModel(modelPath) {
    return $Call.ByID(2221616526, modelPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<ysm$0.YSMModelMeta>}
 */
export function AnalyzeYSMModel(path) {
    return $Call.ByID(87919393, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} zipPath
 * @returns {$CancellablePromise<void>}
 */
export function ApplyUpdate(zipPath) {
    return $Call.ByID(3688265704, zipPath);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function BackupWorkshopCreators() {
    return $Call.ByID(3964989829);
}

/**
 * BatchExtractCreatorAvatars 批量提取所有有本地模型的创作者头像
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function BatchExtractCreatorAvatars() {
    return $Call.ByID(2317353684).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CacheModelAvatars 从解压目录 ysm.json 缓存头像
 * @param {string} modelPath
 * @returns {$CancellablePromise<void>}
 */
export function CacheModelAvatars(modelPath) {
    return $Call.ByID(3423756102, modelPath);
}

/**
 * CachedCreatorAvatar 检查缓存中是否有作者头像，返回 data URI
 * @param {string} authorName
 * @returns {$CancellablePromise<string>}
 */
export function CachedCreatorAvatar(authorName) {
    return $Call.ByID(224206566, authorName);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelQueue() {
    return $Call.ByID(1786226156);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckFileExists(path) {
    return $Call.ByID(467508719, path);
}

/**
 * @returns {$CancellablePromise<updater$0.UpdateInfo | null>}
 */
export function CheckUpdate() {
    return $Call.ByID(651964520).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} customDir
 * @returns {$CancellablePromise<number>}
 */
export function ClearCustomDir(customDir) {
    return $Call.ByID(2697468754, customDir);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearImportLogs() {
    return $Call.ByID(3815103174);
}

/**
 * ClearInstanceResources 清空指定整合包中已同步的文件（走回收站）
 * insName: 整合包名, rtype: 资源类型（空=全部, 非空=只清此类型）
 * 返回清除的文件数量
 * @param {string} insName
 * @param {string} rtype
 * @returns {$CancellablePromise<number>}
 */
export function ClearInstanceResources(insName, rtype) {
    return $Call.ByID(310409492, insName, rtype);
}

/**
 * ClearScanCache 清除扫描缓存（下载/导入后调用）
 * @returns {$CancellablePromise<void>}
 */
export function ClearScanCache() {
    return $Call.ByID(3066626705);
}

/**
 * ========== 模型复制 ==========
 * CopyModelFile 将 src 复制到 dstDir 目录下（保留原文件名）
 * dstDir 必须是 FilesRoot 的子目录（防路径遍历）
 * @param {string} src
 * @param {string} dstDir
 * @returns {$CancellablePromise<void>}
 */
export function CopyModelFile(src, dstDir) {
    return $Call.ByID(2849400957, src, dstDir);
}

/**
 * CountDuplicateFiles 快速统计重复文件数量
 * @param {string} dir
 * @returns {$CancellablePromise<string>}
 */
export function CountDuplicateFiles(dir) {
    return $Call.ByID(2412651574, dir);
}

/**
 * CountInstanceResources 统计指定整合包中可清空的资源文件数
 * 只统计仓库中已有的文件（同 clearInstanceDir 逻辑）
 * rtype 为空时统计全部类型，否则只统计指定类型
 * @param {string} insName
 * @param {string} rtype
 * @returns {$CancellablePromise<number>}
 */
export function CountInstanceResources(insName, rtype) {
    return $Call.ByID(136508414, insName, rtype);
}

/**
 * ========== 目录操作 ==========
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function CreateDir(dir) {
    return $Call.ByID(14567662, dir);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function CurrentVersion() {
    return $Call.ByID(2861439428);
}

/**
 * DebugExtractCreatorAvatar 调试版：提取指定作者头像
 * @param {string} authorName
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function DebugExtractCreatorAvatar(authorName) {
    return $Call.ByID(1802835376, authorName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} customDir
 * @returns {$CancellablePromise<[number, number]>}
 */
export function DeduplicateCustomDir(customDir) {
    return $Call.ByID(2166378965, customDir);
}

/**
 * @param {string} src
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFromRecycle(src) {
    return $Call.ByID(2594824985, src);
}

/**
 * DeleteModelDir 删除文件夹型资源（MMD 模型等），删除文件所在父文件夹
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteModelDir(path) {
    return $Call.ByID(2959912528, path);
}

/**
 * DeleteResourcePack 删除资源包文件
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteResourcePack(path) {
    return $Call.ByID(395621705, path);
}

/**
 * DetectResourceType 检测指定文件的资源类型
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function DetectResourceType(path) {
    return $Call.ByID(2113518140, path);
}

/**
 * DetectZipType 通过 ZIP 内容检测资源类型（供前端导入路由使用）
 * @param {string} base64Data
 * @returns {$CancellablePromise<string>}
 */
export function DetectZipType(base64Data) {
    return $Call.ByID(747133431, base64Data);
}

/**
 * @param {string} url
 * @param {string} expectedHash
 * @returns {$CancellablePromise<string>}
 */
export function DoUpdate(url, expectedHash) {
    return $Call.ByID(985752667, url, expectedHash);
}

/**
 * @param {string} rawURL
 * @param {string} saveDir
 * @returns {$CancellablePromise<string>}
 */
export function DownloadFromGitHub(rawURL, saveDir) {
    return $Call.ByID(960385788, rawURL, saveDir);
}

/**
 * @param {string} url
 * @param {string} expectedHash
 * @returns {$CancellablePromise<string>}
 */
export function DownloadUpdate(url, expectedHash) {
    return $Call.ByID(2886098546, url, expectedHash);
}

/**
 * @param {string} $0
 * @returns {$CancellablePromise<number>}
 */
export function EmptyRecycleBin($0) {
    return $Call.ByID(4211256250, $0);
}

/**
 * @param {$models.DownloadTask[]} tasks
 * @returns {$CancellablePromise<void>}
 */
export function EnqueueDownloads(tasks) {
    return $Call.ByID(552244624, tasks);
}

/**
 * ========== 批量导出骨骼结构 ==========
 * @param {string} repoRoot
 * @returns {$CancellablePromise<string>}
 */
export function ExportBoneStructures(repoRoot) {
    return $Call.ByID(2854573701, repoRoot);
}

/**
 * ExportModelStructureJSON 导出单模型骨骼结构
 * @param {string} modelPath
 * @returns {$CancellablePromise<string>}
 */
export function ExportModelStructureJSON(modelPath) {
    return $Call.ByID(2285469521, modelPath);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportWorkshopCreatorsJSONFile() {
    return $Call.ByID(3313564853);
}

/**
 * ========== CSV 导出/导入 ==========
 * @returns {$CancellablePromise<string>}
 */
export function ExportWorkshopSitesCSV() {
    return $Call.ByID(2284407588);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportWorkshopSitesJSONFile() {
    return $Call.ByID(3241109304);
}

/**
 * @param {string} modelPath
 * @returns {$CancellablePromise<string>}
 */
export function ExtractPreviewTexture(modelPath) {
    return $Call.ByID(4136663739, modelPath);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<ysm$0.YSMHeader>}
 */
export function ExtractYSMHeader(path) {
    return $Call.ByID(3464271858, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} base64Data
 * @returns {$CancellablePromise<ysm$0.YSMHeader>}
 */
export function ExtractYSMHeaderFromBase64(base64Data) {
    return $Call.ByID(547420281, base64Data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<ysm$0.YsmSummary>}
 */
export function ExtractYsmSummary(path) {
    return $Call.ByID(847066301, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * FindDuplicateFiles 扫描目录返回所有重复文件分组（JSON 字符串）
 * @param {string} dir
 * @returns {$CancellablePromise<string>}
 */
export function FindDuplicateFiles(dir) {
    return $Call.ByID(1295941240, dir);
}

/**
 * ========== 预览提取 ==========
 * @param {string} modelPath
 * @returns {$CancellablePromise<string>}
 */
export function FindPreviewImage(modelPath) {
    return $Call.ByID(528549045, modelPath);
}

/**
 * GenerateRepoIndex 扫描仓库目录，生成 index.json
 * @param {string} repoPath
 * @returns {$CancellablePromise<string>}
 */
export function GenerateRepoIndex(repoPath) {
    return $Call.ByID(1563740856, repoPath);
}

/**
 * GetAppVersion 返回当前版本号
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(115297084);
}

/**
 * @param {string} mcRoot
 * @returns {$CancellablePromise<string>}
 */
export function GetGlobalCustomDir(mcRoot) {
    return $Call.ByID(4119708496, mcRoot);
}

/**
 * @returns {$CancellablePromise<types$0.ImportLog[]>}
 */
export function GetImportLogs() {
    return $Call.ByID(1065567147).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ========== 状态同步 ==========
 * @param {string} mcRoot
 * @param {string} repoDir
 * @returns {$CancellablePromise<types$0.InstanceStatus[]>}
 */
export function GetInstanceStatus(mcRoot, repoDir) {
    return $Call.ByID(4224028016, mcRoot, repoDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetInstanceSyncStatus 获取整合包下所有资源类型的同步状态（扁平列表）
 * @param {string} instanceName
 * @returns {$CancellablePromise<string>}
 */
export function GetInstanceSyncStatus(instanceName) {
    return $Call.ByID(839308247, instanceName);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLinkMode() {
    return $Call.ByID(736604018);
}

/**
 * GetLitematicVoxelData 读取投影文件体素数据（按颜色分组的方块位置）
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetLitematicVoxelData(path) {
    return $Call.ByID(2172897631, path);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetMinecraftPaths() {
    return $Call.ByID(2122198272).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} modelPath
 * @returns {$CancellablePromise<string>}
 */
export function GetModel3DSpec(modelPath) {
    return $Call.ByID(2923299250, modelPath);
}

/**
 * GetModelTags 返回指定模型文件的所有标签
 * @param {string} modelPath
 * @returns {$CancellablePromise<string[]>}
 */
export function GetModelTags(modelPath) {
    return $Call.ByID(234236959, modelPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetModelTexSizes 扫描仓库文件提取纹理尺寸（轻量级，不解析完整模型）
 * @param {string} repoRoot
 * @returns {$CancellablePromise<ysm$0.TexInfo[]>}
 */
export function GetModelTexSizes(repoRoot) {
    return $Call.ByID(1273620259, repoRoot).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetNbtVoxelData 读取 .nbt 结构文件体素数据
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetNbtVoxelData(path) {
    return $Call.ByID(2164005593, path);
}

/**
 * ========== 包信息 ==========
 * @param {string} dirPath
 * @returns {$CancellablePromise<types$0.PackInfo>}
 */
export function GetPackInfo(dirPath) {
    return $Call.ByID(2243407216, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetRepoRoot 根据资源类型返回对应的仓库根目录
 * @param {string} rtype
 * @returns {$CancellablePromise<string>}
 */
export function GetRepoRoot(rtype) {
    return $Call.ByID(4011191521, rtype);
}

/**
 * GetResourceInstanceStatus 按资源类型获取整合包同步状态
 * repoDir 仅对 YSM 类型生效（其他类型从全局资源目录推导）
 * @param {string} rtype
 * @param {string} mcRoot
 * @param {string} repoDir
 * @returns {$CancellablePromise<types$0.InstanceStatus[]>}
 */
export function GetResourceInstanceStatus(rtype, mcRoot, repoDir) {
    return $Call.ByID(779607888, rtype, mcRoot, repoDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetSchematicVoxelData 读取 .schematic 文件体素数据
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetSchematicVoxelData(path) {
    return $Call.ByID(199377974, path);
}

/**
 * ========== 自动更新 ==========
 * GetSubDirMap 返回资源类型→子目录映射表（前端右键菜单等场景使用）
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetSubDirMap() {
    return $Call.ByID(2085433910).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetWasmBinary 返回内嵌的 YSMParser.wasm 字节（供前端 WebView2 使用）。
 * wasmBinary 由根包 main 的 init() 经 SetEmbedded 注入。
 * @returns {$CancellablePromise<string>}
 */
export function GetWasmBinary() {
    return $Call.ByID(2670724632).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @returns {$CancellablePromise<types$0.WindowState>}
 */
export function GetWindowPosition() {
    return $Call.ByID(3862857718).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ========== YSM 检测 ==========
 * @param {string} modsDir
 * @returns {$CancellablePromise<boolean>}
 */
export function HasYSMMod(modsDir) {
    return $Call.ByID(1327539980, modsDir);
}

/**
 * ImportByType 统一导入入口——根据资源类型自动选择导入策略
 * @param {string} rtype
 * @param {string} srcPath
 * @returns {$CancellablePromise<string>}
 */
export function ImportByType(rtype, srcPath) {
    return $Call.ByID(1466768695, rtype, srcPath);
}

/**
 * @param {string} fileName
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function ImportModelFile(fileName, base64Data) {
    return $Call.ByID(2135926573, fileName, base64Data);
}

/**
 * @param {string} fileName
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function ImportModelFileOverwrite(fileName, base64Data) {
    return $Call.ByID(2920266218, fileName, base64Data);
}

/**
 * @param {string} fileName
 * @param {string} subpath
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function ImportModelFileOverwriteTo(fileName, subpath, base64Data) {
    return $Call.ByID(3849603631, fileName, subpath, base64Data);
}

/**
 * @param {string} fileName
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function ImportModelFileSkipCheck(fileName, base64Data) {
    return $Call.ByID(334185050, fileName, base64Data);
}

/**
 * @param {string} fileName
 * @param {string} subpath
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function ImportModelFileTo(fileName, subpath, base64Data) {
    return $Call.ByID(191674492, fileName, subpath, base64Data);
}

/**
 * ImportResourcePack 使用策略模式导入资源包
 * @param {string} srcPath
 * @param {string} rtype
 * @returns {$CancellablePromise<string>}
 */
export function ImportResourcePack(srcPath, rtype) {
    return $Call.ByID(2578913479, srcPath, rtype);
}

/**
 * @param {string} csvContent
 * @returns {$CancellablePromise<void>}
 */
export function ImportWorkshopSitesCSV(csvContent) {
    return $Call.ByID(1342547047, csvContent);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function ImportWorkshopSitesJSONFile() {
    return $Call.ByID(1933238405);
}

/**
 * ========== 安装 ==========
 * @param {string} src
 * @param {string} mcRoot
 * @returns {$CancellablePromise<string>}
 */
export function InstallModelFile(src, mcRoot) {
    return $Call.ByID(2558470757, src, mcRoot);
}

/**
 * @param {string} src
 * @param {string} customDir
 * @returns {$CancellablePromise<void>}
 */
export function InstallModelTo(src, customDir) {
    return $Call.ByID(547256422, src, customDir);
}

/**
 * @param {string} src
 * @param {string} customDir
 * @returns {$CancellablePromise<string>}
 */
export function InstallModelWithOverlay(src, customDir) {
    return $Call.ByID(4168467473, src, customDir);
}

/**
 * InstallResourceToInstance 将资源文件安装到指定整合包
 * rtype: 资源类型（resourcepack/shaderpack 等），srcPath: 源文件路径，instanceName: 整合包名称
 * @param {string} rtype
 * @param {string} srcPath
 * @param {string} instanceName
 * @returns {$CancellablePromise<void>}
 */
export function InstallResourceToInstance(rtype, srcPath, instanceName) {
    return $Call.ByID(215553224, rtype, srcPath, instanceName);
}

/**
 * InvalidateScanCache 清空扫描缓存，下次扫描获取最新数据
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateScanCache() {
    return $Call.ByID(2605564787);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFileBanned(path) {
    return $Call.ByID(3330292233, path);
}

/**
 * IsProxyRunning 检查代理是否运行中
 * @returns {$CancellablePromise<boolean>}
 */
export function IsProxyRunning() {
    return $Call.ByID(3002035324);
}

/**
 * IsResourcePackEnabled 检查资源包是否启用
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function IsResourcePackEnabled(path) {
    return $Call.ByID(2413288079, path);
}

/**
 * ListAllFilePaths 递归列出指定目录下的所有文件完整路径（不限制扩展名）
 * @param {string} dir
 * @returns {$CancellablePromise<string[]>}
 */
export function ListAllFilePaths(dir) {
    return $Call.ByID(504456952, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListByTag 返回所有打了指定标签的文件路径列表
 * @param {string} tag
 * @returns {$CancellablePromise<string[]>}
 */
export function ListByTag(tag) {
    return $Call.ByID(543634162, tag).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<string[]>}
 */
export function ListFileNames(dir) {
    return $Call.ByID(223101035, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<types$0.AuthorInfo[]>}
 */
export function ListModelAuthors() {
    return $Call.ByID(2783678748).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} $0
 * @returns {$CancellablePromise<types$0.ModelEntry[]>}
 */
export function ListRecycleBin($0) {
    return $Call.ByID(3420025601, $0).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @param {string} mcRoot
 * @returns {$CancellablePromise<types$0.VersionInstance[]>}
 */
export function ListVersionInstances(mcRoot) {
    return $Call.ByID(2348617735, mcRoot).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @returns {$CancellablePromise<types$0.AppConfig>}
 */
export function LoadAppConfig() {
    return $Call.ByID(4081731812).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @returns {$CancellablePromise<types$0.WorkshopCreator[]>}
 */
export function LoadGitHubRepos() {
    return $Call.ByID(555735249).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * LoadResourceTypes 加载资源类型注册表
 * @returns {$CancellablePromise<string>}
 */
export function LoadResourceTypes() {
    return $Call.ByID(3636552016);
}

/**
 * @returns {$CancellablePromise<types$0.WorkshopCreator[]>}
 */
export function LoadWorkshopCreators() {
    return $Call.ByID(3429491443).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @returns {$CancellablePromise<types$0.WorkshopSite[]>}
 */
export function LoadWorkshopSites() {
    return $Call.ByID(1402443890).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @param {string} jsonContent
 * @returns {$CancellablePromise<[number, number]>}
 */
export function MergeWorkshopCreatorsFromJSON(jsonContent) {
    return $Call.ByID(2866539347, jsonContent);
}

/**
 * ========== 模型移动 ==========
 * @param {string} src
 * @param {string} dstDir
 * @returns {$CancellablePromise<void>}
 */
export function MoveModelFile(src, dstDir) {
    return $Call.ByID(1018628389, src, dstDir);
}

/**
 * ========== 回收站 ==========
 * @param {string} src
 * @returns {$CancellablePromise<void>}
 */
export function MoveToRecycle(src) {
    return $Call.ByID(1383304780, src);
}

/**
 * @param {string} src
 * @returns {$CancellablePromise<[string, string]>}
 */
export function MoveToRecycleEx(src) {
    return $Call.ByID(2099759785, src);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolder(dir) {
    return $Call.ByID(4260431887, dir);
}

/**
 * OpenInBrowser 在系统默认浏览器中打开链接（而非 WebView2 内嵌）
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenInBrowser(url) {
    return $Call.ByID(3205913216, url);
}

/**
 * OpenInstanceFolder 按资源类型打开整合包子目录；目录不存在时回退到实例根目录
 * @param {string} instDir
 * @param {string} rtype
 * @returns {$CancellablePromise<void>}
 */
export function OpenInstanceFolder(instDir, rtype) {
    return $Call.ByID(2384592956, instDir, rtype);
}

/**
 * PullResourceFromInstance 将整合包中多余的资源拉取到全局
 * @param {string} rtype
 * @param {string} instanceName
 * @returns {$CancellablePromise<number>}
 */
export function PullResourceFromInstance(rtype, instanceName) {
    return $Call.ByID(3336031775, rtype, instanceName);
}

/**
 * PullSingleResourceFromInstance 从整合包拉取单个 extra 文件/文件夹到全局仓库
 * @param {string} rtype
 * @param {string} srcPath
 * @param {string} instanceName
 * @returns {$CancellablePromise<void>}
 */
export function PullSingleResourceFromInstance(rtype, srcPath, instanceName) {
    return $Call.ByID(2266526243, rtype, srcPath, instanceName);
}

/**
 * PushResourceToInstance 将全局中缺失的资源推送到整合包
 * @param {string} rtype
 * @param {string} instanceName
 * @returns {$CancellablePromise<number>}
 */
export function PushResourceToInstance(rtype, instanceName) {
    return $Call.ByID(3583202917, rtype, instanceName);
}

/**
 * PushSingleResourceToInstance 推送单个文件/文件夹到整合包
 * @param {string} rtype
 * @param {string} instanceName
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function PushSingleResourceToInstance(rtype, instanceName, filePath) {
    return $Call.ByID(3553253805, rtype, instanceName, filePath);
}

/**
 * @returns {$CancellablePromise<$models.QueueStatusInfo>}
 */
export function QueueStatus() {
    return $Call.ByID(1350901616).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileBytes(path) {
    return $Call.ByID(2124137540, path).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * ReadLitematicMeta 读取投影文件元数据（作者/时间/版本/方块统计/预览图）
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadLitematicMeta(path) {
    return $Call.ByID(3216421386, path);
}

/**
 * ReadNbtStructure 读取 .nbt 结构文件基本信息
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadNbtStructure(path) {
    return $Call.ByID(304829738, path);
}

/**
 * ReadPackMeta 读取资源包信息（pack.mcmeta + pack.png）
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadPackMeta(path) {
    return $Call.ByID(1762327275, path);
}

/**
 * ReadSchematic 读取 .schematic 文件基本信息
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadSchematic(path) {
    return $Call.ByID(2285677248, path);
}

/**
 * ReadShaderpackLang 读取光影包 lang/en_US.lang 提取显示名
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadShaderpackLang(path) {
    return $Call.ByID(3411986111, path);
}

/**
 * RelinkAllInstanceResources 重新应用链接模式到整合包所有资源类型目录
 * @param {string} instanceName
 * @returns {$CancellablePromise<number>}
 */
export function RelinkAllInstanceResources(instanceName) {
    return $Call.ByID(3612469403, instanceName);
}

/**
 * RelinkCustomDir 重新应用链接模式到指定目录（兼容旧版）
 * @param {string} customDir
 * @param {string} repoRoot
 * @returns {$CancellablePromise<number>}
 */
export function RelinkCustomDir(customDir, repoRoot) {
    return $Call.ByID(3736551740, customDir, repoRoot);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function RemoveDir(dir) {
    return $Call.ByID(2521913290, dir);
}

/**
 * @param {string} oldPath
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameDir(oldPath, newName) {
    return $Call.ByID(1511264492, oldPath, newName);
}

/**
 * @param {string} oldPath
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(oldPath, newName) {
    return $Call.ByID(1176761595, oldPath, newName);
}

/**
 * @param {string} jsonContent
 * @returns {$CancellablePromise<number>}
 */
export function ReplaceWorkshopCreatorsFromJSON(jsonContent) {
    return $Call.ByID(1355854287, jsonContent);
}

/**
 * ResetResourceRoot 恢复指定资源类型的路径为默认（清空自定义值）
 * @param {string} rtype
 * @returns {$CancellablePromise<void>}
 */
export function ResetResourceRoot(rtype) {
    return $Call.ByID(3252835018, rtype);
}

/**
 * @returns {$CancellablePromise<types$0.WorkshopSite[]>}
 */
export function ResetWorkshopConfigs() {
    return $Call.ByID(2959472146).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RestartApplication() {
    return $Call.ByID(143393668);
}

/**
 * @param {string} src
 * @param {string} repoRoot
 * @returns {$CancellablePromise<void>}
 */
export function RestoreFromRecycle(src, repoRoot) {
    return $Call.ByID(983517996, src, repoRoot);
}

/**
 * ========== 在资源管理器中显示 ==========
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RevealInExplorer(path) {
    return $Call.ByID(3185410442, path);
}

/**
 * @param {string} filesRoot
 * @param {string} rpRoot
 * @param {string} mcRoot
 * @param {string} linkMode
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SaveAppConfig(filesRoot, rpRoot, mcRoot, linkMode, theme) {
    return $Call.ByID(3201182099, filesRoot, rpRoot, mcRoot, linkMode, theme);
}

/**
 * @param {string} base64Data
 * @returns {$CancellablePromise<string>}
 */
export function SavePreviewTempFile(base64Data) {
    return $Call.ByID(3917626618, base64Data);
}

/**
 * SaveScreenshotFile 保存 base64 PNG 到磁盘（供 JS 批量截图用）
 * @param {string} filename
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function SaveScreenshotFile(filename, base64Data) {
    return $Call.ByID(1822573792, filename, base64Data);
}

/**
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SaveWindowPosition(x, y, width, height) {
    return $Call.ByID(469886297, x, y, width, height);
}

/**
 * @param {types$0.WorkshopCreator[]} list
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkshopCreators(list) {
    return $Call.ByID(2516832214, list);
}

/**
 * SaveWorkshopCreatorsBySite 只替换指定站点的创作者，其他站点不动
 * @param {string} siteID
 * @param {types$0.WorkshopCreator[]} siteCreators
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkshopCreatorsBySite(siteID, siteCreators) {
    return $Call.ByID(3867129300, siteID, siteCreators);
}

/**
 * SaveWorkshopPresetsBySite 只替换指定站点的搜索词，其他站点不动
 * @param {string} siteID
 * @param {types$0.WorkshopPresetSearch[]} presets
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkshopPresetsBySite(siteID, presets) {
    return $Call.ByID(4066089783, siteID, presets);
}

/**
 * @param {types$0.WorkshopSite[]} sites
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkshopSites(sites) {
    return $Call.ByID(2656683497, sites);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<types$0.ModelEntry[]>}
 */
export function ScanCustomModels(dir) {
    return $Call.ByID(2414288603, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * ScanLocalAuthors 扫描所有本地资源目录，从文件名提取作者
 * 返回统一格式的创作者列表（可直接合并到 creators.json）
 * @returns {$CancellablePromise<types$0.WorkshopCreator[]>}
 */
export function ScanLocalAuthors() {
    return $Call.ByID(3176279871).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * ========== 模型扫描 ==========
 * @param {string} dir
 * @returns {$CancellablePromise<types$0.ModelEntry[]>}
 */
export function ScanModelEntries(dir) {
    return $Call.ByID(963930825, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * ========== 高级搜索 ==========
 * @param {string} repoRoot
 * @param {string} keyword
 * @param {number} minBones
 * @param {number} maxBones
 * @param {number} minCubes
 * @param {number} maxCubes
 * @param {number} minTex
 * @param {number} maxTex
 * @returns {$CancellablePromise<types$0.SearchResult[]>}
 */
export function SearchModels(repoRoot, keyword, minBones, maxBones, minCubes, maxCubes, minTex, maxTex) {
    return $Call.ByID(652244789, repoRoot, keyword, minBones, maxBones, minCubes, maxCubes, minTex, maxTex).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * ========== 目录选择 ==========
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(2136780286);
}

/**
 * SelectImportFile 打开文件选择器，按给定扩展名过滤
 * filter 格式: "显示名|*.ext1;*.ext2"
 * @param {string} filter
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function SelectImportFile(filter, title) {
    return $Call.ByID(3917673792, filter, title);
}

/**
 * SelectImportZip 打开文件选择器选取 .zip 文件
 * @returns {$CancellablePromise<string>}
 */
export function SelectImportZip() {
    return $Call.ByID(3551213909);
}

/**
 * SetApp 注入 Wails 3 应用实例，供 service 方法访问窗口/事件/对话框/浏览器管理器
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(2864115508, app);
}

/**
 * @param {string} mirror
 * @returns {$CancellablePromise<void>}
 */
export function SetDownloadMirror(mirror) {
    return $Call.ByID(1760896254, mirror);
}

/**
 * ========== 链接模式 ==========
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetLinkMode(mode) {
    return $Call.ByID(2002865150, mode);
}

/**
 * SetMainWindow 注入主窗口实例，避免依赖 Window.Current()。
 * 注意：ServiceStartup 在 app.Run() 早期被调用，此时窗口尚未成为 Current，
 * Window.Current() 会返回 nil 导致空指针；故改用直接持有的窗口引用。
 * @param {application$0.WebviewWindow | null} w
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(w) {
    return $Call.ByID(734441964, w);
}

/**
 * SetModelTags 设置指定模型文件的标签列表（覆盖写入）
 * @param {string} modelPath
 * @param {string[]} tags
 * @returns {$CancellablePromise<void>}
 */
export function SetModelTags(modelPath, tags) {
    return $Call.ByID(4009573307, modelPath, tags);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetRepoRoot(dir) {
    return $Call.ByID(1007646501, dir);
}

/**
 * SetResourceRoot 设置指定资源类型的自定义根路径（空=恢复默认）
 * @param {string} rtype
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetResourceRoot(rtype, path) {
    return $Call.ByID(3405438717, rtype, path);
}

/**
 * SetVoxelMaxBlocks 设置 3D 体素渲染上限，0=恢复默认 200000
 * @param {number} limit
 * @returns {$CancellablePromise<void>}
 */
export function SetVoxelMaxBlocks(limit) {
    return $Call.ByID(1029825393, limit);
}

/**
 * StartProxy 启动本地反代服务器（127.0.0.1 仅本机可访问）
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function StartProxy(port) {
    return $Call.ByID(3346937763, port);
}

/**
 * StopProxy 关闭反代服务器
 * @returns {$CancellablePromise<void>}
 */
export function StopProxy() {
    return $Call.ByID(3863670921);
}

/**
 * @param {string} customDir
 * @param {string} repoDir
 * @returns {$CancellablePromise<number>}
 */
export function SyncCustomToRepo(customDir, repoDir) {
    return $Call.ByID(1317956650, customDir, repoDir);
}

/**
 * @param {string} instanceCustomDir
 * @param {string} repoRoot
 * @returns {$CancellablePromise<[number, number]>}
 */
export function SyncModelToggleStatus(instanceCustomDir, repoRoot) {
    return $Call.ByID(933155543, instanceCustomDir, repoRoot);
}

/**
 * SyncResources 获取全局 ↔ 整合包的资源同步状态
 * @param {string} rtype
 * @param {string} instanceName
 * @returns {$CancellablePromise<string>}
 */
export function SyncResources(rtype, instanceName) {
    return $Call.ByID(2551449925, rtype, instanceName);
}

/**
 * ========== 启用/禁用 ==========
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleModelEnable(path) {
    return $Call.ByID(3300558263, path);
}

/**
 * ToggleResourcePack 切换资源包的启用/禁用状态（.zip ↔ .zip.disabled）
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleResourcePack(path) {
    return $Call.ByID(3911031138, path);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<[string, string]>}
 */
export function ValidateMinecraftDir(dir) {
    return $Call.ByID(2967962547, dir);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = types$0.BedrockModel.createFrom;
const $$createType2 = ysm$0.YSMModelMeta.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = updater$0.UpdateInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = ysm$0.YSMHeader.createFrom;
const $$createType7 = ysm$0.YsmSummary.createFrom;
const $$createType8 = types$0.ImportLog.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = types$0.InstanceStatus.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ysm$0.TexInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = types$0.PackInfo.createFrom;
const $$createType15 = types$0.WindowState.createFrom;
const $$createType16 = types$0.AuthorInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = types$0.ModelEntry.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = types$0.VersionInstance.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = types$0.AppConfig.createFrom;
const $$createType23 = types$0.WorkshopCreator.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = types$0.WorkshopSite.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.QueueStatusInfo.createFrom;
const $$createType28 = types$0.SearchResult.createFrom;
const $$createType29 = $Create.Array($$createType28);
