// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../go/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../go/updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ysm$0 from "../../go/ysm/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ========== 日志 ==========
 */
export function AddImportLog(modelName: string, sourcePath: string, targetDir: string, fileSize: number, status: string, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(3744622591, modelName, sourcePath, targetDir, fileSize, status, errMsg);
}

export function AddOpLog(op: string, modelName: string, sourcePath: string, targetDir: string, fileSize: number, status: string, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(2143326689, op, modelName, sourcePath, targetDir, fileSize, status, errMsg);
}

/**
 * AllTags 返回所有被使用的标签（按使用次数降序）
 */
export function AllTags(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1246240395);
}

export function AnalyzeBedrockModel(modelPath: string): $CancellablePromise<types$0.BedrockModel> {
    return $Call.ByID(2221616526, modelPath);
}

export function AnalyzeYSMModel(path: string): $CancellablePromise<ysm$0.YSMModelMeta> {
    return $Call.ByID(87919393, path);
}

export function ApplyUpdate(zipPath: string): $CancellablePromise<void> {
    return $Call.ByID(3688265704, zipPath);
}

export function BackupWorkshopCreators(): $CancellablePromise<string> {
    return $Call.ByID(3964989829);
}

/**
 * BatchExtractCreatorAvatars 批量提取所有有本地模型的创作者头像
 */
export function BatchExtractCreatorAvatars(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2317353684);
}

/**
 * CacheModelAvatars 从解压目录 ysm.json 缓存头像
 */
export function CacheModelAvatars(modelPath: string): $CancellablePromise<void> {
    return $Call.ByID(3423756102, modelPath);
}

/**
 * CachedCreatorAvatar 检查缓存中是否有作者头像，返回 data URI
 */
export function CachedCreatorAvatar(authorName: string): $CancellablePromise<string> {
    return $Call.ByID(224206566, authorName);
}

export function CancelQueue(): $CancellablePromise<void> {
    return $Call.ByID(1786226156);
}

export function CheckFileExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(467508719, path);
}

export function CheckUpdate(): $CancellablePromise<updater$0.UpdateInfo | null> {
    return $Call.ByID(651964520);
}

export function ClearCustomDir(customDir: string): $CancellablePromise<number> {
    return $Call.ByID(2697468754, customDir);
}

export function ClearImportLogs(): $CancellablePromise<void> {
    return $Call.ByID(3815103174);
}

/**
 * ClearInstanceResources 清空指定整合包中已同步的文件（走回收站）
 * insName: 整合包名, rtype: 资源类型（空=全部, 非空=只清此类型）
 * 返回清除的文件数量
 */
export function ClearInstanceResources(insName: string, rtype: string): $CancellablePromise<number> {
    return $Call.ByID(310409492, insName, rtype);
}

/**
 * ClearScanCache 清除扫描缓存（下载/导入后调用）
 */
export function ClearScanCache(): $CancellablePromise<void> {
    return $Call.ByID(3066626705);
}

/**
 * ========== 模型复制 ==========
 * CopyModelFile 将 src 复制到 dstDir 目录下（保留原文件名）
 * dstDir 必须是 FilesRoot 的子目录（防路径遍历）
 */
export function CopyModelFile(src: string, dstDir: string): $CancellablePromise<void> {
    return $Call.ByID(2849400957, src, dstDir);
}

/**
 * CountDuplicateFiles 快速统计重复文件数量
 */
export function CountDuplicateFiles(dir: string): $CancellablePromise<string> {
    return $Call.ByID(2412651574, dir);
}

/**
 * CountInstanceResources 统计指定整合包中可清空的资源文件数
 * 只统计仓库中已有的文件（同 clearInstanceDir 逻辑）
 * rtype 为空时统计全部类型，否则只统计指定类型
 */
export function CountInstanceResources(insName: string, rtype: string): $CancellablePromise<number> {
    return $Call.ByID(136508414, insName, rtype);
}

/**
 * ========== 目录操作 ==========
 */
export function CreateDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(14567662, dir);
}

export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(2861439428);
}

/**
 * DebugExtractCreatorAvatar 调试版：提取指定作者头像
 */
export function DebugExtractCreatorAvatar(authorName: string): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1802835376, authorName);
}

export function DeduplicateCustomDir(customDir: string): $CancellablePromise<[number, number]> {
    return $Call.ByID(2166378965, customDir);
}

export function DeleteFromRecycle(src: string): $CancellablePromise<void> {
    return $Call.ByID(2594824985, src);
}

/**
 * DeleteModelDir 删除文件夹型资源（MMD 模型等），删除文件所在父文件夹
 */
export function DeleteModelDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(2959912528, path);
}

/**
 * DeleteResourcePack 删除资源包文件
 */
export function DeleteResourcePack(path: string): $CancellablePromise<void> {
    return $Call.ByID(395621705, path);
}

/**
 * DetectResourceType 检测指定文件的资源类型
 */
export function DetectResourceType(path: string): $CancellablePromise<string> {
    return $Call.ByID(2113518140, path);
}

/**
 * DetectZipType 通过 ZIP 内容检测资源类型（供前端导入路由使用）
 */
export function DetectZipType(base64Data: string): $CancellablePromise<string> {
    return $Call.ByID(747133431, base64Data);
}

export function DoUpdate(url: string, expectedHash: string): $CancellablePromise<string> {
    return $Call.ByID(985752667, url, expectedHash);
}

export function DownloadFromGitHub(rawURL: string, saveDir: string): $CancellablePromise<string> {
    return $Call.ByID(960385788, rawURL, saveDir);
}

export function DownloadUpdate(url: string, expectedHash: string): $CancellablePromise<string> {
    return $Call.ByID(2886098546, url, expectedHash);
}

export function EmptyRecycleBin($0: string): $CancellablePromise<number> {
    return $Call.ByID(4211256250, $0);
}

export function EnqueueDownloads(tasks: $models.DownloadTask[] | null): $CancellablePromise<void> {
    return $Call.ByID(552244624, tasks);
}

/**
 * ========== 批量导出骨骼结构 ==========
 */
export function ExportBoneStructures(repoRoot: string): $CancellablePromise<string> {
    return $Call.ByID(2854573701, repoRoot);
}

/**
 * ExportModelStructureJSON 导出单模型骨骼结构
 */
export function ExportModelStructureJSON(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(2285469521, modelPath);
}

export function ExportWorkshopCreatorsJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(3313564853);
}

/**
 * ========== CSV 导出/导入 ==========
 */
export function ExportWorkshopSitesCSV(): $CancellablePromise<string> {
    return $Call.ByID(2284407588);
}

export function ExportWorkshopSitesJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(3241109304);
}

export function ExtractPreviewTexture(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(4136663739, modelPath);
}

export function ExtractYSMHeader(path: string): $CancellablePromise<ysm$0.YSMHeader> {
    return $Call.ByID(3464271858, path);
}

export function ExtractYSMHeaderFromBase64(base64Data: string): $CancellablePromise<ysm$0.YSMHeader> {
    return $Call.ByID(547420281, base64Data);
}

export function ExtractYsmSummary(path: string): $CancellablePromise<ysm$0.YsmSummary> {
    return $Call.ByID(847066301, path);
}

/**
 * FindDuplicateFiles 扫描目录返回所有重复文件分组（JSON 字符串）
 */
export function FindDuplicateFiles(dir: string): $CancellablePromise<string> {
    return $Call.ByID(1295941240, dir);
}

/**
 * ========== 预览提取 ==========
 */
export function FindPreviewImage(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(528549045, modelPath);
}

/**
 * GenerateRepoIndex 扫描仓库目录，生成 index.json
 */
export function GenerateRepoIndex(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(1563740856, repoPath);
}

/**
 * GetAppVersion 返回当前版本号
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(115297084);
}

export function GetGlobalCustomDir(mcRoot: string): $CancellablePromise<string> {
    return $Call.ByID(4119708496, mcRoot);
}

export function GetImportLogs(): $CancellablePromise<types$0.ImportLog[] | null> {
    return $Call.ByID(1065567147);
}

/**
 * ========== 状态同步 ==========
 */
export function GetInstanceStatus(mcRoot: string, repoDir: string): $CancellablePromise<types$0.InstanceStatus[] | null> {
    return $Call.ByID(4224028016, mcRoot, repoDir);
}

/**
 * GetInstanceSyncStatus 获取整合包下所有资源类型的同步状态（扁平列表）
 */
export function GetInstanceSyncStatus(instanceName: string): $CancellablePromise<string> {
    return $Call.ByID(839308247, instanceName);
}

export function GetLinkMode(): $CancellablePromise<string> {
    return $Call.ByID(736604018);
}

/**
 * GetLitematicVoxelData 读取投影文件体素数据（按颜色分组的方块位置）
 */
export function GetLitematicVoxelData(path: string): $CancellablePromise<string> {
    return $Call.ByID(2172897631, path);
}

export function GetMinecraftPaths(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2122198272);
}

export function GetModel3DSpec(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(2923299250, modelPath);
}

/**
 * GetModelTags 返回指定模型文件的所有标签
 */
export function GetModelTags(modelPath: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(234236959, modelPath);
}

/**
 * GetModelTexSizes 扫描仓库文件提取纹理尺寸（轻量级，不解析完整模型）
 */
export function GetModelTexSizes(repoRoot: string): $CancellablePromise<ysm$0.TexInfo[] | null> {
    return $Call.ByID(1273620259, repoRoot);
}

/**
 * GetNbtVoxelData 读取 .nbt 结构文件体素数据
 */
export function GetNbtVoxelData(path: string): $CancellablePromise<string> {
    return $Call.ByID(2164005593, path);
}

/**
 * ========== 包信息 ==========
 */
export function GetPackInfo(dirPath: string): $CancellablePromise<types$0.PackInfo> {
    return $Call.ByID(2243407216, dirPath);
}

/**
 * GetRepoRoot 根据资源类型返回对应的仓库根目录
 */
export function GetRepoRoot(rtype: string): $CancellablePromise<string> {
    return $Call.ByID(4011191521, rtype);
}

/**
 * GetResourceInstanceStatus 按资源类型获取整合包同步状态
 * repoDir 仅对 YSM 类型生效（其他类型从全局资源目录推导）
 */
export function GetResourceInstanceStatus(rtype: string, mcRoot: string, repoDir: string): $CancellablePromise<types$0.InstanceStatus[] | null> {
    return $Call.ByID(779607888, rtype, mcRoot, repoDir);
}

/**
 * GetSchematicVoxelData 读取 .schematic 文件体素数据
 */
export function GetSchematicVoxelData(path: string): $CancellablePromise<string> {
    return $Call.ByID(199377974, path);
}

/**
 * ========== 自动更新 ==========
 * GetSubDirMap 返回资源类型→子目录映射表（前端右键菜单等场景使用）
 */
export function GetSubDirMap(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2085433910);
}

/**
 * GetWasmBinary 返回内嵌的 YSMParser.wasm 字节（供前端 WebView2 使用）。
 * wasmBinary 由根包 main 的 init() 经 SetEmbedded 注入。
 */
export function GetWasmBinary(): $CancellablePromise<string | null> {
    return $Call.ByID(2670724632);
}

export function GetWindowPosition(): $CancellablePromise<types$0.WindowState> {
    return $Call.ByID(3862857718);
}

/**
 * ========== YSM 检测 ==========
 */
export function HasYSMMod(modsDir: string): $CancellablePromise<boolean> {
    return $Call.ByID(1327539980, modsDir);
}

/**
 * ImportByType 统一导入入口——根据资源类型自动选择导入策略
 */
export function ImportByType(rtype: string, srcPath: string): $CancellablePromise<string> {
    return $Call.ByID(1466768695, rtype, srcPath);
}

export function ImportModelFile(fileName: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(2135926573, fileName, base64Data);
}

export function ImportModelFileOverwrite(fileName: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(2920266218, fileName, base64Data);
}

export function ImportModelFileOverwriteTo(fileName: string, subpath: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(3849603631, fileName, subpath, base64Data);
}

export function ImportModelFileSkipCheck(fileName: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(334185050, fileName, base64Data);
}

export function ImportModelFileTo(fileName: string, subpath: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(191674492, fileName, subpath, base64Data);
}

/**
 * ImportResourcePack 使用策略模式导入资源包
 */
export function ImportResourcePack(srcPath: string, rtype: string): $CancellablePromise<string> {
    return $Call.ByID(2578913479, srcPath, rtype);
}

export function ImportWorkshopSitesCSV(csvContent: string): $CancellablePromise<void> {
    return $Call.ByID(1342547047, csvContent);
}

export function ImportWorkshopSitesJSONFile(): $CancellablePromise<number> {
    return $Call.ByID(1933238405);
}

/**
 * ========== 安装 ==========
 */
export function InstallModelFile(src: string, mcRoot: string): $CancellablePromise<string> {
    return $Call.ByID(2558470757, src, mcRoot);
}

export function InstallModelTo(src: string, customDir: string): $CancellablePromise<void> {
    return $Call.ByID(547256422, src, customDir);
}

export function InstallModelWithOverlay(src: string, customDir: string): $CancellablePromise<string> {
    return $Call.ByID(4168467473, src, customDir);
}

/**
 * InstallResourceToInstance 将资源文件安装到指定整合包
 * rtype: 资源类型（resourcepack/shaderpack 等），srcPath: 源文件路径，instanceName: 整合包名称
 */
export function InstallResourceToInstance(rtype: string, srcPath: string, instanceName: string): $CancellablePromise<void> {
    return $Call.ByID(215553224, rtype, srcPath, instanceName);
}

/**
 * InvalidateScanCache 清空扫描缓存，下次扫描获取最新数据
 */
export function InvalidateScanCache(): $CancellablePromise<void> {
    return $Call.ByID(2605564787);
}

export function IsFileBanned(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3330292233, path);
}

/**
 * IsProxyRunning 检查代理是否运行中
 */
export function IsProxyRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3002035324);
}

/**
 * IsResourcePackEnabled 检查资源包是否启用
 */
export function IsResourcePackEnabled(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2413288079, path);
}

/**
 * ListAllFilePaths 递归列出指定目录下的所有文件完整路径（不限制扩展名）
 */
export function ListAllFilePaths(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(504456952, dir);
}

/**
 * ListByTag 返回所有打了指定标签的文件路径列表
 */
export function ListByTag(tag: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(543634162, tag);
}

export function ListFileNames(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(223101035, dir);
}

export function ListModelAuthors(): $CancellablePromise<types$0.AuthorInfo[] | null> {
    return $Call.ByID(2783678748);
}

export function ListRecycleBin($0: string): $CancellablePromise<types$0.ModelEntry[] | null> {
    return $Call.ByID(3420025601, $0);
}

export function ListVersionInstances(mcRoot: string): $CancellablePromise<types$0.VersionInstance[] | null> {
    return $Call.ByID(2348617735, mcRoot);
}

export function LoadAppConfig(): $CancellablePromise<types$0.AppConfig> {
    return $Call.ByID(4081731812);
}

export function LoadGitHubRepos(): $CancellablePromise<types$0.WorkshopCreator[] | null> {
    return $Call.ByID(555735249);
}

/**
 * LoadResourceTypes 加载资源类型注册表
 */
export function LoadResourceTypes(): $CancellablePromise<string> {
    return $Call.ByID(3636552016);
}

export function LoadWorkshopCreators(): $CancellablePromise<types$0.WorkshopCreator[] | null> {
    return $Call.ByID(3429491443);
}

export function LoadWorkshopSites(): $CancellablePromise<types$0.WorkshopSite[] | null> {
    return $Call.ByID(1402443890);
}

export function MergeWorkshopCreatorsFromJSON(jsonContent: string): $CancellablePromise<[number, number]> {
    return $Call.ByID(2866539347, jsonContent);
}

/**
 * ========== 模型移动 ==========
 */
export function MoveModelFile(src: string, dstDir: string): $CancellablePromise<void> {
    return $Call.ByID(1018628389, src, dstDir);
}

/**
 * ========== 回收站 ==========
 */
export function MoveToRecycle(src: string): $CancellablePromise<void> {
    return $Call.ByID(1383304780, src);
}

export function MoveToRecycleEx(src: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(2099759785, src);
}

export function OpenFolder(dir: string): $CancellablePromise<void> {
    return $Call.ByID(4260431887, dir);
}

/**
 * OpenInBrowser 在系统默认浏览器中打开链接（而非 WebView2 内嵌）
 */
export function OpenInBrowser(url: string): $CancellablePromise<void> {
    return $Call.ByID(3205913216, url);
}

/**
 * OpenInstanceFolder 按资源类型打开整合包子目录；目录不存在时回退到实例根目录
 */
export function OpenInstanceFolder(instDir: string, rtype: string): $CancellablePromise<void> {
    return $Call.ByID(2384592956, instDir, rtype);
}

/**
 * PullResourceFromInstance 将整合包中多余的资源拉取到全局
 */
export function PullResourceFromInstance(rtype: string, instanceName: string): $CancellablePromise<number> {
    return $Call.ByID(3336031775, rtype, instanceName);
}

/**
 * PullSingleResourceFromInstance 从整合包拉取单个 extra 文件/文件夹到全局仓库
 */
export function PullSingleResourceFromInstance(rtype: string, srcPath: string, instanceName: string): $CancellablePromise<void> {
    return $Call.ByID(2266526243, rtype, srcPath, instanceName);
}

/**
 * PushResourceToInstance 将全局中缺失的资源推送到整合包
 */
export function PushResourceToInstance(rtype: string, instanceName: string): $CancellablePromise<number> {
    return $Call.ByID(3583202917, rtype, instanceName);
}

/**
 * PushSingleResourceToInstance 推送单个文件/文件夹到整合包
 */
export function PushSingleResourceToInstance(rtype: string, instanceName: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(3553253805, rtype, instanceName, filePath);
}

export function QueueStatus(): $CancellablePromise<$models.QueueStatusInfo> {
    return $Call.ByID(1350901616);
}

export function ReadFileBytes(path: string): $CancellablePromise<string | null> {
    return $Call.ByID(2124137540, path);
}

/**
 * ReadLitematicMeta 读取投影文件元数据（作者/时间/版本/方块统计/预览图）
 */
export function ReadLitematicMeta(path: string): $CancellablePromise<string> {
    return $Call.ByID(3216421386, path);
}

/**
 * ReadNbtStructure 读取 .nbt 结构文件基本信息
 */
export function ReadNbtStructure(path: string): $CancellablePromise<string> {
    return $Call.ByID(304829738, path);
}

/**
 * ReadPackMeta 读取资源包信息（pack.mcmeta + pack.png）
 */
export function ReadPackMeta(path: string): $CancellablePromise<string> {
    return $Call.ByID(1762327275, path);
}

/**
 * ReadSchematic 读取 .schematic 文件基本信息
 */
export function ReadSchematic(path: string): $CancellablePromise<string> {
    return $Call.ByID(2285677248, path);
}

/**
 * ReadShaderpackLang 读取光影包 lang/en_US.lang 提取显示名
 */
export function ReadShaderpackLang(path: string): $CancellablePromise<string> {
    return $Call.ByID(3411986111, path);
}

/**
 * RelinkAllInstanceResources 重新应用链接模式到整合包所有资源类型目录
 */
export function RelinkAllInstanceResources(instanceName: string): $CancellablePromise<number> {
    return $Call.ByID(3612469403, instanceName);
}

/**
 * RelinkCustomDir 重新应用链接模式到指定目录（兼容旧版）
 */
export function RelinkCustomDir(customDir: string, repoRoot: string): $CancellablePromise<number> {
    return $Call.ByID(3736551740, customDir, repoRoot);
}

export function RemoveDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2521913290, dir);
}

export function RenameDir(oldPath: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1511264492, oldPath, newName);
}

export function RenameFile(oldPath: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1176761595, oldPath, newName);
}

export function ReplaceWorkshopCreatorsFromJSON(jsonContent: string): $CancellablePromise<number> {
    return $Call.ByID(1355854287, jsonContent);
}

/**
 * ResetResourceRoot 恢复指定资源类型的路径为默认（清空自定义值）
 */
export function ResetResourceRoot(rtype: string): $CancellablePromise<void> {
    return $Call.ByID(3252835018, rtype);
}

export function ResetWorkshopConfigs(): $CancellablePromise<types$0.WorkshopSite[] | null> {
    return $Call.ByID(2959472146);
}

export function RestartApplication(): $CancellablePromise<void> {
    return $Call.ByID(143393668);
}

export function RestoreFromRecycle(src: string, repoRoot: string): $CancellablePromise<void> {
    return $Call.ByID(983517996, src, repoRoot);
}

/**
 * ========== 在资源管理器中显示 ==========
 */
export function RevealInExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(3185410442, path);
}

export function SaveAppConfig(filesRoot: string, rpRoot: string, mcRoot: string, linkMode: string, theme: string): $CancellablePromise<void> {
    return $Call.ByID(3201182099, filesRoot, rpRoot, mcRoot, linkMode, theme);
}

export function SavePreviewTempFile(base64Data: string): $CancellablePromise<string> {
    return $Call.ByID(3917626618, base64Data);
}

/**
 * SaveScreenshotFile 保存 base64 PNG 到磁盘（供 JS 批量截图用）
 */
export function SaveScreenshotFile(filename: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(1822573792, filename, base64Data);
}

export function SaveWindowPosition(x: number, y: number, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(469886297, x, y, width, height);
}

export function SaveWorkshopCreators(list: types$0.WorkshopCreator[] | null): $CancellablePromise<void> {
    return $Call.ByID(2516832214, list);
}

/**
 * SaveWorkshopCreatorsBySite 只替换指定站点的创作者，其他站点不动
 */
export function SaveWorkshopCreatorsBySite(siteID: string, siteCreators: types$0.WorkshopCreator[] | null): $CancellablePromise<void> {
    return $Call.ByID(3867129300, siteID, siteCreators);
}

/**
 * SaveWorkshopPresetsBySite 只替换指定站点的搜索词，其他站点不动
 */
export function SaveWorkshopPresetsBySite(siteID: string, presets: types$0.WorkshopPresetSearch[] | null): $CancellablePromise<void> {
    return $Call.ByID(4066089783, siteID, presets);
}

export function SaveWorkshopSites(sites: types$0.WorkshopSite[] | null): $CancellablePromise<void> {
    return $Call.ByID(2656683497, sites);
}

export function ScanCustomModels(dir: string): $CancellablePromise<types$0.ModelEntry[] | null> {
    return $Call.ByID(2414288603, dir);
}

/**
 * ScanLocalAuthors 扫描所有本地资源目录，从文件名提取作者
 * 返回统一格式的创作者列表（可直接合并到 creators.json）
 */
export function ScanLocalAuthors(): $CancellablePromise<types$0.WorkshopCreator[] | null> {
    return $Call.ByID(3176279871);
}

/**
 * ========== 模型扫描 ==========
 */
export function ScanModelEntries(dir: string): $CancellablePromise<types$0.ModelEntry[] | null> {
    return $Call.ByID(963930825, dir);
}

/**
 * ========== 高级搜索 ==========
 */
export function SearchModels(repoRoot: string, keyword: string, minBones: number, maxBones: number, minCubes: number, maxCubes: number, minTex: number, maxTex: number): $CancellablePromise<types$0.SearchResult[] | null> {
    return $Call.ByID(652244789, repoRoot, keyword, minBones, maxBones, minCubes, maxCubes, minTex, maxTex);
}

/**
 * ========== 目录选择 ==========
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2136780286);
}

/**
 * SelectImportFile 打开文件选择器，按给定扩展名过滤
 * filter 格式: "显示名|*.ext1;*.ext2"
 */
export function SelectImportFile(filter: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(3917673792, filter, title);
}

/**
 * SelectImportZip 打开文件选择器选取 .zip 文件
 */
export function SelectImportZip(): $CancellablePromise<string> {
    return $Call.ByID(3551213909);
}

/**
 * SetApp 注入 Wails 3 应用实例，供 service 方法访问窗口/事件/对话框/浏览器管理器
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2864115508, app);
}

export function SetDownloadMirror(mirror: string): $CancellablePromise<void> {
    return $Call.ByID(1760896254, mirror);
}

/**
 * ========== 链接模式 ==========
 */
export function SetLinkMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(2002865150, mode);
}

/**
 * SetMainWindow 注入主窗口实例，避免依赖 Window.Current()。
 * 注意：ServiceStartup 在 app.Run() 早期被调用，此时窗口尚未成为 Current，
 * Window.Current() 会返回 nil 导致空指针；故改用直接持有的窗口引用。
 */
export function SetMainWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(734441964, w);
}

/**
 * SetModelTags 设置指定模型文件的标签列表（覆盖写入）
 */
export function SetModelTags(modelPath: string, tags: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4009573307, modelPath, tags);
}

export function SetRepoRoot(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1007646501, dir);
}

/**
 * SetResourceRoot 设置指定资源类型的自定义根路径（空=恢复默认）
 */
export function SetResourceRoot(rtype: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3405438717, rtype, path);
}

/**
 * SetVoxelMaxBlocks 设置 3D 体素渲染上限，0=恢复默认 200000
 */
export function SetVoxelMaxBlocks(limit: number): $CancellablePromise<void> {
    return $Call.ByID(1029825393, limit);
}

/**
 * StartProxy 启动本地反代服务器（127.0.0.1 仅本机可访问）
 */
export function StartProxy(port: number): $CancellablePromise<void> {
    return $Call.ByID(3346937763, port);
}

/**
 * StopProxy 关闭反代服务器
 */
export function StopProxy(): $CancellablePromise<void> {
    return $Call.ByID(3863670921);
}

export function SyncCustomToRepo(customDir: string, repoDir: string): $CancellablePromise<number> {
    return $Call.ByID(1317956650, customDir, repoDir);
}

export function SyncModelToggleStatus(instanceCustomDir: string, repoRoot: string): $CancellablePromise<[number, number]> {
    return $Call.ByID(933155543, instanceCustomDir, repoRoot);
}

/**
 * SyncResources 获取全局 ↔ 整合包的资源同步状态
 */
export function SyncResources(rtype: string, instanceName: string): $CancellablePromise<string> {
    return $Call.ByID(2551449925, rtype, instanceName);
}

/**
 * ========== 启用/禁用 ==========
 */
export function ToggleModelEnable(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3300558263, path);
}

/**
 * ToggleResourcePack 切换资源包的启用/禁用状态（.zip ↔ .zip.disabled）
 */
export function ToggleResourcePack(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3911031138, path);
}

export function ValidateMinecraftDir(dir: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(2967962547, dir);
}
