// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../go/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../go/updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ysm$0 from "../../go/ysm/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ========== 日志 ==========
 */
export function AddImportLog(modelName: string, sourcePath: string, targetDir: string, fileSize: number, status: string, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(3744622591, modelName, sourcePath, targetDir, fileSize, status, errMsg);
}

export function AddOpLog(op: string, modelName: string, sourcePath: string, targetDir: string, fileSize: number, status: string, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(2143326689, op, modelName, sourcePath, targetDir, fileSize, status, errMsg);
}

/**
 * AllTags 返回所有被使用的标签（按使用次数降序）
 */
export function AllTags(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1246240395);
}

export function AnalyzeBedrockModel(modelPath: string): $CancellablePromise<types$0.BedrockModel> {
    return $Call.ByID(2221616526, modelPath);
}

/**
 * AnalyzeBedrockModelEntry 按 SubModel.SourcePath 只解析归档内单模型 geometry（多角色包角色切换用）。
 * 
 * 路径守卫：与 AnalyzeBedrockModel 对齐 isPathInRootOrSelf；subPath 是 zip/7z 内 entry 路径，只用于
 * 归档内 geoFile 匹配，不涉及文件系统。
 * 
 * 返回规则：
 *   - 单条目命中 → BedrockModel 为该单角色 Bones（BoneCount/CubeCount 对应单模型）；Textures/TextureNames 仍全量（切纹理不换 PNG 集合，只换 texIdx）
 *   - 单条目未命中 → 空 BedrockModel{}（前端据此回退到全量解析 AnalyzeBedrockModel）
 *   - ext == .ysm / .json（非压缩包）或 subPath 空 → 空 BedrockModel{}
 */
export function AnalyzeBedrockModelEntry(modelPath: string, subPath: string): $CancellablePromise<types$0.BedrockModel> {
    return $Call.ByID(3264818422, modelPath, subPath);
}

export function AnalyzeYSMModel(path: string): $CancellablePromise<ysm$0.YSMModelMeta> {
    return $Call.ByID(87919393, path);
}

export function BackupWorkshopCreators(): $CancellablePromise<string> {
    return $Call.ByID(3964989829);
}

/**
 * BatchExtractCreatorAvatars 批量提取所有有本地模型的创作者头像
 */
export function BatchExtractCreatorAvatars(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2317353684);
}

/**
 * Build3DSpecFromGeometryJSON 从 bedrock geometry JSON 构建 3D spec（纯 Go，无 Node 依赖）。
 * 用途：Android 上 Go 端无 .ysm 解码通道（Node WASM 不可用，runYSMNodeJSDecode 恒 nil）时，
 * 前端用 WebView 内 WASM 解码 .ysm 拿到 geometry JSON，再调本函数构建 spec——
 * 复用 threejs.BuildMulti 全量顶点算法（ADR-004：Go 绑定为唯一事实来源），桌面端主路径不变。
 * 返回 "{}" 表示不可用（前端据此决定是否报错/提示）。
 */
export function Build3DSpecFromGeometryJSON(geometryJSON: string): $CancellablePromise<string> {
    return $Call.ByID(2035968503, geometryJSON);
}

/**
 * CacheModelAvatars 从模型文件缓存作者头像（覆盖 .ysm/.zip/.json 等所有格式）
 */
export function CacheModelAvatars(modelPath: string): $CancellablePromise<void> {
    return $Call.ByID(3423756102, modelPath);
}

/**
 * CachedCreatorAvatar 检查缓存中是否有作者头像，返回 data URI
 */
export function CachedCreatorAvatar(authorName: string): $CancellablePromise<string> {
    return $Call.ByID(224206566, authorName);
}

export function CancelQueue(): $CancellablePromise<void> {
    return $Call.ByID(1786226156);
}

export function CheckFileExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(467508719, path);
}

export function CheckUpdate(): $CancellablePromise<updater$0.UpdateInfo | null> {
    return $Call.ByID(651964520);
}

export function ClearCustomDir(customDir: string): $CancellablePromise<number> {
    return $Call.ByID(2697468754, customDir);
}

export function ClearImportLogs(): $CancellablePromise<void> {
    return $Call.ByID(3815103174);
}

/**
 * ClearInstanceResources 清空指定整合包中已同步的文件
 * insName: 整合包名, rtype: 资源类型（空=全部, 非空=只清此类型）
 * 返回清除的文件数量。整合包文件是仓库的副本/链接，删除后可从仓库重新推送恢复；
 * 实例文件在仓库根内才移回收站，其余直接删除（见 clearInstanceDir）
 */
export function ClearInstanceResources(insName: string, rtype: string): $CancellablePromise<number> {
    return $Call.ByID(310409492, insName, rtype);
}

/**
 * ClearRuntimeLogs 清空运行时日志缓冲
 */
export function ClearRuntimeLogs(): $CancellablePromise<void> {
    return $Call.ByID(232184103);
}

/**
 * ClearScanCache 清除扫描缓存（下载/导入后调用）
 */
export function ClearScanCache(): $CancellablePromise<void> {
    return $Call.ByID(3066626705);
}

/**
 * ClearTextureCache 清空纹理缓存（用户主动清理用）。
 */
export function ClearTextureCache(): $CancellablePromise<void> {
    return $Call.ByID(2838206023);
}

export function ClosePlazaWindow(): $CancellablePromise<void> {
    return $Call.ByID(891522693);
}

/**
 * CopyModelFile 复制（同 MoveModelFile 修复：findMoveRoot 多根校验，fail-closed）
 */
export function CopyModelFile(src: string, dstDir: string): $CancellablePromise<void> {
    return $Call.ByID(2849400957, src, dstDir);
}

/**
 * CountDuplicateFiles 快速统计重复文件数量。
 * 契约（见 docs/wails-bindings.md）：成功 → {groups, extra}；失败 → {error: string}。
 */
export function CountDuplicateFiles(dir: string): $CancellablePromise<string> {
    return $Call.ByID(2412651574, dir);
}

/**
 * CountInstanceResources 统计指定整合包中可清空的资源文件数
 * 只统计仓库中已有的文件（同 clearInstanceDir 逻辑）
 * rtype 为空时统计全部类型，否则只统计指定类型
 */
export function CountInstanceResources(insName: string, rtype: string): $CancellablePromise<number> {
    return $Call.ByID(136508414, insName, rtype);
}

/**
 * ========== 目录操作 ==========
 */
export function CreateDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(14567662, dir);
}

export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(2861439428);
}

/**
 * DebugExtractCreatorAvatar 调试版：提取指定作者头像
 */
export function DebugExtractCreatorAvatar(authorName: string): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1802835376, authorName);
}

/**
 * DeduplicateCustomDir 按 SHA256 哈希去重（执行逻辑下沉 go/recycle）
 */
export function DeduplicateCustomDir(customDir: string): $CancellablePromise<[number, number]> {
    return $Call.ByID(2166378965, customDir);
}

export function DefaultWorkshopSites(): $CancellablePromise<types$0.WorkshopSite[] | null> {
    return $Call.ByID(3846649579);
}

export function DeleteFromRecycle(src: string): $CancellablePromise<void> {
    return $Call.ByID(2594824985, src);
}

/**
 * DeleteResourcePack 删除资源（目录感知，ADR-038 D3.6）：
 * 统一入口——根据 rtype.isDir 决定语义：
 * 
 * 	isDir=true:  删除文件所在父文件夹（MMD/EntityPlayer 等目录型资源）
 * 	isDir=false: src 为 ysm.json 时整组删除父目录，否则删除单文件（ysm 等）
 * 
 * 守卫根传类型特定仓库根：防根级 ysm.json 清空整个仓库；
 * 路径守卫拒绝 rel=="." 或 rel 含 ".." 前缀的越权路径。
 */
export function DeleteResourcePack(path: string, rtype: string): $CancellablePromise<void> {
    return $Call.ByID(395621705, path, rtype);
}

/**
 * DetectConflicts 检测指定整合包与全局仓库之间的文件冲突
 * rtype: 资源类型 ID
 * instanceName: 整合包名称
 * 返回冲突报告 JSON
 */
export function DetectConflicts(rtype: string, instanceName: string): $CancellablePromise<string> {
    return $Call.ByID(2472631939, rtype, instanceName);
}

/**
 * DetectLaunchers inspects a selected directory, or a small set of known
 * Minecraft locations when root is empty. Discovery is deliberately bounded:
 * it never walks an entire drive and it never writes launcher files.
 */
export function DetectLaunchers(root: string): $CancellablePromise<types$0.LauncherInfo[] | null> {
    return $Call.ByID(88398009, root);
}

/**
 * DetectResourceType 检测指定文件的资源类型
 */
export function DetectResourceType(path: string): $CancellablePromise<string> {
    return $Call.ByID(2113518140, path);
}

/**
 * DetectZipType 通过 ZIP 内容检测资源类型（供前端导入路由使用）
 */
export function DetectZipType(base64Data: string): $CancellablePromise<string> {
    return $Call.ByID(747133431, base64Data);
}

export function DoUpdate(url: string, expectedHash: string): $CancellablePromise<string> {
    return $Call.ByID(985752667, url, expectedHash);
}

export function DownloadFromGitHub(rawURL: string, saveDir: string): $CancellablePromise<string> {
    return $Call.ByID(960385788, rawURL, saveDir);
}

/**
 * EmptyRecycleBin 清空所有已配置资源根目录的回收站，返回删除条目总数。
 * src 参数保留以兼容既有前端绑定契约（批次4 P2 参数命名）：历史遗留占位，
 * 实际清空全部回收站而非按单目录，Go 端不消费该值。
 */
export function EmptyRecycleBin(src: string): $CancellablePromise<number> {
    return $Call.ByID(4211256250, src);
}

export function EnqueueDownloads(tasks: $models.DownloadTask[] | null): $CancellablePromise<void> {
    return $Call.ByID(552244624, tasks);
}

/**
 * EnsureStorageDirs 预创建所有注册资源类型的存储子目录
 * （FilesRoot/{group}/{storageSubDir}，或各类型专属覆写路径）。
 * 修复惰性创建的体感问题：用户指定仓库根路径后期望整棵类型树立即出现在磁盘，
 * 而非等到首次导入某类型才逐个 MkdirAll。
 * 仅当 GetRepoRoot 返回非空路径才建——空串（未配置/平台默认不可达）跳过，
 * 避免在工作目录裸建；已存在目录为 MkdirAll no-op，幂等安全。
 */
export function EnsureStorageDirs(): $CancellablePromise<void> {
    return $Call.ByID(3449365602);
}

/**
 * ExecuteCLI 执行 CLI 命令并返回 JSON 响应（Wails 绑定）
 */
export function ExecuteCLI(command: string, args: { [_ in string]?: any } | null): $CancellablePromise<string> {
    return $Call.ByID(302310740, command, args);
}

/**
 * ========== 导出单模型骨骼结构 ==========
 * ExportModelStructureJSON 导出单模型骨骼结构
 */
export function ExportModelStructureJSON(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(2285469521, modelPath);
}

export function ExportWorkshopCreatorsJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(3313564853);
}

/**
 * ========== CSV 导出/导入 ==========
 */
export function ExportWorkshopSitesCSV(): $CancellablePromise<string> {
    return $Call.ByID(2284407588);
}

export function ExportWorkshopSitesJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(3241109304);
}

export function ExtractPreviewTexture(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(4136663739, modelPath);
}

export function ExtractYSMHeader(path: string): $CancellablePromise<ysm$0.YSMHeader> {
    return $Call.ByID(3464271858, path);
}

export function ExtractYSMHeaderFromBase64(base64Data: string): $CancellablePromise<ysm$0.YSMHeader> {
    return $Call.ByID(547420281, base64Data);
}

export function ExtractYsmSummary(path: string): $CancellablePromise<ysm$0.YsmSummary> {
    return $Call.ByID(847066301, path);
}

/**
 * FindDuplicateFiles 扫描目录返回所有重复文件分组（JSON 字符串）。
 * 契约（见 docs/wails-bindings.md）：成功 → DedupGroup[]；失败 → {error: string}。
 * configStr: 可选的去重配置 JSON 字符串，格式: {"strategy":"...", "keepPolicy":"...", "priorityPath":"..."}
 */
export function FindDuplicateFiles(dir: string, ...configStr: string[]): $CancellablePromise<string> {
    return $Call.ByID(1295941240, dir, configStr);
}

/**
 * ========== 预览提取 ==========
 */
export function FindPreviewImage(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(528549045, modelPath);
}

/**
 * GenerateRepoIndex 生成 index.json（含 GitHub Actions workflow 模板）
 */
export function GenerateRepoIndex(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(1563740856, repoPath);
}

/**
 * GetAllRepoRoots 遍历所有注册资源类型，返回 rtype → root 映射（供跨类型搜索）。
 * 仅返回目录真实存在且可访问的类型；空 root/不存在的目录跳过。
 */
export function GetAllRepoRoots(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(454948853);
}

/**
 * GetAllowedCLICommands 返回可用 CLI 命令列表
 * 列表由 main.go 从 cli 注册表注入（SetAllowedCommands），新增命令自动可见
 */
export function GetAllowedCLICommands(): $CancellablePromise<string> {
    return $Call.ByID(4049775249);
}

/**
 * GetAppVersion 返回当前版本号
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(115297084);
}

/**
 * GetCachedTexture 读取纹理文件，计算内容哈希，检查 KTX2 缓存。
 * 缓存命中时 Format="ktx2" Data=KTX2 base64；未命中时 Format="png" Data=PNG base64。
 * 前端可根据 Format 决定使用 KTX2Loader 还是 TextureLoader。
 */
export function GetCachedTexture(path: string): $CancellablePromise<$models.CachedTextureResult> {
    return $Call.ByID(3613359678, path);
}

/**
 * GetCachedTextureByHash 通过哈希直接读取 KTX2 缓存（不读取原始文件，轻量操作）。
 * hash 由前端从已读纹理数据计算 SHA256 得到。
 * 返回 base64 编码的 KTX2 数据；缓存未命中时返回空字符串。
 */
export function GetCachedTextureByHash(hash: string): $CancellablePromise<string> {
    return $Call.ByID(79095655, hash);
}

/**
 * GetConfigPath 返回应用配置文件路径（跨平台：Windows %APPDATA%，Linux ~/.config，macOS ~/Library/Application Support）
 * 供前端 UI 展示，避免硬编码 Windows 路径
 */
export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(3095584372);
}

/**
 * GetDefaultRepoRoot 返回平台默认公共仓库根目录（不含类型子目录）。
 * Android：固定公共路径（如 /storage/emulated/0/YSM-Model-Manager，授权
 * MANAGE_EXTERNAL_STORAGE 后直读，查看器模式）；desktop：空串。
 * 供前端 Android 分支「自动定位公共目录」使用（ADR-046 P2）。
 * 会尝试 MkdirAll 创建目录；创建后目录仍不可读（未授权）则返回空串，
 * 避免前端 toast 假成功（review 修复）。
 */
export function GetDefaultRepoRoot(): $CancellablePromise<string> {
    return $Call.ByID(2892280306);
}

export function GetGlobalCustomDir(mcRoot: string): $CancellablePromise<string> {
    return $Call.ByID(4119708496, mcRoot);
}

export function GetImportLogs(): $CancellablePromise<types$0.ImportLog[] | null> {
    return $Call.ByID(1065567147);
}

/**
 * ========== 状态同步 ==========
 * GetInstanceStatus 获取整合包状态（按资源类型限定路径）
 * rtype: 资源类型 ID，用于解析特定子目录；为空时使用 ins.CustomDir（向后兼容）
 */
export function GetInstanceStatus(mcRoot: string, repoDir: string, rtype: string): $CancellablePromise<types$0.InstanceStatus[] | null> {
    return $Call.ByID(4224028016, mcRoot, repoDir, rtype);
}

/**
 * GetInstanceSyncStatus 获取整合包下所有资源类型的同步状态（扁平列表）
 * subtype 可选，指定子类型目录名（如 EntityPlayer），仅 subDirGrouping 类型有效——路径限定。
 * GetInstanceSyncStatus 整合包同步状态（组装逻辑已下沉 go/instance，此处仅注入依赖）
 */
export function GetInstanceSyncStatus(instanceName: string, subtype: string): $CancellablePromise<string> {
    return $Call.ByID(839308247, instanceName, subtype);
}

export function GetLinkMode(): $CancellablePromise<string> {
    return $Call.ByID(736604018);
}

/**
 * GetLitematicVoxelData 读取投影文件体素数据（按颜色分组的方块位置）
 */
export function GetLitematicVoxelData(path: string): $CancellablePromise<string> {
    return $Call.ByID(2172897631, path);
}

export function GetMinecraftPaths(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2122198272);
}

export function GetModel3DSpec(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(2923299250, modelPath);
}

/**
 * GetModelTags 返回指定模型文件的所有标签
 */
export function GetModelTags(modelPath: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(234236959, modelPath);
}

/**
 * GetModelTexSizes 扫描仓库文件提取纹理尺寸（轻量级，不解析完整模型）
 */
export function GetModelTexSizes(filesRoot: string): $CancellablePromise<ysm$0.TexInfo[] | null> {
    return $Call.ByID(1273620259, filesRoot);
}

/**
 * GetNbtVoxelData 读取 .nbt 结构文件体素数据
 */
export function GetNbtVoxelData(path: string): $CancellablePromise<string> {
    return $Call.ByID(2164005593, path);
}

/**
 * ========== 包信息 ==========
 */
export function GetPackInfo(dirPath: string): $CancellablePromise<types$0.PackInfo> {
    return $Call.ByID(2243407216, dirPath);
}

/**
 * GetRepoRoot 根据资源类型返回对应的仓库根目录
 */
export function GetRepoRoot(rtype: string): $CancellablePromise<string> {
    return $Call.ByID(4011191521, rtype);
}

/**
 * GetResourceInstanceStatus 按资源类型获取整合包同步状态
 * 统一走 GetInstanceStatus 路径，通过 rtype 限定实例侧扫描子目录 + 仓库侧扩展名过滤
 */
export function GetResourceInstanceStatus(rtype: string, mcRoot: string, repoDir: string): $CancellablePromise<types$0.InstanceStatus[] | null> {
    return $Call.ByID(779607888, rtype, mcRoot, repoDir);
}

/**
 * GetRuntimeLogs 获取运行时日志（watcher/sync 等标准库 log 输出）
 */
export function GetRuntimeLogs(): $CancellablePromise<types$0.RuntimeLog[] | null> {
    return $Call.ByID(3524121676);
}

/**
 * GetSchematicVoxelData 读取 .schematic 文件体素数据
 */
export function GetSchematicVoxelData(path: string): $CancellablePromise<string> {
    return $Call.ByID(199377974, path);
}

/**
 * ========== 自动更新 ==========
 * GetSubDirMap 返回资源类型→子目录映射表（前端右键菜单等场景使用）
 */
export function GetSubDirMap(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2085433910);
}

/**
 * GetWasmBinary 返回内嵌的 YSMParser.wasm 字节（供前端 WebView2 使用）。
 * wasmBinary 由根包 main 的 init() 经 SetEmbedded 注入。
 */
export function GetWasmBinary(): $CancellablePromise<string | null> {
    return $Call.ByID(2670724632);
}

export function GetWindowPosition(): $CancellablePromise<types$0.WindowState> {
    return $Call.ByID(3862857718);
}

/**
 * GetYSMRepoRoot 返回当前配置的 YSM 仓库根目录
 */
export function GetYSMRepoRoot(): $CancellablePromise<string> {
    return $Call.ByID(2204623080);
}

/**
 * HasCachedTexture 检查指定纹理的内容哈希是否已有 KTX2 缓存。
 */
export function HasCachedTexture(hash: string): $CancellablePromise<boolean> {
    return $Call.ByID(337849218, hash);
}

/**
 * HasCachedTextures 批量检查多个哈希是否已有 KTX2 缓存。
 * 一次 RPC 返回所有检查结果，map[hash] → 是否存在。
 */
export function HasCachedTextures(hashes: string[] | null): $CancellablePromise<{ [_ in string]?: boolean } | null> {
    return $Call.ByID(2757635171, hashes);
}

/**
 * ========== YSM 检测 ==========
 */
export function HasYSMMod(modsDir: string): $CancellablePromise<boolean> {
    return $Call.ByID(1327539980, modsDir);
}

/**
 * ImportByType 统一导入入口——根据资源类型自动选择导入策略
 */
export function ImportByType(rtype: string, srcPath: string): $CancellablePromise<string> {
    return $Call.ByID(1466768695, rtype, srcPath);
}

export function ImportModelFile(fileName: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(2135926573, fileName, base64Data);
}

export function ImportModelFileOverwrite(fileName: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(2920266218, fileName, base64Data);
}

export function ImportModelFileOverwriteTo(fileName: string, subpath: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(3849603631, fileName, subpath, base64Data);
}

/**
 * ImportModelFileOverwriteToMMD 覆盖导入 MMD 模型文件到指定用途子目录。
 */
export function ImportModelFileOverwriteToMMD(fileName: string, subpath: string, mmdSubdir: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(445496335, fileName, subpath, mmdSubdir, base64Data);
}

export function ImportModelFileSkipCheck(fileName: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(334185050, fileName, base64Data);
}

export function ImportModelFileTo(fileName: string, subpath: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(191674492, fileName, subpath, base64Data);
}

/**
 * ImportModelFileToMMD 导入 MMD 模型文件到指定用途子目录（ADR-096）。
 * mmdSubdir: MMD 用途子目录名（如 SceneModel/CustomAnim），对应 MMD 独立顶级类型。
 * subpath: 文件在子目录内的相对路径（文件夹导入时保留层级）。
 */
export function ImportModelFileToMMD(fileName: string, subpath: string, mmdSubdir: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(509903146, fileName, subpath, mmdSubdir, base64Data);
}

/**
 * ImportModelFolder 文件夹型模型整组导入（YSM 解压目录 / MMD 模型目录，保留子目录层级，ADR-038 关联）
 * folderName = 仓库文件夹名（模型名）；files = 相对路径 → base64 内容
 * rtype 按文件夹内容推断（非硬编码 ysm）：扫主文件扩展名经 ExtBelongsTo 判定，
 * 使 MMD 文件夹落到 EntityPlayer 根而非 ysm 根（ADR-092 子类型落位根基）。
 */
export function ImportModelFolder(folderName: string, subpath: string, files: types$0.ImportFileItem[] | null): $CancellablePromise<void> {
    return $Call.ByID(100876983, folderName, subpath, files);
}

/**
 * ImportModelFolderTo 带页面上下文类型的文件夹整组导入（拖拽导入上下文路由）。
 * rtype 来自前端当前树的根属性——树根本就派生自注册表路由配置，前端只透传不判型；
 * 上下文优先：注册表校验通过即按该类型仓库根落盘，解决 .zip 多类型歧义文件夹
 * 被内容推断兜底进 ysm 根的结构性失灵（maid-model 等仅注册 .zip 的类型永不可达）。
 * 空串/未注册类型回退 inferFolderType 内容推断（兼容导入页等无上下文入口）。
 * 提醒非阻断：内容明确归属其他单一类型且与上下文不符时记一条 warn 日志，
 * 落盘仍按上下文执行——用户拖到哪页就落哪页的根。
 * 例外（审核 P3-4）：上下文为默认中性类型时让位内容推断、整条走 ImportModelFolder
 * 旧路（含 ysm.json 入口优先级与兜底），最常用入口不静默改数据落点。
 */
export function ImportModelFolderTo(folderName: string, subpath: string, rtype: string, files: types$0.ImportFileItem[] | null): $CancellablePromise<void> {
    return $Call.ByID(435971586, folderName, subpath, rtype, files);
}

/**
 * ImportResourcePack 使用策略模式导入资源包
 */
export function ImportResourcePack(srcPath: string, rtype: string): $CancellablePromise<string> {
    return $Call.ByID(2578913479, srcPath, rtype);
}

export function ImportWorkshopSitesCSV(csvContent: string): $CancellablePromise<void> {
    return $Call.ByID(1342547047, csvContent);
}

/**
 * ========== 安装 ==========
 */
export function InstallModelFile(src: string, mcRoot: string): $CancellablePromise<string> {
    return $Call.ByID(2558470757, src, mcRoot);
}

export function InstallModelTo(src: string, customDir: string): $CancellablePromise<void> {
    return $Call.ByID(547256422, src, customDir);
}

export function InstallModelWithOverlay(src: string, customDir: string): $CancellablePromise<string> {
    return $Call.ByID(4168467473, src, customDir);
}

/**
 * InstallResourceToInstance 将资源文件安装到指定整合包
 * rtype: 资源类型（resourcepack/shaderpack 等），srcPath: 源文件路径，instanceName: 整合包名称
 */
export function InstallResourceToInstance(rtype: string, srcPath: string, instanceName: string): $CancellablePromise<void> {
    return $Call.ByID(215553224, rtype, srcPath, instanceName);
}

/**
 * InvalidateScanCache 清空扫描缓存，下次扫描获取最新数据（委托 ClearScanCache）
 */
export function InvalidateScanCache(): $CancellablePromise<void> {
    return $Call.ByID(2605564787);
}

export function IsFileBanned(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3330292233, path);
}

/**
 * IsResourcePackEnabled 检查资源包是否启用
 */
export function IsResourcePackEnabled(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2413288079, path);
}

/**
 * ListAllFilePaths 递归列出指定目录下的所有文件完整路径（不限制扩展名）
 */
export function ListAllFilePaths(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(504456952, dir);
}

/**
 * ListByTag 返回所有打了指定标签的文件路径列表
 */
export function ListByTag(tag: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(543634162, tag);
}

export function ListFileNames(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(223101035, dir);
}

/**
 * ListModelAuthors 统计 [作者] 前缀（走扫描缓存，不重复读磁盘）
 */
export function ListModelAuthors(): $CancellablePromise<types$0.AuthorInfo[] | null> {
    return $Call.ByID(2783678748);
}

/**
 * ListPackModels 枚举资源包容器内的 block/item 模型 JSON 条目路径（升序）。
 * 失败或无模型返回 "[]"（前端据此回退缩略图通道）。
 */
export function ListPackModels(path: string): $CancellablePromise<string> {
    return $Call.ByID(426377372, path);
}

export function ListRecycleBin(recyclePath: string): $CancellablePromise<types$0.ModelEntry[] | null> {
    return $Call.ByID(3420025601, recyclePath);
}

export function ListVersionInstances(mcRoot: string): $CancellablePromise<types$0.VersionInstance[] | null> {
    return $Call.ByID(2348617735, mcRoot);
}

export function LoadAppConfig(): $CancellablePromise<types$0.AppConfig> {
    return $Call.ByID(4081731812);
}

export function LoadGitHubRepos(): $CancellablePromise<types$0.WorkshopCreator[] | null> {
    return $Call.ByID(555735249);
}

/**
 * LoadResourceTypes 加载资源类型注册表
 */
export function LoadResourceTypes(): $CancellablePromise<string> {
    return $Call.ByID(3636552016);
}

export function LoadWorkshopCreators(): $CancellablePromise<types$0.WorkshopCreator[] | null> {
    return $Call.ByID(3429491443);
}

export function MergeWorkshopCreatorsFromJSON(jsonContent: string): $CancellablePromise<[number, number]> {
    return $Call.ByID(2866539347, jsonContent);
}

/**
 * MoveModelFile 移动（findMoveRoot 遍历所有已配置根做路径安全校验，
 * 修复原硬编码 cfg.FilesRoot 导致自定义根下文件无法移动的 bug。
 * fail-closed：无匹配根时拒绝，不向 fileops 传空 root 跳过校验）
 */
export function MoveModelFile(src: string, dstDir: string): $CancellablePromise<void> {
    return $Call.ByID(1018628389, src, dstDir);
}

/**
 * ========== 回收站 ==========
 */
export function MoveToRecycle(src: string): $CancellablePromise<void> {
    return $Call.ByID(1383304780, src);
}

export function MoveToRecycleEx(src: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(2099759785, src);
}

export function NavigatePlazaWindow(url: string, direct: boolean): $CancellablePromise<void> {
    return $Call.ByID(424032226, url, direct);
}

export function OpenFolder(dir: string): $CancellablePromise<void> {
    return $Call.ByID(4260431887, dir);
}

/**
 * OpenInBrowser 在系统默认浏览器中打开链接（而非 WebView2 内嵌）
 */
export function OpenInBrowser(url: string): $CancellablePromise<void> {
    return $Call.ByID(3205913216, url);
}

/**
 * OpenInstanceFolder 按资源类型打开整合包内资源存储目录
 * 
 * 扁平化架构下，统一使用 instanceDir（如 EntityPlayer、config/yes_steve_model/custom）
 * 拼 instDir/instanceDir 作为打开目标；目录不存在也不回退（用户手动放错位置由他负责）。
 * 
 * subdir 参数：保留签名为 Wails 绑定兼容，已不参与路由。
 */
export function OpenInstanceFolder(instDir: string, rtype: string, subdir: string): $CancellablePromise<void> {
    return $Call.ByID(2384592956, instDir, rtype, subdir);
}

export function PlazaGoBack(): $CancellablePromise<void> {
    return $Call.ByID(45748458);
}

export function PlazaGoForward(): $CancellablePromise<void> {
    return $Call.ByID(3547542930);
}

export function PlazaReload(): $CancellablePromise<void> {
    return $Call.ByID(1284133918);
}

export function PlazaZoomIn(): $CancellablePromise<void> {
    return $Call.ByID(63364583);
}

export function PlazaZoomOut(): $CancellablePromise<void> {
    return $Call.ByID(209278668);
}

export function PlazaZoomReset(): $CancellablePromise<void> {
    return $Call.ByID(4082864247);
}

/**
 * PullResourceFromInstance 拉取整合包多余资源回仓库（执行循环下沉 go/sync）
 */
export function PullResourceFromInstance(rtype: string, instanceName: string): $CancellablePromise<number> {
    return $Call.ByID(3336031775, rtype, instanceName);
}

/**
 * PullSingleResourceFromInstance 从整合包拉取单个 extra 文件/文件夹到全局仓库
 * PullSingleResourceFromInstance 从整合包拉取单个资源（复制核心下沉 go/sync）
 */
export function PullSingleResourceFromInstance(rtype: string, srcPath: string, instanceName: string): $CancellablePromise<void> {
    return $Call.ByID(2266526243, rtype, srcPath, instanceName);
}

/**
 * PushResourceToInstance 将全局中缺失的资源推送到整合包
 * PushResourceToInstance 推送缺失资源到整合包（执行循环下沉 go/sync）
 */
export function PushResourceToInstance(rtype: string, instanceName: string): $CancellablePromise<number> {
    return $Call.ByID(3583202917, rtype, instanceName);
}

/**
 * PushSingleResourceToInstance 推送单个资源到整合包（分派核心下沉 go/sync）
 */
export function PushSingleResourceToInstance(rtype: string, instanceName: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(3553253805, rtype, instanceName, filePath);
}

export function QueueStatus(): $CancellablePromise<$models.QueueStatusInfo> {
    return $Call.ByID(1350901616);
}

export function ReadFileBytes(path: string): $CancellablePromise<string | null> {
    return $Call.ByID(2124137540, path);
}

/**
 * ReadFileBytesBatch 批量读取多个文件（ADR-101：MMD 纹理加载优化）。
 * 一次 RPC 返回多个文件字节，减少 Go↔JS IPC 往返（原 N 次 readFileBytes → 1 次 batch）。
 * 路径守卫：逐个校验 isPathInRootOrSelf，非法路径跳过（值为 nil）。
 * 返回 map[路径] → base64 字节（Wails []byte 自动序列化为 base64，map 保持键序）。
 * 
 * 并发优化：I/O 密集型任务，使用 goroutine 池并行读取。
 * 当 paths 数量 <= 4 时退化为顺序读取（goroutine 开销不划算）。
 */
export function ReadFileBytesBatch(paths: string[] | null): $CancellablePromise<{ [_ in string]?: string | null } | null> {
    return $Call.ByID(1632485740, paths);
}

/**
 * ReadFileBytesBatchWithMeta 批量读取文件并返回内容 + SHA256 哈希。
 * 一次 RPC 完成数据读取和 hash 计算，避免前端额外算 hash 或二次 RPC。
 * 路径守卫和行为与 ReadFileBytesBatch 一致。
 */
export function ReadFileBytesBatchWithMeta(paths: string[] | null): $CancellablePromise<{ [_ in string]?: $models.ReadFileMeta } | null> {
    return $Call.ByID(919610209, paths);
}

/**
 * ReadLitematicMeta 读取投影文件元数据（作者/时间/版本/方块统计/预览图）
 */
export function ReadLitematicMeta(path: string): $CancellablePromise<string> {
    return $Call.ByID(3216421386, path);
}

/**
 * ReadNbtStructure 读取 .nbt 结构文件基本信息
 */
export function ReadNbtStructure(path: string): $CancellablePromise<string> {
    return $Call.ByID(304829738, path);
}

/**
 * ReadPackEntry 读取容器内条目内容（base64 字符串）。
 * entry 非法/缺失/超限返回空串（前端渲染兜底跳过）。
 */
export function ReadPackEntry(path: string, entry: string): $CancellablePromise<string> {
    return $Call.ByID(1997958062, path, entry);
}

/**
 * ReadPackMeta 读取资源包信息（pack.mcmeta + pack.png）
 */
export function ReadPackMeta(path: string): $CancellablePromise<string> {
    return $Call.ByID(1762327275, path);
}

/**
 * ReadSchematic 读取 .schematic 文件基本信息
 */
export function ReadSchematic(path: string): $CancellablePromise<string> {
    return $Call.ByID(2285677248, path);
}

/**
 * ReadShaderpackLang 读取光影包 lang/en_US.lang 提取显示名
 */
export function ReadShaderpackLang(path: string): $CancellablePromise<string> {
    return $Call.ByID(3411986111, path);
}

/**
 * RelinkAllInstanceResources 重新应用链接模式到整合包所有资源类型目录
 */
export function RelinkAllInstanceResources(instanceName: string): $CancellablePromise<number> {
    return $Call.ByID(3612469403, instanceName);
}

/**
 * RelinkCustomDir 重新应用链接模式到指定目录（兼容旧版）
 */
export function RelinkCustomDir(customDir: string, filesRoot: string): $CancellablePromise<number> {
    return $Call.ByID(3736551740, customDir, filesRoot);
}

export function RemoveDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2521913290, dir);
}

export function RenameDir(oldPath: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1511264492, oldPath, newName);
}

export function RenameFile(oldPath: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1176761595, oldPath, newName);
}

export function ReplaceWorkshopCreatorsFromJSON(jsonContent: string): $CancellablePromise<number> {
    return $Call.ByID(1355854287, jsonContent);
}

/**
 * RepoHealthAudit 一键全仓体检（审计 + 去重），返回 JSON 字符串。
 * 契约（与 FindDuplicateFiles 同模式）：成功 → repoaudit.HealthReport；失败 → {error: string}。
 * 与 CLI health-report 同源（go/repoaudit 唯一实现），GUI/CLI 双端消双轨。
 */
export function RepoHealthAudit(dir: string): $CancellablePromise<string> {
    return $Call.ByID(3995157004, dir);
}

/**
 * RepoHealthAuditAll 全仓库体检：遍历所有已配置资源类型根目录，合并审计结果。
 * 无有效目录时返回错误提示（与 RepoHealthAudit 同源格式）。
 */
export function RepoHealthAuditAll(): $CancellablePromise<string> {
    return $Call.ByID(2158058199);
}

/**
 * ResetResourceRoot 恢复指定资源类型的路径为默认（清空自定义值）
 */
export function ResetResourceRoot(rtype: string): $CancellablePromise<void> {
    return $Call.ByID(3252835018, rtype);
}

export function ResetWorkshopConfigs(): $CancellablePromise<types$0.WorkshopSite[] | null> {
    return $Call.ByID(2959472146);
}

/**
 * ResolveConflicts 批量解决冲突
 * conflictsJSON: 冲突列表 JSON（来自 DetectConflicts）
 * defaultStrategy: 默认解决策略 (force_remote/force_local/manual)
 * rtype: 资源类型 ID
 * instanceName: 整合包名称
 * 返回解决结果 JSON
 */
export function ResolveConflicts(conflictsJSON: string, defaultStrategy: string, rtype: string, instanceName: string): $CancellablePromise<string> {
    return $Call.ByID(1918295312, conflictsJSON, defaultStrategy, rtype, instanceName);
}

export function RestartApplication(): $CancellablePromise<void> {
    return $Call.ByID(143393668);
}

export function RestoreFromRecycle(src: string, filesRoot: string): $CancellablePromise<void> {
    return $Call.ByID(983517996, src, filesRoot);
}

/**
 * ========== 在资源管理器中显示 ==========
 */
export function RevealInExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(3185410442, path);
}

export function SaveAppConfig(filesRoot: string, rpRoot: string, mcRoot: string, linkMode: string, theme: string): $CancellablePromise<void> {
    return $Call.ByID(3201182099, filesRoot, rpRoot, mcRoot, linkMode, theme);
}

/**
 * SaveCachedTexture 保存前端 WASM 编码后的 KTX2 数据到缓存。
 * hash 是 GetCachedTexture 返回的 Hash 值，data 是 KTX2 字节的 base64。
 */
export function SaveCachedTexture(hash: string, b64Data: string): $CancellablePromise<void> {
    return $Call.ByID(3781776119, hash, b64Data);
}

export function SavePreviewTempFile(base64Data: string): $CancellablePromise<string> {
    return $Call.ByID(3917626618, base64Data);
}

/**
 * SaveScreenshotFile 保存 base64 PNG 到磁盘（供 JS 批量截图用）
 * 路径守卫：限制在 os.TempDir()/ysm-preview 内，禁止绝对路径与路径穿越（.. 段）
 */
export function SaveScreenshotFile(filename: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(1822573792, filename, base64Data);
}

/**
 * SaveThresholds 保存运行阈值配置（ADR-062 §2.3：前端设置页写入入口）。
 * 仅更新传入的阈值字段，其余字段从旧配置保留（与 SaveAppConfig 的 orDefault 语义一致）。
 * checkIntervalMs / logMaxEntries 传 0 = 重置为各包默认常量（scanner/logs 读取 0=默认）。
 */
export function SaveThresholds(checkIntervalMs: number, logMaxEntries: number): $CancellablePromise<void> {
    return $Call.ByID(2817934378, checkIntervalMs, logMaxEntries);
}

export function SaveWindowPosition(x: number, y: number, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(469886297, x, y, width, height);
}

export function SaveWorkshopCreators(list: types$0.WorkshopCreator[] | null): $CancellablePromise<void> {
    return $Call.ByID(2516832214, list);
}

/**
 * SaveWorkshopCreatorsBySite 只替换指定站点的创作者，其他站点不动
 */
export function SaveWorkshopCreatorsBySite(siteID: string, siteCreators: types$0.WorkshopCreator[] | null): $CancellablePromise<void> {
    return $Call.ByID(3867129300, siteID, siteCreators);
}

/**
 * SaveWorkshopPresetsBySite 只替换指定站点的搜索词，其他站点不动
 */
export function SaveWorkshopPresetsBySite(siteID: string, presets: types$0.WorkshopPresetSearch[] | null): $CancellablePromise<void> {
    return $Call.ByID(4066089783, siteID, presets);
}

export function SaveWorkshopSites(sites: types$0.WorkshopSite[] | null): $CancellablePromise<void> {
    return $Call.ByID(2656683497, sites);
}

/**
 * ScanLocalAuthors 扫描所有本地资源目录，从文件名提取作者
 */
export function ScanLocalAuthors(): $CancellablePromise<types$0.WorkshopCreator[] | null> {
    return $Call.ByID(3176279871);
}

/**
 * ScanModelEntries 用户可见的扫描入口（Wails 绑定），记录操作日志。
 * 仅在真正扫盘（缓存未命中）时记日志，30s 内重复访问命中缓存则跳过，避免刷屏。
 */
export function ScanModelEntries(dir: string): $CancellablePromise<types$0.ModelEntry[] | null> {
    return $Call.ByID(963930825, dir);
}

/**
 * ScanModelEntriesFiltered 同 ScanModelEntriesWithLabel，但额外按 rtype（+可选 subtype）的 extensions
 * 注册表做类型特定扩展名过滤。前端预览菜单切换模型场景用——EntityPlayer 类型需排除
 * .vmd/.vpd 动作文件，仅保留 .pmx/.pmd/.zip 模型/容器文件。
 * 
 * subtype 参数：按子类型隔离扩展名（如 EntityPlayer → 只有 .pmx/.pmd/.zip，不含 .vmd/.vpd）。
 * subtype 为空时回退到父类型扩展名（壳类型场景）。
 * 过滤逻辑：取 types.SupportedExtsForSubtype(rtype, subtype) 白名单，扩展名不匹配的条目直接丢弃。
 * rtype 为空或注册表无匹配时退化为 ScanModelEntriesWithLabel 行为（不过滤）。
 * 路径守卫与 ScanModelEntries/ScanModelEntriesWithLabel 完全一致。
 */
export function ScanModelEntriesFiltered(dir: string, rtype: string, subtype: string, label: string): $CancellablePromise<types$0.ModelEntry[] | null> {
    return $Call.ByID(1678370138, dir, rtype, subtype, label);
}

/**
 * ScanModelEntriesWithLabel 同 ScanModelEntries，但操作日志附带资源类型标签
 * （如「资源包」「光影包」「模型」），便于在操作日志面板区分扫描的文件类型。
 * 仅在缓存未命中时记日志，避免刷屏。
 * 与 ScanModelEntries 共用同一路径守卫——原实现无守卫，
 * 前端主扫描入口（loader.ts/app-content/community.ts 等）可传 `..`/盘符根越权遍历，
 * 且与 ScanModelEntries 行为不一致（ADR-044③ 路径边界对称范式）。
 */
export function ScanModelEntriesWithLabel(dir: string, label: string): $CancellablePromise<types$0.ModelEntry[] | null> {
    return $Call.ByID(3762097925, dir, label);
}

/**
 * SearchAllModels 跨类型搜索：遍历所有已配置资源类型的根目录，并发扫描 + 合并结果。
 * allRoots 为 rtype→root 映射（由 GetAllRepoRoots 提供）；每个搜索结果携带 Type 字段。
 * 关键词/数值过滤逻辑与 SearchModels 一致，但扫描范围覆盖全部类型。
 */
export function SearchAllModels(allRoots: { [_ in string]?: string } | null, keyword: string, minBones: number, maxBones: number, minCubes: number, maxCubes: number, minTex: number, maxTex: number): $CancellablePromise<types$0.SearchResult[] | null> {
    return $Call.ByID(2041765860, allRoots, keyword, minBones, maxBones, minCubes, maxCubes, minTex, maxTex);
}

/**
 * ========== 高级搜索 ==========
 * SearchModels 扫描模型条目后按关键词、骨骼数、立方体数、纹理尺寸范围过滤。
 * 并发优化：关键词预过滤后，用 goroutine 池并行 AnalyzeBedrockModel（I/O + CPU 混合型）。
 */
export function SearchModels(filesRoot: string, keyword: string, minBones: number, maxBones: number, minCubes: number, maxCubes: number, minTex: number, maxTex: number): $CancellablePromise<types$0.SearchResult[] | null> {
    return $Call.ByID(652244789, filesRoot, keyword, minBones, maxBones, minCubes, maxCubes, minTex, maxTex);
}

/**
 * ========== 目录选择 ==========
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2136780286);
}

/**
 * SelectImportFile 打开文件选择器，按给定扩展名过滤
 * filter 格式: "显示名|*.ext1;*.ext2"
 */
export function SelectImportFile(filter: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(3917673792, filter, title);
}

/**
 * SelectImportZip 打开文件选择器选取 .zip 文件
 */
export function SelectImportZip(): $CancellablePromise<string> {
    return $Call.ByID(3551213909);
}

/**
 * SetAllowedCommands 注入可用 CLI 命令列表（由 main.go 调用 cli.GetAllowedCommands() 提供）
 * 避免 app→cli 循环依赖：命令注册表单一事实来源在 go/cli，前端可见列表经此注入
 */
export function SetAllowedCommands(cmds: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4179505329, cmds);
}

/**
 * SetApp 注入 Wails 3 应用实例，供 service 方法访问窗口/事件/对话框/浏览器管理器
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2864115508, app);
}

export function SetDownloadMirror(mirror: string): $CancellablePromise<void> {
    return $Call.ByID(1760896254, mirror);
}

/**
 * ========== 链接模式 ==========
 */
export function SetLinkMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(2002865150, mode);
}

/**
 * SetMainWindow 注入主窗口实例，避免依赖 Window.Current()。
 * 注意：ServiceStartup 在 app.Run() 早期被调用，此时窗口尚未成为 Current，
 * Window.Current() 会返回 nil 导致空指针；故改用直接持有的窗口引用。
 */
export function SetMainWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(734441964, w);
}

/**
 * SetModelTags 设置指定模型文件的标签列表（覆盖写入）
 */
export function SetModelTags(modelPath: string, tags: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4009573307, modelPath, tags);
}

/**
 * SetResourceRoot 设置指定资源类型的自定义根路径（空=恢复默认）
 * ADR-095：写入 cfg.CustomRoots[rtype]；删除则清空该 key。
 * 不再反射结构体字段，新增资源类型只改 resource_types.json 即可生效。
 */
export function SetResourceRoot(rtype: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3405438717, rtype, path);
}

/**
 * SetVoxelMaxBlocks 设置 3D 体素渲染上限，0=恢复默认 200000
 */
export function SetVoxelMaxBlocks(limit: number): $CancellablePromise<void> {
    return $Call.ByID(1029825393, limit);
}

/**
 * SyncCustomToRepo 同步整合包自定义目录到仓库（执行逻辑下沉 go/sync）
 */
export function SyncCustomToRepo(customDir: string, repoDir: string): $CancellablePromise<number> {
    return $Call.ByID(1317956650, customDir, repoDir);
}

export function SyncModelToggleStatus(instanceCustomDir: string, filesRoot: string): $CancellablePromise<[number, number]> {
    return $Call.ByID(933155543, instanceCustomDir, filesRoot);
}

/**
 * SyncResources 获取全局 ↔ 整合包的资源同步状态
 */
export function SyncResources(rtype: string, instanceName: string): $CancellablePromise<string> {
    return $Call.ByID(2551449925, rtype, instanceName);
}

/**
 * ========== 统一启用/禁用（兄弟会话裁定：无 rtype，纯路径包含判定）==========
 * ToggleEnable 统一启禁入口——root 归属由「哪个已知根包含此路径」判定，而非按
 * rtype 路由：前端零类型信息过桥，杜绝「rtype 与实际位置不一致」（文件移动/复制后
 * rtype 过期）错根；允许集合与 ToggleResourcePack 同口径（FilesRoot + McRoot +
 * CustomRoots 值），内部复用 fileops 的 .disabled 统一机制（新标准，兼容历史 .ban）。
 */
export function ToggleEnable(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(1450559684, path);
}

/**
 * ========== 启用/禁用 ==========
 * ToggleModelEnable 切换 .ban 状态（fileops 纯逻辑 + 薄壳缓存失效）
 */
export function ToggleModelEnable(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3300558263, path);
}

/**
 * ToggleResourcePack 切换资源包的启用/禁用状态（.zip ↔ .zip.disabled）
 * 补路径守卫——原实现 os.Rename 对任意路径可重命名（对齐 ToggleModelEnable 经 fileops
 * 的 ysmRoot 防护；rename 目标派生自输入路径，越权路径会连带生成越权目标）。
 * 额外拒绝 path == 仓库根——IsInside 对「路径等于基准」按设计返回 nil，
 * 传入仓库根时 os.Rename(root, root+".disabled") 会把整个仓库移出配置位置（镜像 DeleteModelDir
 * 的 rel=="." 拒绝同类输入）
 */
export function ToggleResourcePack(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3911031138, path);
}

export function ValidateMinecraftDir(dir: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(2967962547, dir);
}

export function ValidateWorkshopSites(): $CancellablePromise<number> {
    return $Call.ByID(952603376);
}
