// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadTask 下载队列任务
 */
export class DownloadTask {
    /**
     * Creates a new DownloadTask instance.
     * @param {Partial<DownloadTask>} [$$source = {}] - The source object to create the DownloadTask.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("saveDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveDir"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadTask}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadTask(/** @type {Partial<DownloadTask>} */($$parsedSource));
    }
}

/**
 * QueueStatusInfo 队列状态（替代多返回值，Wails 自动映射为 JS object）
 */
export class QueueStatusInfo {
    /**
     * Creates a new QueueStatusInfo instance.
     * @param {Partial<QueueStatusInfo>} [$$source = {}] - The source object to create the QueueStatusInfo.
     */
    constructor($$source = {}) {
        if (!("remaining" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remaining"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueStatusInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueueStatusInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueStatusInfo(/** @type {Partial<QueueStatusInfo>} */($$parsedSource));
    }
}
