// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadTask 下载队列任务
 */
export interface DownloadTask {
    "url": string;
    "saveDir": string;
    "name": string;
    "size": number;
}

/**
 * QueueStatusInfo 队列状态（替代多返回值，Wails 自动映射为 JS object）
 */
export interface QueueStatusInfo {
    "remaining": number;
    "running": boolean;
}
