// ===== 性能面板 e2e 的**真实载荷**夹具（ADR-262 D5）=====
// 取值自 `go run . --cli --files-root tests/fixtures/ysm … --format json`（2026-09-18 实测）。
// 只保留界面真正读的键（去掉 bytes / size_bytes / models / output / filesRoot 等），数值原样。
// 立因：性能面板此前的渲染断言只在 vitest（jsdom + mock executeCLI）——不跑布局/CSS，
// 抓不到「元素被吞掉」「i18n 占位符残留」这类只在真实浏览器暴露的缺陷。

export const SINGLE_BENCH_SAVED = {
  model: "tests\\fixtures\\ysm\\shen-fengling\\ysm.json",
  iterations: 1,
  total_ms: 9.015,
  per_iteration_ms: 9.015,
  bottleneck: "② JSON 解析",
  format: "YSM",
  hints: ["所有阶段 <10ms，性能良好"],
  identity: {
    relPath: "shen-fengling/ysm.json",
    rtype: "ysm",
    rtype_label: "YSM 模型",
  },
  stages: [
    {
      name: "① 清单读取",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ 115B",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "② JSON 解析",
      ms: 7.914,
      status: "ok",
      bottleneck: false,
      note: "✅ 1 bones, 0 textures (YSM)",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 7.914,
        p95_ms: 7.914,
      },
    },
    {
      name: "③ 数据验证",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ ✅ 结构校验通过: 1 骨骼, 1 立方块, 0 纹理",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "④ 几何数据准备",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ 192B",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "⑤ 纹理数据准备",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ 0B",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "⑥ 序列化模拟",
      ms: 0.507,
      status: "ok",
      bottleneck: false,
      note: "✅ 实测载荷 239B（Wails binding 走 JSON 序列化）",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0.507,
        p95_ms: 0.507,
      },
    },
    {
      name: "⑦ 缓存检查",
      ms: 0.593,
      status: "ok",
      bottleneck: false,
      note: "⚠️ 缓存未命中（总缓存: 64 个文件, 10.1MB）",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0.593,
        p95_ms: 0.593,
      },
    },
  ],
  baseline: {
    diff: {
      path: "<repo>\\e2e-base2.json",
      threshold_pct: 50,
      noise_floor_ms: 1,
      verdict: "ok",
      degraded: 0,
      stages: [
        {
          name: "① 清单读取",
          base_ms: 0,
          now_ms: 0,
          delta_pct: 0,
          verdict: "noise",
        },
        {
          name: "② JSON 解析",
          base_ms: 8.226,
          now_ms: 7.914,
          delta_pct: -3.7928519328957107,
          verdict: "faster",
        },
        {
          name: "③ 数据验证",
          base_ms: 0,
          now_ms: 0,
          delta_pct: 0,
          verdict: "noise",
        },
        {
          name: "④ 几何数据准备",
          base_ms: 0,
          now_ms: 0,
          delta_pct: 0,
          verdict: "noise",
        },
        {
          name: "⑤ 纹理数据准备",
          base_ms: 0,
          now_ms: 0,
          delta_pct: 0,
          verdict: "noise",
        },
        {
          name: "⑥ 序列化模拟",
          base_ms: 0,
          now_ms: 0.507,
          delta_pct: 0,
          verdict: "noise",
        },
        {
          name: "⑦ 缓存检查",
          base_ms: 0,
          now_ms: 0.593,
          delta_pct: 0,
          verdict: "noise",
        },
      ],
    },
  },
};

export const SINGLE_BENCH_BASELINE_MISSING = {
  model: "tests\\fixtures\\ysm\\shen-fengling\\ysm.json",
  iterations: 1,
  total_ms: 15.191,
  per_iteration_ms: 15.191,
  bottleneck: "② JSON 解析",
  format: "YSM",
  hints: ["② JSON 解析 14.6ms：模型可能过大，考虑精简数据或使用更快的解析器"],
  identity: {
    relPath: "shen-fengling/ysm.json",
    rtype: "ysm",
    rtype_label: "YSM 模型",
  },
  stages: [
    {
      name: "① 清单读取",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ 115B",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "② JSON 解析",
      ms: 14.569,
      status: "slow",
      bottleneck: true,
      note: "✅ 1 bones, 0 textures (YSM)",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 14.569,
        p95_ms: 14.569,
      },
    },
    {
      name: "③ 数据验证",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ ✅ 结构校验通过: 1 骨骼, 1 立方块, 0 纹理",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "④ 几何数据准备",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ 192B",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "⑤ 纹理数据准备",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ 0B",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "⑥ 序列化模拟",
      ms: 0,
      status: "ok",
      bottleneck: false,
      note: "✅ 实测载荷 239B（Wails binding 走 JSON 序列化）",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0,
        p95_ms: 0,
      },
    },
    {
      name: "⑦ 缓存检查",
      ms: 0.621,
      status: "ok",
      bottleneck: false,
      note: "⚠️ 缓存未命中（总缓存: 64 个文件, 10.1MB）",
      runtime: "go",
      stats: {
        n: 1,
        median_ms: 0.621,
        p95_ms: 0.621,
      },
    },
  ],
  baseline: {
    error: "missing",
    detail: "未找到基准文件 <repo>\\e2e-none.json：请先用 --save-baseline 记录一次基准",
  },
};

export const CONC_BENCH_REAL = {
  workers: 4,
  max_models: 3,
  model_count: 3,
  serial: {
    total_ms: 11.1793,
    per_model_ms: 3.726433333333333,
  },
  parallel: [
    {
      workers: 2,
      total_ms: 1.1501,
      speedup: 9.720285192591948,
      verdict: "excellent",
    },
    {
      workers: 4,
      total_ms: 1.0243,
      speedup: 10.914087669628039,
      verdict: "excellent",
    },
  ],
  file_read: {
    file_count: 30,
    serial_ms: 3.3301,
    parallel_ms: 1.0757,
    speedup: 3.0957516036069537,
  },
  hints: ["✅ 推荐使用 4 workers，可获得 10.9x 加速", "💡 适合场景: 批量模型分析、并行文件处理"],
};

// gui-flow：由 `go test ./go/cli/ -run TestZZDumpGuiFlowPayload` 经真实代码路径
// （runGUIFlow 内部组装 + ctx.SetResult）落盘后原样搬运；唯一改动是把本机仓库绝对路径前缀
// 换成 <repo>（换机器必然不同的部分），数值与文案逐字未动。
export const GUI_FLOW_REAL = {
  stages: [
    {
      status: "✅",
      name: "① 配置加载",
      ms: 0,
      kind: "measured",
      desc: [
        "✅ 配置已加载",
        "仓库根: <repo>\\tests\\fixtures\\ysm",
        "模型根: <repo>\\tests\\fixtures\\ysm",
      ],
      runtime: "go",
    },
    {
      status: "✅",
      name: "② 模型扫描",
      ms: 0,
      kind: "measured",
      desc: [
        "✅ 发现 1 个模型",
        "类型分布: ysm: 1 [YAML: 0, YSM: 1]",
        "首个模型: <repo>\\tests\\fixtures\\ysm\\shen-fengling\\ysm.json",
      ],
      runtime: "go",
    },
    {
      status: "✅",
      name: "③ 模型分析",
      ms: 0,
      kind: "measured",
      desc: ["✅ 分析完成", "文件: ysm.json", "骨骼: 1", "纹理: 1", "预估几何: 36B"],
      runtime: "go",
    },
    {
      status: "✅",
      name: "④ 纹理缓存",
      ms: 0.522,
      kind: "measured",
      desc: ["⚠️  缓存未命中（首次加载会编码生成）", "哈希: cbc1f3094cca9865..."],
      runtime: "go",
    },
    {
      status: "✅",
      name: "⑤ 数据准备",
      ms: 0,
      kind: "measured",
      desc: [
        "📦 数据就绪",
        "载荷(实测 JSON): 118B",
        "序列化(实测): 0.00ms",
        "预计传输: 0ms (假设 50MB/s，估算)",
      ],
      estimated_ms: 0.00225,
      note: "载荷与序列化耗时为实测（118B / 0.00ms）；仅传输时间按 50MB/s 假设外推（CLI 观测不到 Wails IPC 通道），估算不计入总耗时",
      runtime: "go",
    },
    {
      status: "✅",
      name: "⑥ 渲染预估",
      ms: 0,
      kind: "estimated",
      desc: [
        "🟢 轻量负载 — 可流畅渲染",
        "⚠️ CLI 估算值（无渲染管线，仅按骨骼/纹理数粗估；真实首帧须在 GUI 验证）",
        "骨骼: 1, 纹理: 1",
        "预估首帧: 50-100ms（估算，不计入总耗时）",
      ],
      estimated_ms: 75.015,
      note: "无渲染管线：首帧按 boneCount*0.01+50 ~ *0.02+100 粗估（区间 50-100ms，此处取中值），真实首帧须在 GUI 验证",
      runtime: "three",
    },
  ],
  total_ms: 1.027,
  estimated_ms: 75.017,
  failed: false,
};

// 目标集「全库扁平 + 体量降序」= `--target repo --order size --max-models 2`（旧 --top-largest 2 的正交写法）：
// 真实 CLI 输出（2026-09-18），数值文案逐字未动。
// 注：目录式模型的 size_bytes 是 0（identity 口径），排名依据看 footprint_bytes——排序依据必须可见，
// 否则「凭什么它排第一」在界面上无从复核。

export const TARGET_REPO_SIZE_REAL = {
  spec: {
    target: "repo",
    order: "size",
    max_models: 2,
    iterations: 3,
    analyzed: 2,
    unsupported: 0,
    cli_analyzable: false,
    size_source: "dir_total",
    types: [
      {
        rtype: "ysm",
        rtype_label: "YSM 模型",
        cli_analyzable: true,
        found: 5,
        analyzed: 2,
        unsupported: 0,
        expected_stages: 7,
      },
    ],
  },
  models: [
    {
      model: "tests\\fixtures\\ysm\\博丽灵梦Hakurei_Reimu\\ysm.json",
      iterations: 3,
      total_ms: 19.57,
      per_iteration_ms: 6.523333333333333,
      stages: [
        {
          name: "① 清单读取",
          ms: 0,
          bytes: 42420,
          status: "ok",
          bottleneck: false,
          note: "✅ 41.4KB",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "② JSON 解析",
          ms: 4.486,
          status: "ok",
          bottleneck: false,
          note: "✅ 340 bones, 0 textures (YSM)",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 13.458,
          },
        },
        {
          name: "③ 数据验证",
          ms: 0,
          status: "ok",
          bottleneck: false,
          note: "✅ ✅ 结构校验通过: 340 骨骼, 723 立方块, 0 纹理",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "④ 几何数据准备",
          ms: 0,
          bytes: 102048,
          status: "ok",
          bottleneck: false,
          note: "✅ 99.7KB",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑤ 纹理数据准备",
          ms: 0,
          status: "ok",
          bottleneck: false,
          note: "✅ 0B",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑥ 序列化模拟",
          ms: 1.503,
          bytes: 441260,
          status: "ok",
          bottleneck: false,
          note: "✅ 实测载荷 430.9KB（Wails binding 走 JSON 序列化）",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 1.53,
            p95_ms: 1.921,
          },
        },
        {
          name: "⑦ 缓存检查",
          ms: 0.534,
          status: "ok",
          bottleneck: false,
          note: "⚠️ 缓存未命中（总缓存: 64 个文件, 10.1MB）",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0.594,
            p95_ms: 1.009,
          },
        },
      ],
      bottleneck: "② JSON 解析",
      hints: ["所有阶段 <10ms，性能良好"],
      format: "YSM",
      size_bytes: 0,
      footprint_bytes: 2792158,
      identity: {
        rtype: "ysm",
        rtype_source: "extension",
        rtype_label: "YSM 模型",
        form: "dir",
        filesRoot: "tests/fixtures/ysm",
        relPath: "博丽灵梦Hakurei_Reimu/ysm.json",
        absPath:
          "C:\\Users\\zhujieling11\\ysm-model-manager\\tests\\fixtures\\ysm\\博丽灵梦Hakurei_Reimu\\ysm.json",
      },
    },
    {
      model: "tests\\fixtures\\ysm\\01_taisho_maid\\ysm.json",
      iterations: 3,
      total_ms: 4.738,
      per_iteration_ms: 1.5793333333333335,
      stages: [
        {
          name: "① 清单读取",
          ms: 0,
          bytes: 5303,
          status: "ok",
          bottleneck: false,
          note: "✅ 5.2KB",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "② JSON 解析",
          ms: 0.878,
          status: "ok",
          bottleneck: false,
          note: "✅ 192 bones, 7 textures (YSM)",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 2.634,
          },
        },
        {
          name: "③ 数据验证",
          ms: 0,
          status: "ok",
          bottleneck: false,
          note: "✅ ✅ 结构校验通过: 192 骨骼, 490 立方块, 7 纹理",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "④ 几何数据准备",
          ms: 0,
          bytes: 65472,
          status: "ok",
          bottleneck: false,
          note: "✅ 63.9KB",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑤ 纹理数据准备",
          ms: 0,
          bytes: 680,
          status: "ok",
          bottleneck: false,
          note: "✅ 680B",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑥ 序列化模拟",
          ms: 0.701,
          bytes: 93015,
          status: "ok",
          bottleneck: false,
          note: "✅ 实测载荷 90.8KB（Wails binding 走 JSON 序列化）",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0.544,
            p95_ms: 1.558,
          },
        },
        {
          name: "⑦ 缓存检查",
          ms: 0,
          status: "ok",
          bottleneck: false,
          note: "⚠️ 缓存未命中（总缓存: 64 个文件, 10.1MB）",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
      ],
      bottleneck: "② JSON 解析",
      hints: ["所有阶段 <10ms，性能良好"],
      format: "YSM",
      size_bytes: 0,
      footprint_bytes: 1891138,
      identity: {
        rtype: "ysm",
        rtype_source: "extension",
        rtype_label: "YSM 模型",
        form: "dir",
        filesRoot: "tests/fixtures/ysm",
        relPath: "01_taisho_maid/ysm.json",
        absPath:
          "C:\\Users\\zhujieling11\\ysm-model-manager\\tests\\fixtures\\ysm\\01_taisho_maid\\ysm.json",
      },
    },
  ],
};

// 目标集「每类型各取 N 条 + 体量降序」= `--target all --order size --max-models 2`：
// 旧面表达不出的新组合（旧 --top-largest 把「体量降序」与「取 N 条」焊死，只能全库扁平）。
// 与上面对照读：同样 2 是上限，但 target=all 时单位是**每个类型**，target=repo 时单位是**全库**。
export const TARGET_ALL_SIZE_REAL = {
  spec: {
    target: "all",
    order: "size",
    max_models: 2,
    iterations: 3,
    analyzed: 2,
    unsupported: 0,
    cli_analyzable: false,
    size_source: "dir_total",
    types: [
      {
        rtype: "ysm",
        rtype_label: "YSM 模型",
        cli_analyzable: true,
        found: 5,
        analyzed: 2,
        unsupported: 0,
        expected_stages: 7,
      },
    ],
  },
  models: [
    {
      model: "tests\\fixtures\\ysm\\博丽灵梦Hakurei_Reimu\\ysm.json",
      iterations: 3,
      total_ms: 20.29,
      per_iteration_ms: 6.763333333333333,
      stages: [
        {
          name: "① 清单读取",
          ms: 0,
          bytes: 42420,
          status: "ok",
          bottleneck: false,
          note: "✅ 41.4KB",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "② JSON 解析",
          ms: 5.241,
          status: "ok",
          bottleneck: false,
          note: "✅ 340 bones, 0 textures (YSM)",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 1.544,
            p95_ms: 14.178,
          },
        },
        {
          name: "③ 数据验证",
          ms: 0,
          status: "ok",
          bottleneck: false,
          note: "✅ ✅ 结构校验通过: 340 骨骼, 723 立方块, 0 纹理",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "④ 几何数据准备",
          ms: 0,
          bytes: 102048,
          status: "ok",
          bottleneck: false,
          note: "✅ 99.7KB",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑤ 纹理数据准备",
          ms: 0,
          status: "ok",
          bottleneck: false,
          note: "✅ 0B",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑥ 序列化模拟",
          ms: 1.013,
          bytes: 441260,
          status: "ok",
          bottleneck: false,
          note: "✅ 实测载荷 430.9KB（Wails binding 走 JSON 序列化）",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 1.503,
            p95_ms: 1.537,
          },
        },
        {
          name: "⑦ 缓存检查",
          ms: 0.508,
          status: "ok",
          bottleneck: false,
          note: "⚠️ 缓存未命中（总缓存: 64 个文件, 10.1MB）",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 1.526,
          },
        },
      ],
      bottleneck: "② JSON 解析",
      hints: ["所有阶段 <10ms，性能良好"],
      format: "YSM",
      size_bytes: 0,
      footprint_bytes: 2792158,
      identity: {
        rtype: "ysm",
        rtype_source: "extension",
        rtype_label: "YSM 模型",
        form: "dir",
        filesRoot: "tests/fixtures/ysm",
        relPath: "博丽灵梦Hakurei_Reimu/ysm.json",
        absPath:
          "C:\\Users\\zhujieling11\\ysm-model-manager\\tests\\fixtures\\ysm\\博丽灵梦Hakurei_Reimu\\ysm.json",
      },
    },
    {
      model: "tests\\fixtures\\ysm\\01_taisho_maid\\ysm.json",
      iterations: 3,
      total_ms: 6.547,
      per_iteration_ms: 2.1823333333333332,
      stages: [
        {
          name: "① 清单读取",
          ms: 0,
          bytes: 5303,
          status: "ok",
          bottleneck: false,
          note: "✅ 5.2KB",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "② JSON 解析",
          ms: 1.849,
          status: "ok",
          bottleneck: false,
          note: "✅ 192 bones, 7 textures (YSM)",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 1.078,
            p95_ms: 3.963,
          },
        },
        {
          name: "③ 数据验证",
          ms: 0,
          status: "ok",
          bottleneck: false,
          note: "✅ ✅ 结构校验通过: 192 骨骼, 490 立方块, 7 纹理",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "④ 几何数据准备",
          ms: 0,
          bytes: 65472,
          status: "ok",
          bottleneck: false,
          note: "✅ 63.9KB",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑤ 纹理数据准备",
          ms: 0,
          bytes: 680,
          status: "ok",
          bottleneck: false,
          note: "✅ 680B",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑥ 序列化模拟",
          ms: 0,
          bytes: 93015,
          status: "ok",
          bottleneck: false,
          note: "✅ 实测载荷 90.8KB（Wails binding 走 JSON 序列化）",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 0,
          },
        },
        {
          name: "⑦ 缓存检查",
          ms: 0.333,
          status: "ok",
          bottleneck: false,
          note: "⚠️ 缓存未命中（总缓存: 64 个文件, 10.1MB）",
          runtime: "go",
          stats: {
            n: 3,
            median_ms: 0,
            p95_ms: 1,
          },
        },
      ],
      bottleneck: "② JSON 解析",
      hints: ["所有阶段 <10ms，性能良好"],
      format: "YSM",
      size_bytes: 0,
      footprint_bytes: 1891138,
      identity: {
        rtype: "ysm",
        rtype_source: "extension",
        rtype_label: "YSM 模型",
        form: "dir",
        filesRoot: "tests/fixtures/ysm",
        relPath: "01_taisho_maid/ysm.json",
        absPath:
          "C:\\Users\\zhujieling11\\ysm-model-manager\\tests\\fixtures\\ysm\\01_taisho_maid\\ysm.json",
      },
    },
  ],
};

// 引擎对照 scan-bench：真实 CLI 输出（2026-09-18，`--iterations 2 --format json`）。
// 两份载荷是**同一条命令在两种构建下**的真实结果，对照读才有意义：
//   - 默认构建（无 rust_backend）：Go 有实测，Rust `used=false` + `reason="unavailable"`，
//     `parity.comparable=false`——**0.00ms 不得出现**，界面必须写「未采集」；
//   - `-tags rust_backend` 构建：两端都实测（条目数一致）且 `parity.match=true`。
// 数值逐字未动（含 runs_ms 抖动），只保留界面读的键。
// 注：rust 行的 `skipped` 是「请求了 Rust 却没记成样本」的次数——stub 构建下每次请求都被
// 生产兜底逻辑走成 Go，故为 2，界面应如实说明而不是当作 0 次。
export const SCAN_BENCH_REAL = {
  spec: {
    files_root: "tests/fixtures/ysm",
    iterations: 2,
    build_backend: "go",
  },
  engines: [
    {
      engine: "go",
      used: true,
      runs_ms: [2.69, 1.688],
      median_ms: 1.688,
      p95_ms: 2.69,
      entries: 5,
      skipped: 0,
    },
    {
      engine: "rust",
      used: false,
      reason: "unavailable",
      entries: 0,
      skipped: 2,
    },
  ],
  parity: {
    comparable: false,
    match: false,
  },
};

// `-tags rust_backend` 构建的真实输出（2026-09-18）——两端都实测到，故 parity 可比且一致。
export const SCAN_BENCH_RUST_REAL = {
  spec: {
    files_root: "tests/fixtures/ysm",
    iterations: 2,
    build_backend: "rust",
  },
  engines: [
    {
      engine: "go",
      used: true,
      runs_ms: [2.615, 1.639],
      median_ms: 1.639,
      p95_ms: 2.615,
      entries: 5,
      skipped: 0,
    },
    {
      engine: "rust",
      used: true,
      runs_ms: [5.171, 1.004],
      median_ms: 1.004,
      p95_ms: 5.171,
      entries: 5,
      skipped: 0,
    },
  ],
  parity: {
    comparable: true,
    match: true,
  },
};
