// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateInfo 更新信息（序列化给前端）
 */
export interface UpdateInfo {
    "available": boolean;
    "latest": string;
    "current": string;
    "url": string;
    "sha256sumsUrl"?: string;
    "expectedHash"?: string;
    "releaseNotes"?: string;
}
