// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheStatus 缓存状态
 * 
 * 关于「命中率」的口径（2026-09 重写，勿退回到旧实现）：
 *   - 旧实现：HitRate = 全局缓存目录文件数 / 本仓库纹理数——**语义错误**。分子
 *     （CacheStats.FileCount，内容哈希键、跨仓库跨类型共享）与分母（本仓库纹理数）
 *     不同源、无因果关系，比例随缓存增长必然 >100%，被 `>100 截断` 掩盖成「命中率
 *     100%」假绿。已于 2026-09-14 删除。
 *   - 现实现：逐纹理 TextureHash(内容) → 查缓存集 → 真实命中计数。分子分母同源
 *     （都是本仓库纹理），与 `cache-verify` 命令同口径。字段复用旧名但语义已变。
 */
export interface CacheStatus {
    "cache_dir": string;
    "cache_files": number;
    "cache_size": number;

    /**
     * ShouldWarn 容量接近上限（texture_cache 阈值），体检页提示清理
     */
    "should_warn"?: boolean;

    /**
     * HitRate 本仓库纹理的缓存命中率（0~100）。CacheSampled 为真时是基于采样
     * 的估计值（纹理数超 cacheHitSampleLimit），前端应标注「≈」。
     */
    "hit_rate"?: number;

    /**
     * Hits / Misses 本仓库纹理中命中/未命中缓存的**文件数**（非全局缓存条目数）。
     */
    "hits"?: number;
    "misses"?: number;

    /**
     * CacheSampled 命中率是否来自采样（纹理数超上限）。
     */
    "cache_sampled"?: boolean;

    /**
     * CacheScanErrors 命中率统计过程中的哈希/探测失败数（非文件本身损坏）。
     * 失败纹理不计入分子分母，失败数可见以免「故障」被误读为「全部未缓存」。
     */
    "cache_scan_errors"?: number;
}

/**
 * Completeness 完整性统计
 */
export interface Completeness {
    "checked": number;
    "valid": number;
    "invalid": number;
    "percentage": number;
}

/**
 * DedupSummary 去重维度汇总（HealthReport 追加）
 */
export interface DedupSummary {
    "groups": number;
    "extra_files": number;
    "reclaim_bytes": number;
}

/**
 * HealthReport 完整体检：审计 + 去重（GUI 与 CLI health-report 同一载荷）
 */
export interface HealthReport {
    "timestamp": string;
    "directory": string;
    "score": number;
    "completeness": Completeness;
    "cache": CacheStatus;
    "resources": ResourceSummary;
    "dedup": DedupSummary;
    "warnings"?: string[] | null;
}

/**
 * ResourceSummary 资源统计
 */
export interface ResourceSummary {
    "total_files": number;
    "total_size": number;
    "banned": number;
    "by_type": { [_ in string]?: number } | null;
    "largest_file"?: string;
    "largest_size"?: number;
}
