// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheStatus 缓存状态
 */
export interface CacheStatus {
    "cache_dir": string;
    "cache_files": number;
    "cache_size": number;
    "hit_rate": number;
    "hits": number;
    "misses": number;

    /**
     * ShouldWarn 容量接近上限（texture_cache 阈值），体检页提示清理
     */
    "should_warn"?: boolean;
}

/**
 * Completeness 完整性统计
 */
export interface Completeness {
    "checked": number;
    "valid": number;
    "invalid": number;
    "percentage": number;
}

/**
 * DedupSummary 去重维度汇总（HealthReport 追加）
 */
export interface DedupSummary {
    "groups": number;
    "extra_files": number;
    "reclaim_bytes": number;
}

/**
 * HealthReport 完整体检：审计 + 去重（GUI 与 CLI health-report 同一载荷）
 */
export interface HealthReport {
    "timestamp": string;
    "directory": string;
    "score": number;
    "completeness": Completeness;
    "cache": CacheStatus;
    "resources": ResourceSummary;
    "dedup": DedupSummary;
    "warnings"?: string[] | null;
}

/**
 * ResourceSummary 资源统计
 */
export interface ResourceSummary {
    "total_files": number;
    "total_size": number;
    "banned": number;
    "by_type": { [_ in string]?: number } | null;
    "largest_file"?: string;
    "largest_size"?: number;
}
